### ISSUE TITLE
Plans for cce_node_pool and cce_addon data sources

### ISSUE THREAD

**Issue by ippeter** [huaweicloud/terraform-provider-huaweicloud#1005]
Good afternoon!

When do you have plans to implement cce_node_pool and cce_addon data sources?

Best regards,
Peter.

**Comment by niuzhenguo** [comment]
Sorry for the late response, it will be available on release 1.24.0.

**Comment by ippeter** [comment]
Zhenguo, thank you for the update!

Will it be possible to **import** these resources as well in 1.24.0?

**Comment by Jason-Zhang9309** [comment]
@ippeter 
Hi, I'm developing new data source for cce addon.
What information do you mainly want from the data source?
List all addon instances in a cluster? Or details of a specific addon instance?
The API returns a lot of attributes, it will be very helpful if you can tell me which ones you need.

**Comment by ippeter** [comment]
@Jason-Zhang9309 
Dear Jason:

thank you for the support!

I think I confused you a bit, and I'm sorry, if it's really so.
There is a "huaweicloud_cce_addon" resource, which adds a specific addon into a specific CCE cluster.
I want to perform a reverse action: I need to import this very addon into the Terraform state and be able to manage it later, as if it was created as new.
So it's not really a datasource, but the **import** operation.

**Comment by Jason-Zhang9309** [comment]
@ippeter 
Thanks for your response. I've clearly understood your needs for cce addon.
How about cce node pool? Need import operation too？

**Comment by ippeter** [comment]
@Jason-Zhang9309 
Dear Jason, yes, this is correct: I need the same **import** feature for cce node pools.

**Comment by Jason-Zhang9309** [comment]
@ippeter 
Understood. 
But due to time constraints we have to move these feathers to release v1.25.0, which should be availiable by the end of next month.
Sorry about that.
