### ISSUE TITLE
cce_addon with configuration

### ISSUE THREAD

**Issue by littlejo** [huaweicloud/terraform-provider-huaweicloud#1039]
Hello,

i tried to install autoscaler cce addon:

```
resource "huaweicloud_cce_addon" "autoscaler" {
    cluster_id    = huaweicloud_cce_cluster.this.id
    template_name = "autoscaler"
    version       = "1.17.8"
}
```

But it does not work because there is no configuration.

In documentation, i read:

> values - (Optional, List, ForceNew) Add-on template installation parameters. These parameters vary depending on the add-on.

> The values block supports:
>
>    basic - (Required, Map) Key/Value pairs vary depending on the add-on.
>    custom - (Optional, Map) Key/Value pairs vary depending on the add-on.

https://registry.terraform.io/providers/huaweicloud/huaweicloud/latest/docs/resources/cce_addon#values

But how to find key/value? Where is it documented?

**Comment by Lance52259** [comment]
@littlejo [`values`](https://support.huaweicloud.com/en-us/api-cce/cce_02_0321.html) is the installation parameter of the addon template. We will provide a data-source for filtering and querying the addon template in the future.

**Comment by nttd-dongxuguo** [comment]
Hi,cce addon is not supported in version 1.23.1 ？

**Comment by nttd-dongxuguo** [comment]
@Lance52259 Hi,cce addon is not supported in version 1.23.1 ？

**Comment by Lance52259** [comment]
Not yet. We are waiting for API support.
