### ISSUE TITLE
Relax ForceNew requirement wherever possible in huaweicloud_fgs_function

### ISSUE THREAD

**Issue by siviae** [huaweicloud/terraform-provider-huaweicloud#1040]
Hello!

For now, all  huaweicloud_fgs_function parameter are marked as ForceNew. However, according to documentation
https://support.huaweicloud.com/intl/en-us/api-functiongraph/functiongraph_06_0110.html
https://support.huaweicloud.com/intl/en-us/api-functiongraph/functiongraph_06_0111.html
this is not necessary - some function parameters could be updated without the need to recreate the function.

There are multiple problems with ForceNew for all parameters:
- not all parameters, which are available in console, are available in Terraform provider (these include init handler, xrole aka agency (exists but does not seem to work), vpc and mount configuration). This could be workarounded, if the function was created in Terraform and enriched with necessary parameters from Console after that. But since function is recreated on each Terraform apply if something (i.e. function code) changed, these amendments made in console are cleared and have to be made again, which is very inconvenient during development.
- IDK if this is a bug or feature, but every time I recreate the function, the dependent API Gateway API is unpublished, even though function urn is not changed.

### Affected Resource(s)
Please list the resources as a list, for example:
- **huaweicloud_fgs_function**

### Expected Behavior
Function should not be recreated if this is not absolutely necessary.

### Actual Behavior
Function is recreated on all, even smallest, changes.

Thank you in advance!

**Comment by Jason-Zhang9309** [comment]
Hi there, 
Sorry for late response. And thank you for these helpful suggestions. 
Support for update in huaweicloud_fgs_function is under consideration and should be available soon.

As for the API unpublished problem, I tested calling func according to https://support.huaweicloud.com/intl/en-us/api-functiongraph/functiongraph_06_0125.html, but did not encounter any problems.
Could you provide more information?
