### ISSUE TITLE
huaweicloud_cce_node_v3.node_1: : invalid or unknown key: node_count

### ISSUE THREAD

**Issue by Thomas999999** [huaweicloud/terraform-provider-huaweicloud#105]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### Terraform Version
Terraform v0.11.13
+ provider.huaweicloud v1.4.0

### Affected Resource(s)
huaweicloud_cce_node_v3

### Terraform Configuration Files
```hcl
##worker nodes
resource "huaweicloud_cce_node_v3" "node_1" {
    cluster_id         = "${huaweicloud_cce_cluster_v3.cluster_1.id}"
    name               = "${var.cce_cluster_name}-node"
    #os: see https://github.com/terraform-providers/terraform-provider-huaweicloud/issues/97
    #os                 = "${var.cce_node_os}"
    flavor_id          = "${var.worker_flavor_id}"
    iptype             = "5_bgp"
    eip_count          = "${var.worker_node_capacity}"
    billing_mode       = "0"
    node_count         = "${var.worker_node_capacity}"
    availability_zone  = "${var.availability_zone}"
    key_pair           = "${var.key_pair}"
    root_volume        = {
                         size= 40,
                         volumetype= "SATA"
                         }
    sharetype          = "PER"
    bandwidth_size     = "100"
    bandwidth_charge_mode = "traffic"
    data_volumes       = [
                       {
                        size= 128,
                        volumetype= "SATA"
                       },
    ]
  }

### Expected Behavior
Automated creation of several nodes for a cluster by just adding a count for nodes and automated EIP creation and binding for  each created node (as it is possible to do in the console)

I found in https://www.terraform.io/docs/providers/huaweicloud/r/cce_nodes_v3.html 2 keys:

- **node_count - (Required) The number of nodes in batch creation.**
- **eip_count - (Optional) Number of elastic IPs to be dynamically created. Changing this parameter will create a new resource.**

### Actual Behavior
Getting issue with node_count despite it is mentioned as required in documentation:
....
[root@d021970-ha-jump terraform_CCE]# terraform plan
Error: huaweicloud_cce_node_v3.node_1: : invalid or unknown key: node_count

**Comment by niuzhenguo** [comment]
@Thomas999999 I'm sorry that there's no `node_count` supported, docs need to be fixed, but if you want to create serveral nodes you can just use `count` parameter which can be used for all resources.

**Comment by Thomas999999** [comment]
Hi,
ok count worked, but still the same issue as in 
https://github.com/terraform-providers/terraform-provider-huaweicloud/issues/106 

Terraform tells me that 4 nodes created, but looking at console it was not the case, no nodes created and added to cluster

**Comment by Thomas999999** [comment]
> Hi,
> ok count worked, but still the same issue as in
> #106
> 
> Terraform tells me that 4 nodes created, but looking at console it was not the case, no nodes created and added to cluster

this has been solved meanwhile, thus only documentation update from node-count to count as key necessary.
