### ISSUE TITLE
RDS deployment crash with v1.23.1 version

### ISSUE THREAD

**Issue by littlejo** [huaweicloud/terraform-provider-huaweicloud#1054]
### Summary

Terraform plan works

But terraform apply crash with:
Error: rpc error: code = Unavailable desc = transport is closing

No problem in 1.22.1

### Terraform Version

```
terraform -v
Terraform v0.14.9
+ provider registry.terraform.io/huaweicloud/huaweicloud v1.23.1

Your version of Terraform is out of date! The latest version
is 0.14.10. You can update by downloading from https://www.terraform.io/downloads.html
```

### Terraform Configuration Files

```hcl
module "rds" {
  source    = "./rds"
  name      = "${local.env}-rds"
  password  = var.rds_password
  sg_id     = module.postgres_sg.id
  subnet_id = data.huaweicloud_vpc_subnet.subnet.id
  vpc_id    = data.huaweicloud_vpc_subnet.subnet.vpc_id
}
```

content of module:

```hcl
data "huaweicloud_availability_zones" "myaz" {}

resource "huaweicloud_rds_instance" "instance" {
  db {
    password = var.password
    type     = "PostgreSQL"
    version  = "10"
    port     = var.port
  }
  ha_replication_mode = "async"
  name                = var.name
  security_group_id   = var.sg_id
  subnet_id           = var.subnet_id
  vpc_id              = var.vpc_id
  availability_zone = [
    data.huaweicloud_availability_zones.myaz.names[0],
    data.huaweicloud_availability_zones.myaz.names[1]
  ]
  volume {
    type = "ULTRAHIGH"
    size = 40
  }
  flavor = var.flavor
  backup_strategy {
    start_time = "08:00-09:00"
    keep_days  = 1
  }
}
```

### Debug Output

https://gist.github.com/littlejo/11982befc7ea4da33f322c2900bdf6ae

### Crash Output

https://gist.github.com/littlejo/d4e66b9df50a9842d6fee1b51c4908fa

### Expected Behavior

rds instance should be create

### Actual Behavior

no creation of rds instance and crash of terraform (tfstate not update)

### Steps to Reproduce

Module is there:

https://github.com/littlejo/terraform-huawei-rds
I just changed provider version to the latest version

1. `terraform init`
2. `terraform apply`

**Comment by ShiChangkuo** [comment]
@littlejo thanks for rasing this issue, we will fix it in v1.24.0.
For now, you can use the provider prior to v1.22.3 or without **ha_replication_mode** in your module.
