### ISSUE TITLE
huaweicloud_networking_secgroup_rule_v2: cannot pass list of IP ranges

### ISSUE THREAD

**Issue by Thomas999999** [huaweicloud/terraform-provider-huaweicloud#108]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### Terraform Version
Terraform v0.11.13
+ provider.huaweicloud v1.4.0

### Affected Resource(s)
huaweicloud_networking_secgroup_rule_v2

### Terraform Configuration Files
```hcl
resource "huaweicloud_networking_secgroup_rule_v2" "sg_rule_Germany" {
  direction         = "ingress"
  ethertype         = "IPv4"
  protocol          = "tcp"
  port_range_min    = 1
  port_range_max    = 65535
  remote_ip_prefix  = ["213.69.10.216/29","194.25.175.56/29","217.7.186.120/29","213.61.167.32/27","213.252.8.208/28","213.68.42.72/29","195.145.172.80/29","195.127.230.24/29","213.68.42.192/29","217.7.22.32/29","195.125.167.88/29","217.89.162.216/29","217.89.105.48/29","195.127.230.0/29","195.126.101.152/29","213.68.111.208/29","155.56.44.0/24","155.56.68.208/28","193.16.224.0/24","37.34.69.0/27"]
  #remote_ip_prefix  = "193.16.224.0/24"
  security_group_id = "${huaweicloud_networking_secgroup_v2.secgroup_sap_all.id}"
}

### Expected Behavior
I would like to pass many IP ranges for inbound or outbound rules as a list, but this seems not to be possible.
I could not find any other key, which may handle this, or did I overlook something?

### Actual Behavior
[root@d021970-ha-jump terraform_CCE]# terraform plan

Error: huaweicloud_networking_secgroup_rule_v2.sg_rule_Germany: remote_ip_prefix must be a single value, not a list

**Comment by niuzhenguo** [comment]
@Thomas999999 It's not possible as the type of the remote_ip_prefix parameter is String. One rule can only have one IP range, this also not possible on console as I know. But maybe you can use `count` here to replicate the secgroup rule.

**Comment by Thomas999999** [comment]
So could post a feature request here to add list support for  remote_ip_prefix?
It is for example possible in AWS or AZURE like this:

#inbound rules
  ingress {
    from_port   = 0
    to_port     = 65535
    protocol    = "tcp"
    **cidr_blocks = ["213.69.10.216/29","194.25.175.56/29","217.7.186.120/29","213.61.167.32/27","213.252.8.208/28","213.68.42.72/29","195.145.172.80/29","195.127.230.24/29","213.68.42.192/29","217.7.22.32/29","195.125.167.88/29","217.89.162.216/29","217.89.105.48/29","195.127.230.0/29","195.126.101.152/29","213.68.111.208/29","155.56.44.0/24","155.56.68.208/28","193.16.224.0/24","37.34.69.0/27"]**
    description = "Allow inbound traffic from SAP Germany"
  }

**Comment by niuzhenguo** [comment]
```
variable "sec_ips" {
  default = ["213.69.10.216/29","194.25.175.56/29","217.7.186.120/29","213.61.167.32/27","213.252.8.208/28","213.68.42.72/29","195.145.172.80/29","195.127.230.24/29","213.68.42.192/29","217.7.22.32/29","195.125.167.88/29","217.89.162.216/29","217.89.105.48/29","195.127.230.0/29","195.126.101.152/29","213.68.111.208/29","155.56.44.0/24","155.56.68.208/28","193.16.224.0/24","37.34.69.0/27"]
}

resource "huaweicloud_networking_secgroup_rule_v2" "sg_rule_Germany" {
  count              = 20
  direction         = "ingress"
  ethertype         = "IPv4"
  protocol          = "tcp"
  port_range_min    = 1
  port_range_max    = 65535
  remote_ip_prefix  =  "${element(var.sec_ips,count.index)}"
  security_group_id = "${huaweicloud_networking_secgroup_v2.secgroup_sap_all.id}"
}

**Comment by Thomas999999** [comment]
ok thanks, just saw your proposal

Would like to thank you for your patience and collaboration!

**Comment by niuzhenguo** [comment]
@Thomas999999 Maybe you can create a feature request on Cloud side, then when API allows us to pass a list of ips, we can make a change on our side.

**Comment by Thomas999999** [comment]
Ok, will close issue as workaround provided above
