### ISSUE TITLE
CCI (Cloud Container Instance) service resource support

### ISSUE THREAD

**Issue by namoshizun** [huaweicloud/terraform-provider-huaweicloud#1081]
Hiii guys,

I noticed there was once a [PR](https://github.com/huaweicloud/terraform-provider-huaweicloud/pull/294) adding CCI support into the provider. But the feature seems to have been removed? I can't find it anywhere on the documentation.

In case it did have been removed, is it still possible to add CCI support back as it will be a very useful resource for us. Specifically, we'd like to avoid manually maintaining a bunch of CCI resources like ConfigMap, Secret and PersistentVolume, and do it in Terraform instead~ 

Thanks a lot.

**Comment by niuzhenguo** [comment]
@namoshizun Sorry for the late response, the reason why we remove the CCI resource is because there's no enough testing for that, will take a look at this again and see whether we can support it.
BTW, does the original CCI resources work for you?

**Comment by namoshizun** [comment]
> @namoshizun Sorry for the late response, the reason why we remove the CCI resource is because there's no enough testing for that, will take a look at this again and see whether we can support it.
> BTW, does the original CCI resources work for you?

Do you mean the already removed CCI resource feature o.0? Uh I haven't tried it so I am not really sure about its functionality. But yeah it'd be good to see them back again... :D
