### ISSUE TITLE
[feature] User Access Key management by Terraform

### ISSUE THREAD

**Issue by alexandrovas** [huaweicloud/terraform-provider-huaweicloud#1084]
Hello!

Is it possible to implement Access Key (AK) management through Terraform? IAM users are constantly being created in my project. At the moment, we have to create users through Terraform, and then manually create AK / SK for them. It is very labor intensive.

I think that many users of Huaweicloud provider have faced this problem.

### Current Terraform Version

Provider version: 1.23.1

**Comment by ShiChangkuo** [comment]
@alexandrovas The Access key is a critical credentials which should **not share** with anyone.

I think you can create IAM users by Terraform, then let the new users to create the Access Key in console.

**Comment by alexandrovas** [comment]
@ShiChangkuo I create service accounts for my applications which connects to OBS buckets. I have to first create them via terraform, and then manually generate AK/SK for them via IAM Web interface.

By Terraform I can create user and set password for it. Password is also critical credential. Why I can set a password via terraform, but AK/SK cannot?

**Comment by ShiChangkuo** [comment]
@alexandrovas the password is required to reset at the first login.

I think we can manage the access key via terraform by storing in a file or encrypting it, will implement it next month.
