### ISSUE TITLE
update addon schema to allow "flavor" selection

### ISSUE THREAD

**Issue by Ya-S** [huaweicloud/terraform-provider-huaweicloud#1098]
Hello,

I am try to deploy autoscaler addon in HA mode, but the provider does not support the "flavor" bloc. Could it be possible to update the addon schema to add this bloc, or should i add it and make a pull request ?

**Comment by niuzhenguo** [comment]
@Jason-Zhang9309 pls have a look at this.

**Comment by Ya-S** [comment]
Here is a proposal:

https://github.com/huaweicloud/terraform-provider-huaweicloud/pull/1103

**Comment by ShiChangkuo** [comment]
closed by #1103
