### ISSUE TITLE
这玩意能用吗？

### ISSUE THREAD

**Issue by xiaoxi-note** [huaweicloud/terraform-provider-huaweicloud#11]
就不能参考官方的示例写吗？
你们开发不看官方demo 的吗 ？
找个参数没有，找个demo 也没有。。。

**Comment by xiaoxi-note** [comment]
来来来，你帮我写一个 购买一个按量付费 云主机的 配置文件，按照现有文档配置不出来。

**Comment by xiaoxi-note** [comment]
@freesky-edward 来来来，你帮我写一个 购买一个按量付费 云主机的 配置文件，按照现有文档配置不出来。

**Comment by freesky-edward** [comment]
@xiaoxi-note all resources created by this provider are on demand #12 . no special configuration need. anything I missed?
