### ISSUE TITLE
Filter option missing for data huaweicloud_networking_secgroup_v2

### ISSUE THREAD

**Issue by Thomas999999** [huaweicloud/terraform-provider-huaweicloud#114]
Hi there,

### Terraform Version
Terraform v0.11.13
+ provider.huaweicloud v1.4.0
+ provider.null v2.1.2

### Affected Resource(s)
huaweicloud_networking_secgroup_v2

### Terraform Configuration Files
```hcl
#recognize the 2 sec-groups from Cluster and worker nodes to be assigned to the jumphost
data "huaweicloud_networking_secgroup_v2" "cce_sg" {
    depends_on        = [ "huaweicloud_cce_node_v3.cce_node" ]
    filter {
        name = "group-name"
        values = ["${var.cce_cluster_name}-cce*"] 
    }
}

### Expected Behavior
I need to get the 2 sec-group ids created automatically during CCE cluster and worker nodes setup as I need them later-on to apply to my jumphost.
Thus I tried the same as it was working in AWS for example:
Using data-source to filter the security group name first as list, but key filter is unknown.

I would expect to have an option/key to filter/get sec-group name/id for later use.

### Steps to Reproduce
C:\Testinfo\AWS_Dathub_Vora\Huawei-Cluster\cluster-dev>terraform plan

Error: data.huaweicloud_networking_secgroup_v2.cce_sg: : invalid or unknown key: filter

Thanks,
Thomas

**Comment by niuzhenguo** [comment]
@Thomas999999 Please reference to https://github.com/terraform-providers/terraform-provider-flexibleengine/issues/132 , but I'm not sure if the CCE team will add security group attribute support with CCE cluster on HuaweiCloud as well, you can create a Request for this on Cloud side.

**Comment by Thomas999999** [comment]
created request via service ticket on cloud side

**Comment by niuzhenguo** [comment]
@Thomas999999 seems you can use `name` filter as a workaround.
The security group names are {cce name}-cce-control-rat0 and {cce name}-cce-node-rat0

**Comment by Thomas999999** [comment]
I do not understand that, as we have always new names with each new cluster created by a suffix that is randomly created and not know during terraform runtime of a cluster creation, but I need them during runtime.

For example my names are:
**Cluster d021970-ha-dh25-cce**
d021970-ha-dh25-cce-cce-control-**qm78**
d021970-ha-dh25-cce-cce-node-**qm78**

**Cluster d021970-socat**
d021970-socat-cce-node-**mm7a**
d021970-socat-cce-control-**mm7a**

Therefore I tried to use the filter option to filter  {cce name}-cce* to get the 2 groups...

**Comment by niuzhenguo** [comment]
@Thomas999999 Oh, sorry for the misleading, I was thinking the suffix is fixed.

**Comment by niuzhenguo** [comment]
@Thomas999999 Maybe I can try to list the security groups and filter by names on Terraform side instead of waiting a long time for Cloud side change. Will dig more.

**Comment by Thomas999999** [comment]
Dear Niuzhenguo,

do you have already an workaround for that?
Thanks

**Comment by niuzhenguo** [comment]
@Thomas999999 Sorry for the late response, we need to wait for the CCE API update to import such security group information.

**Comment by niuzhenguo** [comment]
Closing this, will add a feature request issue to track it when Cloud side updated.
