### ISSUE TITLE
Plan for MRS v2

### ISSUE THREAD

**Issue by Jason-Zhang9309** [huaweicloud/terraform-provider-huaweicloud#1149]
Now the mrs cluster resource is using v1.1 API, not the latest v2 API.
For that reason, some features are not supported. That contains:
MIXED and CUSTOM types of cluster
security group of cluster
public ip of cluster
enterprise_project_id of of cluster
configurable type and size of master node disk
configurable type, size and number of core node disk
agency of cluster
Flink type of job

We should plan to upgrade the mrs resource to v2

**Comment by ShiChangkuo** [comment]
both `huaweicloud_mrs_cluster` and `huaweicloud_mrs_job` should be updated with v2 APIs.
