### ISSUE TITLE
Keep secret key in state file

### ISSUE THREAD

**Issue by alexandrovas** [huaweicloud/terraform-provider-huaweicloud#1188]
In version 1.25.0 you released new resource `huaweicloud_identity_access_key` (see https://github.com/huaweicloud/terraform-provider-huaweicloud/issues/1084), but it is impossible to use these resources in my conditions.
In current implementation the secret will be exported to CSV-file, that is very unusable for cases when terraform is built into the CI/CD process. In my case terraform state is stored in Gitlab with encryption (see this docs: https://docs.gitlab.com/ee/user/infrastructure/) and I cannot use CSV files for export secret keys from my CI/CD process.
Current implementation also does not match best practices of terraform. See this: https://www.terraform.io/docs/extend/best-practices/sensitive-state.html#don-39-t-encrypt-state

I think that this resource should be implemented as in AWS provider: https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/iam_access_key

Therefore, the `secret` field must remain readable (if field `pgp_key` is absent). Encryption should be left to the user's choice (use the PGP key or use a secure backend).

**Comment by ShiChangkuo** [comment]
We just keep the same behavior with HuaweiCloud Console, as the secret key is a critical credentials, and we **should not** share with anyone.

The secret key will be stored in **./credentials-{{user name}}.csv** by default. And `secret` field is set only when writing to csv file failed.

I think you can use `pgp_key` to store the secret in `encrypted_secret`. Maybe this way is not convenient, but it is more security.

**Comment by ShiChangkuo** [comment]
I'm going to close this issue because there are no updates for 30 days.
If you have found a problem that seems similar to this, please open a new issue and complete the issue template so we can capture all the details necessary to investigate further.

**Comment by jbg** [comment]
> We just keep the same behavior with HuaweiCloud Console

What is the motivation for making the Terraform provider behave the same way as a point-and-click console? They are different tools with different purposes.

The current approach is inflexible and does not match best practices adopted by all other cloud providers in their Terraform implementation. Please reconsider changing it. Forcing users to add a second ad-hoc layer of PGP encryption when their state is already encrypted and secured is not "more security", it's nonsense.

**Comment by jbg** [comment]
> And secret field is set only when writing to csv file failed.

Furthermore, this statement, which also appears in the documentation, appears not to be true. When writing to the CSV file fails, applying the resource actually exits with an error:

```
│ Error: Error saving the access key to /this/path/does/not/exist/to/try/to/force/the/access/key/not/to/be/written/to/a/file/on/disk: open /this/path/does/not/exist/to/try/to/force/the/access/key/not/to/be/written/to/a/file/on/disk: no such file or directory
│ 
│   with huaweicloud_identity_access_key.redacted,
│   on redacted.tf line 162, in resource "huaweicloud_identity_access_key" "redacted":
│  162: resource "huaweicloud_identity_access_key" "redacted" {
│ 
╵
```
