### ISSUE TITLE
Not being able to attach multiple evs disks to one vault on terraform in an easier way

### ISSUE THREAD

**Issue by albertocrj** [huaweicloud/terraform-provider-huaweicloud#1208]
### Terraform Version

```
Terraform v0.15.0
huaweicloud/huaweicloud v1.25.0
```

### Terraform Configuration Files

```hcl
Today the only code that worked for me is this (**which is a VERY POOR implementation**):

resource "huaweicloud_cbr_vault" "vault" {
  name                   = "vault-${var.env}-${var.project}"
  type                   = var.vault_type
  protection_type        = var.protection_type
  consistent_level       = var.consistent_level
  size                   = var.vault_size
  auto_expand            = var.auto_expand
  policy_id              = var.policy_id

   resources {
     id = "7d95d51b-95a7-4feb-99f9-a81274f35fd1"
     include_volumes  = ["750991e7-9d47-437a-baca-1b2d1323ad42"]
   }
}
```

In my case, I have some instances with just one disk, so I have to put one of these disks as ID and rest of disks IDs (from others machines) in include_volumes filed.

### Expected Behavior

I can think in 2 good solutions for that:

1. Be able to use "resources" ID field as a list (similar to include_volumes), so I can declare multiple disks IDs at once (or multiple instances IDs if I'm using server type), like this:
```hcl
 resources {
     id = "[750991e7-9d47-437a-baca-1b2d1323ad42 , 7d95d51b-95a7-4feb-99f9-a81274f35fd1]"
   }
```
2. Have another way to attach evs disks to one vault (like eip attach "huaweicloud_compute_floatingip_associate_v2", and volume attach "huaweicloud_compute_volume_attach")

### Actual Behavior

Not being able to implement a code that makes sense in terraform, once I dont have an easier way to attach evs disks to a vault. 
If we use hardcoded evs disks ID does not seems so bad, but thinking about automation and terraform it's really a pain in the ass the current implementation.

**Comment by niuzhenguo** [comment]
@Lance52259 please have a look at this!

**Comment by Lance52259** [comment]
@albertocrj Thanks for the feedback, we're reviewing this R&D program.
