### ISSUE TITLE
How to assign role to Global Region?

### ISSUE THREAD

**Issue by winggundamth** [huaweicloud/terraform-provider-huaweicloud#1231]
### Terraform Version

```
Terraform v1.0.0
on linux_amd64
+ provider registry.terraform.io/huaweicloud/huaweicloud v1.24.2
```

### Terraform Configuration Files

```hcl
provider "huaweicloud" {
  region      = "ap-southeast-2"
}

data "huaweicloud_identity_role" "te_adm" {
  display_name = "Tenant Administrator"
}

# Mapping Role, Group, and Project
resource "huaweicloud_identity_role_assignment" "role_assignment_admin" {
  group_id   = huaweicloud_identity_group.group_admin.id
  role_id    = data.huaweicloud_identity_role.te_adm.id
  project_id = var.project_id
}
```

### Expected Behavior

Need to assign Tenant Administrator to Global Region

### Actual Behavior

Terraform assign Tenant Administrator to a region specific in provider

![Selection_143](https://user-images.githubusercontent.com/4833238/123075732-b2586680-d442-11eb-830d-b3090b52e602.png)

**Comment by niuzhenguo** [comment]
https://registry.terraform.io/providers/huaweicloud/huaweicloud/latest/docs/resources/identity_role_assignment#example-usage-assign-role-on-domain-level
please try this ^

**Comment by ShiChangkuo** [comment]
@winggundamth does the example works?

**Comment by ShiChangkuo** [comment]
I'm going to close this issue because there are no updates for 20 days.
If you have found a problem that seems similar to this, please open a new issue and complete the issue template so we can capture all the details necessary to investigate further.
