### ISSUE TITLE
Not being able to create policy using a Resource type list.

### ISSUE THREAD

**Issue by ongsuwannoo** [huaweicloud/terraform-provider-huaweicloud#1289]
# Not being able to create policy using a Resource type list.
Write a policy like this, but resource return must be []string only, I don't know what to do.
### Terraform Version

```
Terraform v1.0.2
on linux_amd64
+ provider registry.terraform.io/huaweicloud/huaweicloud v1.26.0
```

### Terraform Configuration Files

```hcl
resource "huaweicloud_identity_role" "assumeRole_glob_policy" {
  name        = "assumeRole-glob-policy"
  description = "created by terraform"
  type        = "AX"
  policy      = <<EOF
    {
    "Version": "1.1",
    "Statement": [
        {
            "Action": [
                "iam:agencies:assume"
            ],
            "Resource": {
                "uri": [
                    "/iam/agencies/xxx",
                    "/iam/agencies/bbb"
                ]
            },
            "Effect": "Allow"
        }
    ]
  }
EOF
}
```

### Crash Output

```
│ Error: Error unmarshalling policy, please check the format of the policy document: json: cannot unmarshal object into Go struct field Statement.Statement.Resource of type []string
│ 
│   with huaweicloud_identity_role.assumeRole_glob_policy,
│   on base.tf line 1790, in resource "huaweicloud_identity_role" "assumeRole_glob_policy":
│ 1790: resource "huaweicloud_identity_role" "assumeRole_glob_policy" {
```

### Steps to Reproduce

1. `terraform init`
2. `terraform apply`

### References

[(Optional) Assigning Permissions to an IAM User (by a Delegated Party)](https://support.huaweicloud.com/intl/en-us/usermanual-iam/iam_01_0063.html)

**Comment by ShiChangkuo** [comment]
@ongsuwannoo Thanks for raising this.

There are two custom policies in HuaweiCloud: for services and for agencies. Currently, the provider only supports custom policy for services as the JSON formats of them are different.

I will try to implement custom policy for agencies in the next release.
