### ISSUE TITLE
Error creating MRS 

### ISSUE THREAD

**Issue by nik-afa** [huaweicloud/terraform-provider-huaweicloud#1290]
Hi, i try install MRS cluster and this get error

```
huaweicloud_mrs_cluster.spark-stage: Creating...
huaweicloud_mrs_cluster.spark-stage: Still creating... [10s elapsed]
huaweicloud_mrs_cluster.spark-stage: Still creating... [20s elapsed]
huaweicloud_mrs_cluster.spark-stage: Still creating... [30s elapsed]
huaweicloud_mrs_cluster.spark-stage: Still creating... [40s elapsed]
╷
│ Error: Error waiting for cluster (bf3c27aa-f9fd-4997-8e13-58178e7c38c9) to become ready: unexpected state 'failed', wanted target 'running'. last error: %!s(<nil>)
│
│   with huaweicloud_mrs_cluster.spark-stage,
│   on spark-stage.tf line 1, in resource "huaweicloud_mrs_cluster" "spark-stage":
│    1: resource "huaweicloud_mrs_cluster" "spark-stage" {
```
in webui i see this error
```
(MRS.201) Failed due to an ECS error. Try again later or contact customer service.
Cluster ID: bf3c27aa-f9fd-4997-8e13-58178e7c38c9.
( Ecs.0005: root volume size is [40], must over image mindisk [480])
```

### Terraform Version
```
Terraform v0.15.1
on darwin_amd64
+ provider registry.terraform.io/huaweicloud/huaweicloud v1.26.0
```

### Terraform Configuration Files

```hcl
resource "huaweicloud_mrs_cluster" "spark-stage" {
  cluster_name  = "spark-stage"
  cluster_version = "MRS 3.0.5"
  cluster_type = 0
  region = local.region
  available_zone_id = var.zone
  billing_type = 12
  master_node_num = 2
  core_node_num = 3
  master_node_size = "c6.4xlarge.2.linux.bigdata"
  core_node_size = "c6.4xlarge.2.linux.bigdata"
  volume_type = "SAS"
  volume_size = 600
  safe_mode = 0
  cluster_admin_secret = var.pass
  node_password = var.pass
  vpc_id = var.vpc_id
  subnet_id = var.subnet_id
  log_collection = 1

  component_list {
    component_name = "Hadoop"
  }
  component_list {
    component_name = "Spark2x"
  }
  component_list {
    component_name = "Hive"
  }
}
```

### Affected Resource(s)
```
huaweicloud_mrs_cluster
```

### Expected Behavior
MRS default root volume size - 480Gb or must be use specified options

### Actual Behavior
terraform apply failed

### Steps to Reproduce

1. `terraform init`
2. `terraform apply`

**Comment by ShiChangkuo** [comment]
@nik-afa Thanks for raising this. can you try to create a MRS 1.9.2 cluster?

**Comment by nik-afa** [comment]
thanks, I was able to install the 2.1.0 version of the cluster, but how can I install 3.0.5?

**Comment by ShiChangkuo** [comment]
Currently, only MRS 1.8.10, MRS 1.9.2 and MRS 2.1.0 are supported by this provider.

Since the API in cloud side has been updated, we will implement a new resource `huaweicloud_mapreduce_cluster` and release it before 15th Aug.

**Comment by nik-afa** [comment]
thank you to response, waiting for release

**Comment by Lance52259** [comment]
For MRS v2, please refer to #1324

**Comment by Lance52259** [comment]
@nik-afa  The `huaweicloud_mapreduce_cluster` resource has been supported,  please refer to the v1.27.0 release.

**Comment by nik-afa** [comment]
Hi, thanks, i tried 
`    huaweicloud = {
      source  = "huaweicloud/huaweicloud"
      version = "1.27.0"
    }`

but still an error
`(MRS.201) Failed due to an ECS error. Try again later or contact customer service.
Cluster ID: eff2078d-89d1-4f69-88bd-77e2e15fd606.
( Ecs.0005: root volume size is [40], must over image mindisk [480])`

how to specify root volume?
