### ISSUE TITLE
Can't create ECS using Key Pair instead of password

### ISSUE THREAD

**Issue by Altron01** [huaweicloud/terraform-provider-huaweicloud#1293]
### Terraform Version

```
Terraform v0.12.24
```

### Terraform Configuration Files

```hcl
data "huaweicloud_kms_key" "ecs_key" {
  key_alias = "KeyPair-meetup"
}

resource "huaweicloud_compute_instance" "basic" {
  name              = "ecs_test"
  image_id          = data.huaweicloud_images_image.centos_img.id
  flavor_id         = data.huaweicloud_compute_flavors.ecs_flavor.ids[0]
  key_name          = data.huaweicloud_kms_key.ecs_key.key_alias
  security_groups   = ["sg-qa-public-ecs"]
  availability_zone = data.huaweicloud_availability_zones.azs.names[0]

  network {
    uuid    = data.huaweicloud_vpc_subnet.subnet_qa_public_ecs.id
    fixed_ip_v4 = "192.168.0.70"
  }
}
```

### Crash Output

Unsupported argument on base_template.tf line 47, in resource "huaweicloud_compute_instance" "basic":
key_name          = data.huaweicloud_kms_key.ecs_key.key_alias

An argument named "key_name" is not expected here.

### Expected Behavior

Resource huaweicloud_compute_instance should be created using key pair from DEW as authentication instead of password.

### Actual Behavior

attribute key_name is not accepted, even though it is part of the huaweicloud_compute_instance acceptable parameters

### Steps to Reproduce

1. `terraform init`
2. `terraform apply`

**Comment by ShiChangkuo** [comment]
@Altron01 you should use **key_pair** instead of key_name.
https://registry.terraform.io/providers/huaweicloud/huaweicloud/latest/docs/resources/compute_instance#argument-reference

**Comment by Altron01** [comment]
Worked perfectly using key_pair, thank you :)
