### ISSUE TITLE
The mrs topic cannot be created by specified enterprise project 

### ISSUE THREAD

**Issue by jiege3324** [huaweicloud/terraform-provider-huaweicloud#1306]
huaweicloud/huaweicloud: version = "~> 1.26.0"

The instances created by mrs with terraform are all default enterprise projects

**Comment by Lance52259** [comment]
we will implement a new resource huaweicloud_mapreduce_cluster and release it before 15th Aug.

**Comment by Lance52259** [comment]
@jiege3324 The `enterprise_project_id` has been supported by `huaweicloud_mapreduce_cluster`, the document please refer to the release v1.27.0.
