### ISSUE TITLE
create network acl issue

### ISSUE THREAD

**Issue by jiege3324** [huaweicloud/terraform-provider-huaweicloud#1335]
I have to create many rules at the same time, and I reported this error. I can only create 10 rules at most when I reported a rule.

Error: Too many requests: [POST https://vpc.cn-north-4.myhuaweicloud.com/v2.0/fwaas/firewall_policies], error message: {"error_msg":"The throttling threshold has been reached: policy user over ratelimit,limit:200,time:5 minute","error_code":"APIGW.0308","request_id":"d4e8174b8df00840aef0c6907ec0e384"}

limit:200 can open a little more, for example, 500

**Comment by ShiChangkuo** [comment]
@jiege3324 the provider has canceled the maxItems limitation via #1315 after v1.27.0+
The new issue is caused by cloud side. can you open a ticket in HuaweiCloud ?

BTW, you can provide the log to help us get more details, thanks.
