### ISSUE TITLE
Wrong IAM URL in provider configuration

### ISSUE THREAD

**Issue by alexandrovas** [huaweicloud/terraform-provider-huaweicloud#1341]
Hello!
I got wrong IAM URL when only `cloud` parameter is defined in provider condifguration.

### Terraform Version
```
terraform version
Terraform v1.0.3
on darwin_amd64
+ provider registry.terraform.io/huaweicloud/huaweicloud v1.27.0
```

### Terraform Configuration Files

Provider configuration:

```hcl
provider "huaweicloud" {
  cloud        = "hc.sbercloud.ru"
  domain_name  = "[censored]"
  region       = "ru-moscow-1"
  project_name = "[censored]"
  access_key   = var.hw_access_key
  secret_key   = var.hw_secret_key
}
```

### Debug Output

On applying configuration I got this error:
```
Error: user: Get "https://iam.hc.sbercloud.ru/v3.0/OS-USER/users/[censored_id]": dial tcp: lookup iam.hc.sbercloud.ru on [censored_dns_address]:53: no such host
```

Right IAM URL in my case: https://iam.ru-moscow-1.hc.sbercloud.ru

### Expected Behavior

IAM URL should be right calculated from `cloud` parameter in provider configuration.

### Actual Behavior

Calculated IAM URL is wrong.

This configuration is working correctly:

```hcl
provider "huaweicloud" {
  auth_url     = "https://iam.ru-moscow-1.hc.sbercloud.ru"
  cloud        = "hc.sbercloud.ru"
  domain_name  = "[censored]"
  region       = "ru-moscow-1"
  project_name = "[censored]"
  access_key   = var.hw_access_key
  secret_key   = var.hw_secret_key
  endpoints = {
    iam = "iam.ru-moscow-1.hc.sbercloud.ru"
  }
}
```

### Steps to Reproduce

1. Define provider with configuration as above
2. Define some resource in IAM (for example, `huaweicloud_identity_user`)
3. Run `terraform apply`

**Comment by chengxiangdong** [comment]
Hi, alexandrovas,
Change the value of `auth_url` to `"https://iam.ru-moscow-1.hc.sbercloud.ru/v3"`, try again pls

**Comment by alexandrovas** [comment]
@chengxiangdong 
Thanks you, but result is the same :(

Config:
```
provider "huaweicloud" {
  auth_url     = "https://iam.ru-moscow-1.hc.sbercloud.ru/v3"
  cloud        = "hc.sbercloud.ru"
  domain_name  = "[censored]"
  region       = "ru-moscow-1"
  project_name = "[censored]"
  access_key   = var.hw_access_key
  secret_key   = var.hw_secret_key
}
```

**Comment by chengxiangdong** [comment]
Hi, alexandrovas,
After analysis, the URL path composition of the IAM service of Huawei Cloud and SberCloud is different.
It can be calculated in the Huawei Cloud provider, but it not works in SberCloud. And the SberCloud does not provide a new calculation rule, so we need to provide the IAM URL in the Config.

**Comment by alexandrovas** [comment]
@chengxiangdong 
Ok, I get it. But why IAM URL should be defined in two places (in `auth_url` field and `endpoints` block)?

**Comment by chengxiangdong** [comment]
@alexandrovas 
`auth_url` is optional, it can be calculated based on `cloud` and `region`, it is not necessary to define it.
The `iam` in the endpoint is only used for IAM resources, the others do not need to set it.

**Comment by alexandrovas** [comment]
@chengxiangdong Ok, thank you!
