### ISSUE TITLE
Can terraform create dcs to set cluster mode?

### ISSUE THREAD

**Issue by jiege3324** [huaweicloud/terraform-provider-huaweicloud#1369]
Only see Single and HA mode

**Comment by ShiChangkuo** [comment]
@jiege3324 you can create DCS instances with various cache modes  by configing the **product_id** argument.

```
product_id - (Required, String, ForceNew) Specifies the product ID with various cache modes: single, ha, cluster, proxy and ha_rw_split. 
```

The product_id format is **spec_code** + "-h", indicates that the charging mode is pay-per-use. 
You can uuery the specifications in [DCS Instance Specifications](https://support.huaweicloud.com/intl/en-us/productdesc-dcs/dcs-pd-200713003.html)

**Comment by jiege3324** [comment]
no ,corrected the error according to your instructions.
Error: Error creating HuaweiCloud instance: Bad request with: [POST https://dcs.cn-north-4.myhuaweicloud.com/v1.0/0a5fff52d000257a2fd0c0090f6e9f4c/instances], error message: {"error":{"code":"DCS.4927","message":"The param spec_code is invalid","ext_message":null}}

  on dcs-output.tf line 14, in resource "huaweicloud_dcs_instance" "dcs_instance_0":
  14: resource "huaweicloud_dcs_instance" "dcs_instance_0" {

terraform tf
data "huaweicloud_dcs_az" "dcs_az_0" {
  code = "cn-north-4a"
}

data "huaweicloud_vpc" "dcs_vpc0" {
  name = "vpc-rtm-corebe-prelive"
}

data "huaweicloud_vpc_subnet" "dcs_subnet0" {
  vpc_id = data.huaweicloud_vpc.dcs_vpc0.id
  name = "sbn-rtm-crb-db-prelive"
}

resource "huaweicloud_dcs_instance" "dcs_instance_0" {
  name              = "dcs-rtm-db-crb-prelive-01"
  engine            = "Redis"
  engine_version    = "5.0"
  password          = "Test#2021"
  capacity          = 8
  vpc_id            = data.huaweicloud_vpc.dcs_vpc0.id
  subnet_id         = data.huaweicloud_vpc_subnet.dcs_subnet0.id
  available_zones   = [data.huaweicloud_dcs_az.dcs_az_0.id]
  product_id        = "redis.cluster.xu1.large.8-h"
  backup_policy {
    save_days   = 1
    backup_type = "manual"
    begin_at    = "00:00-01:00"
    period_type = "weekly"
    backup_at   = [1, 2, 4, 6]
  }
}

**Comment by ShiChangkuo** [comment]
please access to the Chinese version: https://support.huaweicloud.com/productdesc-dcs/dcs-pd-0522002.html
the `product_id` should be "redis.cluster.xu1.large.r2.8-h"

sorry for the wrong document in HuaweiCloud help center.

**Comment by jiege3324** [comment]
yes
