### ISSUE TITLE
Importing VPC error occur `Terraform detected a resource with this ID doesn't exist`

### ISSUE THREAD

**Issue by eric4545** [huaweicloud/terraform-provider-huaweicloud#138]
Hi there,

I was trying to importing huaweicloud vpc into terraform, but got error `Terraform detected a resource with this ID doesn't exist. Please verify the ID is correct`

### Terraform Version
```
Terraform v0.11.14
+ provider.huaweicloud v1.5.0

Your version of Terraform is out of date! The latest version
is 0.12.1. You can update by downloading from www.terraform.io/downloads.html
```

### Affected Resource(s)
- huaweicloud_vpc_v1

### Terraform Configuration Files
```hcl
resource "huaweicloud_vpc_v1" "main" {
  name   = "cn-south-vpc"
  region = "cn-south-1"
  cidr   = "10.16.0.0/16"
}
```

### Expected Behavior
It should import resource successfully 

### Actual Behavior
Import resource failed error occurred.

```
Error: huaweicloud_vpc_v1.main (import id: 580b347e-122c-4634-a6c7-164fb0fbc34f): 1 error occurred:
        * import huaweicloud_vpc_v1.main result: 580b347e-122c-4634-a6c7-164fb0fbc34f: import huaweicloud_vpc_v1.main (id: 580b347e-122c-4634-a6c7-164fb0fbc34f): Terraform detected a resource with this ID doesn't
exist. Please verify the ID is correct. You cannot import non-existent
resources using Terraform import.
```

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform import huaweicloud_vpc_v1.main 580b347e-122c-4634-a6c7-164fb0fbc34f`

**Comment by niuzhenguo** [comment]
@eric4545 Seems you used a non existing VPC id for importing.

**Comment by niuzhenguo** [comment]
Closing this, please feel free to reopen it if there are still problems.
