### ISSUE TITLE
Bug on huaweicloud_compute_servergroup

### ISSUE THREAD

**Issue by marciobarbato** [huaweicloud/terraform-provider-huaweicloud#1380]
Hello, 
I'm using huaweicloud_compute_servergroup for keeping instances on different hosts, I notice that if I attached the instance and after that delete the instance, it will not remove instance from server group, therefore the next run will fail because it will try to remove an unexisting instance from the server group.

terraform version is 1.0.4

**How to reproduce**:
-**Create an instance with**:
resource "huaweicloud_compute_instance" "ciscoinstance1" {
  name                  = "instancename"
  image_id              = data.huaweicloud_images_image.imagecisco.id
  flavor_id             = var.ciscos_flavorid
  security_group_ids    = [data.huaweicloud_networking_secgroup.secgroup_cisco.id]
  availability_zone     = data.huaweicloud_availability_zones.avazones.names[1]
  enterprise_project_id = var.enterprise_project_id

  network {
    uuid                = data.huaweicloud_vpc_subnet.extsubnet.id
    fixed_ip_v4         = var.cisco1_ext_ip
  }

  network {
    uuid                = data.huaweicloud_vpc_subnet.csrsubnet.id
    fixed_ip_v4         = var.cisco1_csr_ip
  }

}
-**attach it to a server group**

resource "huaweicloud_compute_servergroup" "cisco-sg" {
  name     = var.aag_name_cisco
  policies = ["anti-affinity"]
  members  = [
      huaweicloud_compute_instance.ciscoinstance1.id,
      huaweicloud_compute_instance.ciscoinstance2.id,
  ]
}

-**triggers instance recreation by change it's networking setting**.

**Comment by ShiChangkuo** [comment]
@marciobarbato thanks for raising this. I will try to ignore the error when refreshing the server group.
