### ISSUE TITLE
huaweicloud_compute_instance destroy error

### ISSUE THREAD

**Issue by Hydrogenhax** [huaweicloud/terraform-provider-huaweicloud#1397]
Hi there, I'm wondering if anyone is facing similar error destroying ecs instances.
Terraform version is 1.0.4 and config consists simply of 1 huaweicloud_compute_instance.
Following error can be seen when destroying and fails, but a second time would succeed.
```
huaweicloud_compute_instance.instance: Destroying... [id=1129a48b-aba8-4ade-99f7-e19c34ebd681]
huaweicloud_compute_instance.instance: Still destroying... [id=1129a48b-aba8-4ade-99f7-e19c34ebd681, 10s elapsed]
huaweicloud_compute_instance.instance: Still destroying... [id=1129a48b-aba8-4ade-99f7-e19c34ebd681, 20s elapsed]
huaweicloud_compute_instance.instance: Still destroying... [id=1129a48b-aba8-4ade-99f7-e19c34ebd681, 30s elapsed]

│ Error: json: cannot unmarshal array into Go struct field SubJob.entities.sub_jobs.entities of type string
│ 
│ 
```

**Comment by ShiChangkuo** [comment]
@Hydrogenhax we need more details about this issue:
- the HuaweiCloud provider version
- the config of `huaweicloud_compute_instance`
- the region
- the [debug log](https://www.terraform.io/docs/extend/debugging.html#turning-on-logging)

**Comment by Hydrogenhax** [comment]
Hi there, thanks for looking into this.

HuaweiCloud provider version = 1.27.1
Region = ap-southeast-1 (hongkong)

main.tf
```
terraform {
  required_providers {
    huaweicloud = {
      source  = "huaweicloud/huaweicloud"
      version = "1.27.1"
    }
  }
}

provider "huaweicloud" {
  region = "ap-southeast-1"
}

data "huaweicloud_vpc_subnet" "default_subnet" {
  name = "subnet-default"
}

resource "huaweicloud_compute_instance" "instance" {
  name              = "test-instance-1"
  image_id          = "67159f00-89c1-44eb-b810-c90478376cb4" #ubuntu_20_04_lts
  key_pair          = "scripts"
  flavor_id         = "c3.large.2"
  security_groups   = ["default"]
  availability_zone = "ap-southeast-1a"

  network {
    uuid = data.huaweicloud_vpc_subnet.default_subnet.id
  }
}
```

[tfdebug.log](https://github.com/huaweicloud/terraform-provider-huaweicloud/files/7030091/tfdebug.log)

**Comment by ShiChangkuo** [comment]
@Hydrogenhax the API response is changed, we should update it in the SDK and fix it soon.

**Comment by ShiChangkuo** [comment]
the golangsdk is updated since v1.27.2, so close it.
