### ISSUE TITLE
Terraform Provider Development Program - Initial Review

### ISSUE THREAD

**Issue by bill-rich** [huaweicloud/terraform-provider-huaweicloud#14]
Hello!

Its Bill @ HashiCorp again!

The huaweicloud provider is looking very good! I've built off the reviews for the previous two cloud and added a few additional items. The review was done on the git commit 06ef183c.

- [ ] Data sources missing for several resources.
- [x] There are many sections of code that have been commented out. If they are not needed, it would be best to remove them to keep things clean. Here are a few examples.
 - MaxRetries, S3ForcePathStyle, “fmt.Printf("[DEBUG] Region: %s.\n", c.Region)
 in config.go
 - Block in resource_huaweicloud_elb_loadbalancer.go
 - Commented log lines in data_source_huaweicloud_rds_flavors_v1.go
 - Block comment in huaweicloud/resource_huaweicloud_compute_floatingip_associate_v2_test.go
 - Type comments in resource_huawei_dns_recordset_v2_test.go
 - Assorted lines in resource_huawei_dns_zone_v2.go & resource_huawei_dns_zone_v2_test.go
- [x] References to OpenTelekomCloud in:
  - huaweicloud/resource_huaweicloud_dns_recordset_v2.go
  - huaweicloud/resource_huaweicloud_dns_zone_v2.go
  - huaweicloud/types.go
- [x] CHANGELOG.md needs to be filled in.
- [x] Create a resuable validate function for use in resource_huaweicloud_elb_healthcheck.go since very similar functions are being used repeatedly.
- [x] AWS variable naming in config.go seem to be for swift provider, but may be good to revisit naming to not reference AWS
- [x] Similar issue with naming. Functions testAccAWSS3MultiBucketConfigWithTags & TestAccAWSS3MultiBucket_withTags should have AWS removed.
- [x] Remove comments for test results.
- [x] Standard libraries should be grouped in imports. Used goimports and found issues in:
  - data_source_huaweicloud_kms_data_key_v1.go
  - import_huaweicloud_s3_bucket.go
  - resource_huaweicloud_compute_floatingip_v2.go
  - resource_huaweicloud_elb_backend_test.go
  - resource_huaweicloud_elb_healthcheck_test.go
  - resource_huaweicloud_kms_key_v1.go
  - resource_huaweicloud_rds_instance_v1.go
  - resource_huaweicloud_rds_instance_v1_test.go
  - resource_huaweicloud_s3_bucket_test.go
- [x] ForceNew is not needed in data sources since the data is refreshed on each planning anyway.

**Comment by niuzhenguo** [comment]
@bill-rich Thanks for the review, Will address them soon!  btw, CHANGELOG already updated with 0dc3434d

**Comment by niuzhenguo** [comment]
@bill-rich Regarding "Data sources missing for several resources", we currently only support data sources which are really required by customers like the previous two cloud, and that would be enriched later on. Besides that, all issues have been addressed, please have a look again when you got time, thanks in advance.

**Comment by bill-rich** [comment]
@niuzhenguo Looks great! Thanks for getting those items addressed! That makes total sense on the data sources. Just wanted to make sure it was purposeful.

**Comment by niuzhenguo** [comment]
@bill-rich Thank you very much! will close this and follow up with Chris on slack.
