### ISSUE TITLE
[DCS] Add support for dcs instance capacity changing

### ISSUE THREAD

**Issue by kolsean** [huaweicloud/terraform-provider-huaweicloud#1457]
It would be great to add the ability to change capacity size for `huaweicloud_dcs_instance` resource.
Now the argument in the provider schema has `ForceNew` property, but there is an appropriate `resize` method in the API for this field.

**Comment by chengxiangdong** [comment]
Dear @kolsean, 
I see that there is already an API to support resize capacity size, and we will support it in the next version.
