### ISSUE TITLE
Security group rule creation error when already exists

### ISSUE THREAD

**Issue by Hydrogenhax** [huaweicloud/terraform-provider-huaweicloud#1465]
Hello, I was trying to create a security group rule specified in the resources that was already existing, and saw the error below.
```
Error: Expected HTTP response code [201 202] when accessing [POST https://vpc.ap-southeast-1.myhuaweicloud.com/v2.0/security-group-rules], but got 409 instead
{"NeutronError": {"message": "Security group rule already exists. Rule id is eede3c2d-434d-481e-a252-4e8a0d9facd8.", "detail": "", "type": "SecurityGroupRuleExists"}}
```
Not sure if this would be considered a bug or an enhancement request but other providers are usually able to detect and automatically store the existing one into the state. 
Import will solve the issue but is more manual and when terraform is used as part of automation with credentials all hidden this will be difficult. Removing the security rule for terraform to create it will cause downtime as users would not be able to access the instances from the specified port.

**Comment by ShiChangkuo** [comment]
@Hydrogenhax For most resources in huaweicloud provider, an error will be raised if it already exists.

can you set [delete_default_rules](https://registry.terraform.io/providers/huaweicloud/huaweicloud/latest/docs/resources/networking_secgroup#delete_default_rules) = ture in huaweicloud_networking_secgroup?

**Comment by ShiChangkuo** [comment]
I will close it temporarily, If you have any questions, please reopen it. Thanks.
