### ISSUE TITLE
[CCE] Add the ability to create PVC

### ISSUE THREAD

**Issue by alexandrovas** [huaweicloud/terraform-provider-huaweicloud#1470]
Hello!

I see that there is resource `huaweicloud_cci_pvc`, but I don't understand how to create PVC for CCE cluster via this resource.
If this resource is intended for other tasks, then it makes sense to create a separate resource for PVC.

I see that the necessary APIs exist: https://support.huaweicloud.com/intl/en-us/api-cce/cce_02_0252.html

**Comment by niuzhenguo** [comment]
@alexandrovas Seems we only have create/delete API support while terraform resource needs GET api as well.

**Comment by niuzhenguo** [comment]
we will try to implement this with K8S API.  #1541

**Comment by Lance52259** [comment]
Refer: #1552
