### ISSUE TITLE
How to configure security group rules for mrs

### ISSUE THREAD

**Issue by jiege3324** [huaweicloud/terraform-provider-huaweicloud#1478]
https://registry.terraform.io/providers/huaweicloud/huaweicloud/latest/docs/resources/mapreduce_cluster

I want to configure the security group to allow port 22 through terraform, and other vm can connect via ssh

**Comment by Lance52259** [comment]
you need to create a security group resource and open ingress rule for port 22.

**Comment by jiege3324** [comment]
Yes, I just want to create mrs in terraform at the same time, his security group can customize the opening port

**Comment by Lance52259** [comment]
for `huaweicloud_mapreduce_cluster`, it provide a `security_group_ids` param.

**Comment by jiege3324** [comment]
security_group_ids - (Optional, List, ForceNew) Specifies an array of one or more security group ID to attach to the MapReduce cluster. If using the specified security group, the group need to open the specified port (9022) rules.

I saw this configuration, but I didn’t clearly describe how to implement it.

**Comment by Lance52259** [comment]
security_group_ids = [huaweicloud_networking_secgroup.test1.id, huaweicloud_networking_secgroup.test2.id]

**Comment by jiege3324** [comment]
It means that I can build a security group by myself and bind it here. The format is like this, right?

**Comment by Lance52259** [comment]
sure

**Comment by jiege3324** [comment]
By the way, can mrs 1.9.2 enable ssl.mode.enable in terraform? I want to use ssl to access it. Or can I use terraform to create mrs2.1.0 version?

**Comment by Lance52259** [comment]
I am not sure about this, service tricket can help you.

**Comment by jiege3324** [comment]
I see terraform's instructions can only create version 1.9.2 and 3.1, and there is no explanation when ssl is turned on. Can you please help me? Is there any relevant solution for this one?

**Comment by Lance52259** [comment]
I need to consult related services and I will reply to you later.

**Comment by jiege3324** [comment]
tks

**Comment by Lance52259** [comment]
1. mrs2.1.0 has been offline, the mrs cluster currently supports 1.9.2 and 3.1.
2. did you mean `safe_mode`? I can't find SSL in MapReduce cluster.

**Comment by jiege3324** [comment]
It’s not safe_mode, but ssl authentication. For example, if you don’t enable Kerberos, the ports are 9092 and 9093. If ssl is enabled, it’s 9093 access.

**Comment by Lance52259** [comment]
https://support.huaweicloud.com/en-us/cmpntguide-mrs/mrs_01_1569.html

**Comment by jiege3324** [comment]
Can this ssl be enabled in terraform?

**Comment by Lance52259** [comment]
I think if you enable Kerberos (set `safe_mode` with true), the default value of SSL is true.

**Comment by jiege3324** [comment]
resource "huaweicloud_mapreduce_cluster" "mrs_cluster0" {
  availability_zone  = data.huaweicloud_availability_zones.mrs_az0.names[0]
  name               = "mrs-rtm-db-crb-prelive-01"
  type               = "STREAMING"
  version            = "MRS 1.9.2"
  manager_admin_pass = "Password"
  node_admin_pass    = "Password"
  vpc_id             = data.huaweicloud_vpc.mrs_vpc0.id
  subnet_id          = data.huaweicloud_vpc_subnet.mrs_subnet0.id
  component_list     = ["Storm", "Kafka"]
  safe_mode          = "false"

When I configure flase in safe-mode, the port is 9092. If I configure true in safe-mode, the port is 21009. What I need now is to enable ssl

**Comment by Lance52259** [comment]
`huaweicloud_mapreduce_cluster` does not support enabling kafka SSL with manager, you can submit a ticket to consult MRS service personnel for the API interface support of this function.

**Comment by jiege3324** [comment]
![图片](https://user-images.githubusercontent.com/26430038/132308162-a0b8b438-d08e-4609-bfa0-223737c463b8.png)

If it is a self-built security group, do these 9022 rules also need to be added?

**Comment by Lance52259** [comment]
These ingress rules will be added automatically if `security_group_ids` is omitempty.

**Comment by jiege3324** [comment]
If it is a self-built security group, then I only need to open a few ports that I need to access, and I don’t care about the others, right?

**Comment by Lance52259** [comment]
No! no! no! The automatic addition of 9022 ingress rules only takes effect when `security_group_ids` is omitempty! If you want to specify some custom rules, these 9022 ports need to be set by yourself (Manually created security groups will not automatically add 9022 port rules).

**Comment by Lance52259** [comment]
If you have any questions, please submit a ticket to contact us. @jiege3324
