### ISSUE TITLE
Query a list of DCS flavors

### ISSUE THREAD

**Issue by chengxiangdong** [huaweicloud/terraform-provider-huaweicloud#1496]
I’d like to query a list of available DCS flavors.
data source: huaweicloud_dcs_flavors

**Comment by ShiChangkuo** [comment]
@chengxiangdong how can I use this data source?

**Comment by chengxiangdong** [comment]
> @chengxiangdong how can I use this data source?

data source name: huaweicloud_dcs_flavors
