### ISSUE TITLE
Cannot attach a listener to load balancer

### ISSUE THREAD

**Issue by marciobarbato** [huaweicloud/terraform-provider-huaweicloud#1544]
### Terraform Version

```
1.0.7
```

### Terraform Configuration Files

```hcl
resource "huaweicloud_lb_loadbalancer" "lb_ascs_00" {
  name                  = var.ascs_lb00_name
  vip_subnet_id         = var.lb00_subnet_id
  enterprise_project_id = var.enterprise_project_id
  tags                  = var.tags
}

resource "huaweicloud_lb_listener" "lb_ascs_00_listener1" {
  protocol        = "TCP"
  protocol_port   = 3200
  loadbalancer_id = huaweicloud_lb_loadbalancer.lb_ascs_00.id
  tags            = var.tags
}
```

### Crash Output

│ Error: Error: loadbalancer 451e61ad-6592-4ff9-a4ce-4968b8bf4efa not found: Resource not found: [GET https://elb.cn-north-4.myhuaweicloud.com/v2.0/lbaas/loadbalancers/451e61ad-6592-4ff9-a4ce-4968b8bf4efa], error message: {"NeutronError": {"type": "HTTPNotFound", "message": "The resource could not be found.", "detail": ""}}
│ 
│   with huaweicloud_lb_listener.lb_ascs_00_listener1,
│   on ascs-lb.tf line 8, in resource "huaweicloud_lb_listener" "lb_ascs_00_listener1":
│    8: resource "huaweicloud_lb_listener" "lb_ascs_00_listener1" {

### Expected Behavior
the listener should have been created
### Actual Behavior
listener cannot be created because it cannot find load balancer

### Steps to Reproduce
create a load balancer and try to attach a listener to it

### Additional Context
using latest 1.28 provider

**Comment by ShiChangkuo** [comment]
@marciobarbato Have you checked whether the load balancer 451e61ad-6592-4ff9-a4ce-4968b8bf4efa exists on console?

**Comment by marciobarbato** [comment]
@ShiChangkuo  Yes.
It does get created and still exists in the portal.
![Screenshot from 2021-09-23 08-12-34](https://user-images.githubusercontent.com/13167360/134467722-9c7f2f63-ca68-45e4-b202-4c558ea8fef0.png)

**Comment by ShiChangkuo** [comment]
Kindly fill in the below information so we can start our investigation.

* Did you try to run `terraform apply` again?
* What's the Huaweicloud provider version? Suggest to use the latest version
* If the issue still exists, please provide the debug log with **TF_LOG** and **TF_LOG_PATH** environment variables.

**Comment by marciobarbato** [comment]
Did you try to run terraform apply again?
yes
    What's the Huaweicloud provider version? Suggest to use the latest version
    huaweicloud = {
      source  = "huaweicloud/huaweicloud"
      version = "~> 1.28.0"
    }
    If the issue still exists, please provide the debug log with TF_LOG and TF_LOG_PATH environment variables.
sent it by email and ticket in huawei system

**Comment by ShiChangkuo** [comment]
@marciobarbato Currently, the provider invokes the version 2.0 APIs of ELB service, which requires the IAM user has the permission of ELB administrator.

We will upgrade the APIs as soon as possible, but it will take some time (about 1~2 months).
As a workaround, you can assign  the **ELB Administrator** role to the user group. please refer to the [user guide](https://support.huaweicloud.com/intl/en-us/usermanual-iam/iam_03_0001.html#section2).

**Comment by ShiChangkuo** [comment]
@marciobarbato please try to use [huaweicloud_elb_listener](https://registry.terraform.io/providers/huaweicloud/huaweicloud/latest/docs/resources/elb_listener) which invokes v3 APIs to create an ELB listener.
Looking forward to your update.

**Comment by ShiChangkuo** [comment]
@marciobarbato I'm going to close this issue because it has been blocked for a long time.
If you have found a problem that seems similar to this, please open a new issue and complete the issue template so we can capture all the details necessary to investigate further.
