### ISSUE TITLE
Error creating HuaweiCloud compute client: Discovered 2 matching endpoints while following the ECS example from the documentation

### ISSUE THREAD

**Issue by vtno** [huaweicloud/terraform-provider-huaweicloud#158]
I'm trying to spin up an ECS instance via this TF provider but cannot successfully do so. 

### Terraform Version
0.12.3

### Provider Version
1.6.0

### Affected Resource(s)
Please list the resources as a list, for example:
- huaweicloud_compute_instance_v2 

### Terraform Configuration Files
```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
variable "region" {
  type = string
}

variable "access_key" {
  type = string
}

variable "secret_key" {
  type = string
}

# Configure the HuaweiCloud Provider
provider "huaweicloud" {
  access_key = "${var.access_key}"
  secret_key  = "${var.secret_key}"
  region      = "${var.region}"
  auth_url    = "https://iam.ap-southeast-2.myhuaweicloud.com/v3"
}

resource "huaweicloud_compute_instance_v2" "instance_1" {
  name              = "basic"
  security_groups   = ["default"]
  availability_zone = "az1"
  flavor_name       = "s3.small.1"
  region            = "${var.region}"
}
```

```hcl
access_key = "xxxx"
secret_key  = "xxxx"
region      = "ap-southeast-2"
```

### Expected Behavior
TF successfully apply the plan and create a huawei ecs instance.

### Actual Behavior
```
Error: Error creating HuaweiCloud compute client: Discovered 2 matching endpoints: []tokens.Endpoint{tokens.Endpoint{ID:"d7d418e459334210a969d25a7059aaa9", Region:"ap-southeast-2", Interface:"public", URL:"https://ecs.ap-southeast-2.myhuaweicloud.com/v2.1/"}, tokens.Endpoint{ID:"394f94c0457c428a91c964dd08fa514d", Region:"ap-southeast-2", Interface:"public", URL:"https://ecs.ap-southeast-2.myhuaweicloud.com/v2/"}}
```

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform plan -out plan -var-file variables.tfvars`
2. `terraform apply plan`

Is there any way I could specify the endpoint via my `main.tf` file? I couldn't find it anywhere in the documentation https://www.terraform.io/docs/providers/huaweicloud/index.html

**Comment by niuzhenguo** [comment]
@vtno Seems the endpoints are not correctly registered on Cloud side for region ap-sourceeast-2, can you please try ap-southeast-1, and also please configure the `tenant_name` with the provider.
```
provider "huaweicloud" {
  access_key = "${var.access_key}"
  secret_key  = "${var.secret_key}"
  region      = "ap-southeast-1"
  tenant_name = "ap-southeast-1"
  auth_url    = "https://iam.ap-southeast-1.myhuaweicloud.com/v3"
}
```

**Comment by vtno** [comment]
@niuzhenguo Got it. I will raise this to cloud support then. My specific requirement is to use ap-southeast-2 because it's the only Bangkok server available.
