### ISSUE TITLE
labels deletes after scaling 

### ISSUE THREAD

**Issue by nik-afa** [huaweicloud/terraform-provider-huaweicloud#1620]
Im used few labels in node pool, and observed then after scaling my labels is deleted, as a result tf writing destroy 
### Terraform Version
```
Terraform v0.15.1
on darwin_amd64
+ provider registry.terraform.io/gavinbunney/kubectl v1.13.0
+ provider registry.terraform.io/hashicorp/helm v2.2.0
+ provider registry.terraform.io/hashicorp/kubernetes v2.3.2
+ provider registry.terraform.io/huaweicloud/huaweicloud v1.29.2
```

### Terraform Configuration Files
```hcl
resource "huaweicloud_cce_node_pool" "cce_node_pool_dev" {
  cluster_id = huaweicloud_cce_cluster.dev.id
  name       = "worker-node-pool"
  region     = local.region
  subnet_id  = data.terraform_remote_state.vpc.outputs.subnet_id
  type       = "vm"
  os         = "EulerOS 2.5"
  flavor_id                = "m6.2xlarge.8"
  key_pair                 = huaweicloud_compute_keypair.cce.name
  priority                 = 1
  scall_enable             = true
  initial_node_count       = 3
  min_node_count           = 3
  max_node_count           = 50
  scale_down_cooldown_time = 5
  labels = {
     "environment"                    = "dev"
     "node-role.kubernetes.io/worker" = "worker"
  }
  root_volume {
    size       = 40
    volumetype = "SAS"
  }
  data_volumes {
    size       = 100
    volumetype = "SAS"
  }
}
```

### Steps to Reproduce
1. change parameters:
initial_node_count
min_node_count
2. `terraform apply`

**Comment by Lance52259** [comment]
Thanks for your feedback, we are reviewing and analyzing the reasons about this issue.

**Comment by Jason-Zhang9309** [comment]
I tried to produce the problem. But I didn't meet any problem.
My labels still exits after updating TF script and scalling.
Can you provide more information about this problem?

**Comment by nik-afa** [comment]
sorry, i was wrong, my provider version is old
`huaweicloud = {
      source  = "huaweicloud/huaweicloud"
      version = "1.22.1"
    }`

I update this and will check

**Comment by ShiChangkuo** [comment]
@nik-afa I'm going to close this issue because it has been blocked for a long time.
If you have found a problem that seems similar to this, please open a new issue and complete the issue template so we can capture all the details necessary to investigate further.
