### ISSUE TITLE
Huawei cloud support 

### ISSUE THREAD

**Issue by Pavan976** [huaweicloud/terraform-provider-huaweicloud#1642]
Hello Team,

We are trying to provision below resources using terraform in Huawei cloud and we didn't find the Huawei providers for the same .  could you please help us how we can proceed? 

- How can we enable enterprise project function ?
- Can we add orgs and sub-orgs and  enterprise projects ?
- How can we add member account under the enterprise project ?

Terraform version: 1.0.7
Cloud-provider/provisioner: Huawei Cloud

Cheers,
Pavan

**Comment by Lance52259** [comment]
Q: `How can we enable enterprise project function ?`
A: Terraform only supports querying specific enterprise projects on an enterprise account. Currently, it doesn't support enabling enterprise project functions for ordinary accounts. This action needs to be completed on the HUAWEI CLOUD console.

**Comment by Lance52259** [comment]
Q: `Can we add orgs and sub-orgs and enterprise projects ?`
A: Not support yet. These operations can only be done by the console currently.

Q: `How can we add member account under the enterprise project ?`
A: Sorry, only the console can be added.

**Comment by ShiChangkuo** [comment]
I will close it temporarily, If you have any questions, please reopen it. Thanks.
