### ISSUE TITLE
Create mrs  about ClickHouse

### ISSUE THREAD

**Issue by jiege3324** [huaweicloud/terraform-provider-huaweicloud#1647]
* huaweicloud/huaweicloud: version = "~> 1.29.2"

Report error 

data.huaweicloud_vpc_subnet.subnet_mrs2: Refreshing state... [id=b7d4fd88-2703-421a-9564-4e3977c77f07]
huaweicloud_mapreduce_cluster.cluster2: Creating...

Error: Error creating Cluster: Bad request with: [POST https://mrs.cn-north-4.myhuaweicloud.com/v2/0dba08bb388090662ff3c00364b1cfff/clusters], error message: {"error_code":"12000002","error_msg":"The role list cannot be empty during customized cluster scaling out."}

  on mrs.tf line 12, in resource "huaweicloud_mapreduce_cluster" "cluster2":
  12: resource "huaweicloud_mapreduce_cluster" "cluster2" {

code list
data "huaweicloud_availability_zones" "az_mrs" {}

data "huaweicloud_vpc" "vpc_mrs2" {
  name = var.vpc_mrs2
}

data "huaweicloud_vpc_subnet" "subnet_mrs2" {
  vpc_id = data.huaweicloud_vpc.vpc_mrs2.id
  name = var.subnet_mrs2
}

resource "huaweicloud_mapreduce_cluster" "cluster2" {
  availability_zone  = data.huaweicloud_availability_zones.az_mrs.names[0]
  name               = var.mrsname2
  version            = var.mrsver2
  type               = "CUSTOM"
  component_list     = ["ClickHouse", "ZooKeeper"]
  manager_admin_pass = var.manager_admin_secret2
  node_admin_pass    = var.node_admin_secret2
  vpc_id             = data.huaweicloud_vpc.vpc_mrs2.id
  subnet_id          = data.huaweicloud_vpc_subnet.subnet_mrs2.id
  safe_mode          = true

  master_nodes {
    flavor            = var.master_size2
    node_number       = var.master_num2
    root_volume_type  = var.vol_type2
    root_volume_size  = 480
    data_volume_type  = var.vol_type2
    data_volume_size  = var.vol_master_size2
    data_volume_count = 1
  }

  custom_nodes {
    group_name        = "ClickHouse"
    flavor            = var.core_size2
    node_number       = var.core_num2
    root_volume_type  = var.vol_type2
    root_volume_size  = 480
    data_volume_type  = var.vol_type2
    data_volume_size  = var.vol_node_size2
    data_volume_count = 1
    assigned_roles = [
      "clickhouse",
      "meta"
    ]
  }

  tags = {
    foo = "bar"
    key = "value"

**Comment by hmbig2** [comment]
Error: Error creating Cluster: Bad request with: [POST https://mrs.cn-north-4.myhuaweicloud.com/v2/0dba08bb388090662ff3c00364b1cfff/clusters], error message: {"error_code":"12000002","error_msg":"The role list cannot be empty during customized cluster scaling out."}

as error_msg: you need set `assigned_roles` field in `master_nodes` when the type is `CUSTOM`

**Comment by ShiChangkuo** [comment]
@jiege3324 I'm going to close this issue because there are no updates for 20 days.
If you have found a problem that seems similar to this, please open a new issue and complete the issue template so we can capture all the details necessary to investigate further.
