### ISSUE TITLE
[DLI]Need a new resource to manage Datasource Authentication 

### ISSUE THREAD

**Issue by hmbig2** [huaweicloud/terraform-provider-huaweicloud#1670]
### Current Terraform Version

```
...
```

### Proposal

1. user create an Authentication Certificate

**Comment by ShiChangkuo** [comment]
we have add [huaweicloud_dli_datasource_auth](https://registry.terraform.io/providers/huaweicloud/huaweicloud/latest/docs/resources/dli_datasource_auth) in v1.47.0
