### ISSUE TITLE
CCE Addons 

### ISSUE THREAD

**Issue by Pavan976** [huaweicloud/terraform-provider-huaweicloud#1696]
Hello Team,

could you please help me with some docs to cerate  custom_json template for nginx-ingress addons?

cheers.

**Comment by Jason-Zhang9309** [comment]
Hi, have you read this doc?
https://github.com/huaweicloud/terraform-provider-huaweicloud/blob/master/examples/cce/basic/cce-addon-templates.md

**Comment by Pavan976** [comment]
Yes i did, but it doesn't have the nginx-ingress addons example, could you please help me with ingress custom template to configure ingress controller with existing private ELB and more ?

**Comment by Jason-Zhang9309** [comment]
You can get the nginx-ingress template using data source huaweicloud_cce_addon_template.
The custom_json is contained in the attribute `spec` of the data source.
It looks like this:
```json
{
     "basic": {
          "swr_addr": "swr.cn-north-4.myhuaweicloud.com",
          "swr_user": "hwofficial",
          "tag": "v0.46.0"
     },
     "parameters": {
          "custom": {
               "config": {},
               "defaultBackend": {
                    "enabled": true
               },
               "defaultBackendService": "",
               "headers": {},
               "service": {
                    "annotations": {},
                    "loadBalancerIP": ""
               },
               "tcp": {},
               "udp": {}
          },
          "flavor1": {
               "description": "custom resources",
               "name": "custom-resources",
               "replicas": 2,
               "resources": [
                    {
                         "limitsCpu": "8000m",
                         "limitsMem": "4000Mi",
                         "name": "nginx-ingress",
                         "requestsCpu": "8000m",
                         "requestsMem": "4000Mi"
                    }
               ]
          }
     }
}
```

You can also use the spec as you input while installing the addon with terraform functions.
Here is an example:
```hcl
resource "huaweicloud_cce_cluster" "test" {
  region = "cn-north-4"
  name                   = "zhangjishu-cce-addon-test"
  flavor_id              = "cce.s1.small"
  vpc_id                 = huaweicloud_vpc_v1.test.id
  subnet_id              = huaweicloud_vpc_subnet_v1.test.id
  container_network_type = "overlay_l2"

  masters {
      availability_zone = data.huaweicloud_availability_zones.myaz.names[0]
  }
}

data "huaweicloud_cce_addon_template" "test" {
  cluster_id = huaweicloud_cce_cluster.test.id
  name       = "nginx-ingress"
  version    = "1.2.6"
}

resource "huaweicloud_cce_addon" "test" {
  cluster_id = huaweicloud_cce_cluster.test.id
  template_name = "nginx-ingress"
  version    = "1.2.6"
  values {
    basic = jsondecode(data.huaweicloud_cce_addon_template.test.spec).basic
    custom_json = jsonencode(merge(
      jsondecode(data.huaweicloud_cce_addon_template.test.spec).parameters.custom,
      {
        "config" = {
          "key1" = "value1"
        }
        "defaultBackendService" = "xxxx"
        "headers" = {
            "key2" = "value2"
        }
        "service" = {
          "annotations": {
              "key3" = "value3"
          }
          "loadBalancerIP" = "x.x.x.x"
        }
        "tcp" = {
            "key4" = "value4"
        }
        "udp" = {
            "key5" = "value5"
        }
      }
    ))
  }
}
```

**Comment by Pavan976** [comment]
Great Thanks, this will help lot.

**Comment by Pavan976** [comment]
Hello Jason,

I need small help  on this again.

how do i pass **values** to modules from terraform.auto.tfvars ?

**Comment by Jason-Zhang9309** [comment]
@Pavan976,
 sorry for late response
I have tried using *.aotu.tfvars file. Here is an examle.
1. config a resource in vpc.tf
```
resource "huaweicloud_vpc" "test" {
  name = var.vpc_name
  cidr = var.vpc_cidr
}
```
2. config variables in vpc_variable.tf
```
variable "vpc_name" {
  type = string
  default = "test"
}

variable "vpc_cidr" {
  type = string
  default = "172.16.0.0/16"
}
```
3. config variables in vpc.auto.tfvars
```
vpc_name = "zhangjishu-test"
vpc_cidr = "192.168.1.0/24"
```
Test steps:
1. run terraform plan with all 3 files above.
```
# huaweicloud_vpc.test will be created
  + resource "huaweicloud_vpc" "test" {
      + cidr                  = "192.168.1.0/24"
      + enterprise_project_id = (known after apply)
      + id                    = (known after apply)
      + name                  = "zhangjishu-test"
      + region                = (known after apply)
      + routes                = (known after apply)
      + status                = (known after apply)
    }

Plan: 1 to add, 0 to change, 0 to destroy.
```
2. remove vpc.auto.tfvars and run terraform again
```
# huaweicloud_vpc.test will be created
  + resource "huaweicloud_vpc" "test" {
      + cidr                  = "172.16.0.0/16"
      + enterprise_project_id = (known after apply)
      + id                    = (known after apply)
      + name                  = "test"
      + region                = (known after apply)
      + routes                = (known after apply)
      + status                = (known after apply)
    }

Plan: 1 to add, 0 to change, 0 to destroy.
```
If there is no *.auto.tfvars file, terraform will use the default values in definition of variables.
If there is a *.auto.tfvars file, terraform will override the default values with values in *.auto.tfvars file.

Hope this helps you.

**Comment by Pavan976** [comment]
Thank you .!!

**Comment by Lance52259** [comment]
We are closing this support issue because it has been inactive more than three days. If you still encounter problems, you can join `Discussion` and ask your questions there, which may provide you with better service.

**Comment by cdpiazza** [comment]
Hi, does the nginx-addonn supports the "flavor_json", i believe im getting erros about that because when i send only the basic and custom json everything works, but when i try to specify the flavor data (resources, limits, replicas, etc) it breaks...

**Comment by thisurawijesekera** [comment]
When I am trying to autocreate the elb with addon I am getting below error.

`╷
│ Error: error creating CCE add-on: Bad request with: [POST [https://3d019829-8066-11ef-b874-0255ac10003d.cce.***.myhuaweicloud.com/api/v3/addons],](https://3d019829-8066-11ef-b874-0255ac10003d.cce.%2A%2A%2A.myhuaweicloud.com/api/v3/addons],) request_id: 76c298b1a376a44e95bda0e3f930cee4, error message: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","code":400,"errorCode":"CCE.03400001","errorMessage":"Invalid request.","error":{"message":"kubernetes.io/elb.id and loadBalancerIP cannot both be empty","code":"SVCSTG.CCE-ADDONMGR.4000002"},"message":"kubernetes.io/elb.id and loadBalancerIP cannot both be empty","reason":"BadRequest"}`
