### ISSUE TITLE
SWR information

### ISSUE THREAD

**Issue by anmolnatesha** [huaweicloud/terraform-provider-huaweicloud#1703]
Hi Team,

can you please explain about the login_server attribute in the huaweicloud_swr_organization

Thanks

**Comment by ShiChangkuo** [comment]
`login_server` is the endpoint of SWR service or container registry, and it in format of swr.{{ region }}.myhuaweicloud.com

you can use the URL to push/pull docker images to your repo, for example:
docker push swr.cn-north-1.myhuaweicloud.com/{Organization Name}/{Image Name}:{Tag name}

**Comment by anmolnatesha** [comment]
Thank You
