### ISSUE TITLE
Configure "Source/Destination Check" for ECS NIC 

### ISSUE THREAD

**Issue by aaovchinnikov** [huaweicloud/terraform-provider-huaweicloud#1706]
Hi there,

Today we don't have an ability to control "Source/Destination Check" parameter for ECS NIC. It would be handy to have such ability, especially for scenarios with automated creation of all infrastructure needed for remote-acceess VPNs:

- Subnet
- ECS (with "Source/Destination Check" disabled)
- DNAT rule
- VPC route to ECS

With recent version of provider (v.1.30.0) I can do all of that excluding "Source/Destination Check" control.

For example AWS has such ability (https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/instance#source_dest_check)

Terraform version: 1.0.0
Provider: huaweicloud 1.30.0

**Comment by ShiChangkuo** [comment]
@aaovchinnikov thanks for raising this. I will try to add **source_dest_check** field into the network block.
