### ISSUE TITLE
An optimization requirement of support array-based identification of multiple resources of the same type in resource files

### ISSUE THREAD

**Issue by xiangyuanzhu** [huaweicloud/terraform-provider-huaweicloud#174]
Hi there,

The resource files of terraform do not support the batch arrangement for the same type of resources in the form of arrays. For example,  multiple network cards of a new ECS can only be represented by multiple network nodes at present. We look forward to optimizing this kind of problem. Thank you.
当前terraform工具的资源文件不支持以数组形式批量编排相同类型的资源，比如新申请一台多网卡的ECS，当前只能通过多个network节点来表示，期望对该类问题进行优化，谢谢

Terraform Version
Terraform v0.12.3

Affected Resource(s)
NO

Terraform Configuration Files
NO

Debug Output
NO

Panic Output
NO

Expected Behavior
NO

Actual Behavior
NO

Steps to Reproduce
NO

Important Factoids
NO

References
NO

**Comment by niuzhenguo** [comment]
will add networking interface attaching support instead.
