### ISSUE TITLE
[FGS] There is no way to pass sensitive information to huaweicloud_fgs_function resource

### ISSUE THREAD

**Issue by mrkutin** [huaweicloud/terraform-provider-huaweicloud#1763]
There is no way to pass sensitive information to huaweicloud_fgs_function resource. 
The only available huaweicloud_fgs_function parameter for passing user key-value pairs is user_data.
When I pass sensitive data over there, both sensitive and regular info go to Environment Variables section undo Configuration tab, even though I marked sensitive variables

### Terraform Version
Terraform v1.0.11
on darwin_amd64
+ provider registry.terraform.io/huaweicloud/huaweicloud v1.26.1

### Terraform Configuration Files
in variables.tf:
```
variable "REDIS_PASSWORD" {
  type      = string
  sensitive = true
}
```

in terraform.tfvars
```
REDIS_PASSWORD = "MY_SECURE_PASSWORD"
```

in main.tf:
```
user_data = jsonencode({
    REDIS_HOST     = var.REDIS_HOST
    REDIS_PORT     = var.REDIS_PORT
    REDIS_PASSWORD = var.REDIS_PASSWORD
  })
```

### Expected Behavior
sensitive information must go to Encryption Settings section, not in Environment Variables section (in UI)

### Actual Behavior
sensitive information goes to Environment Variables section along with regular user data

**Comment by Lance52259** [comment]
We are reviewing this demand and expect to get back to you within three working days.

**Comment by Lance52259** [comment]
@mrkutin  Relevant support modifications have been submitted, please pay attention to this PR #1766
