### ISSUE TITLE
[EVS] Use new V2 API to refactor evs resources

### ISSUE THREAD

**Issue by niuzhenguo** [huaweicloud/terraform-provider-huaweicloud#1817]
We need to refactor the evs resources with new V2 API due to V3 API deprecated and OpenStack API not recommended.

**Comment by realli07kkk** [comment]
Why V3 deprecated? and V2 is new version

**Comment by niuzhenguo** [comment]
@realli07kkk V3 API already moved to History API on help center, I'm not sure why as well.

**Comment by realli07kkk** [comment]
@niuzhenguo Reply from Huawei Cloud Support：
![image](https://user-images.githubusercontent.com/40236947/146887647-17637ff7-6efa-41c8-ac92-ffb4992e97ea.png)
