### ISSUE TITLE
[Logger] Incorrect request body display

### ISSUE THREAD

**Issue by Lance52259** [huaweicloud/terraform-provider-huaweicloud#1833]
Hi team,

I tried to send a GET request with a header containing Content-Type as follows:
```
Content-Type: application/json
```
After I send it, the log will output the last request body to the current request, but this request does not contain any request body.
This information can help quickly locate the target code location:
```
[DEBUG] API Request Body
```

Best regards

**Comment by ShiChangkuo** [comment]
@Lance52259 As we discussed before, the issue can not be reproduced, so let's close it.
If you have found a problem that seems similar to this, please open a new issue.
