### ISSUE TITLE
Add ru-moscow-1 region to provider to deploy by Terraform in Moscow.

### ISSUE THREAD

**Issue by abejaranog** [huaweicloud/terraform-provider-huaweicloud#1896]
### Current Terraform Version

```
Terraform v0.14.4
```

### Use-cases

Deploy infrastucture using Terraform in ru-moscow-1 region by Terraform.

### Attempted Solutions

```
─$ terraform plan
Acquiring state lock. This may take a few moments...

Error: [DEBUG] cannot find the tenant: ru-moscow-1

  on main.tf line 17, in provider "huaweicloud":
  17: provider "huaweicloud" {


Releasing state lock. This may take a few moments...
```

but with other regions, like sa-brazil-1 it works:

```
╰─$ terraform plan
Acquiring state lock. This may take a few moments...

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:
...
...
...
...
..
.
Plan: 8 to add, 0 to change, 0 to destroy.

------------------------------------------------------------------------

Note: You didn't specify an "-out" parameter to save this plan, so Terraform
can't guarantee that exactly these actions will be performed if
"terraform apply" is subsequently run.

Releasing state lock. This may take a few moments...
```

**Comment by ShiChangkuo** [comment]
@abejaranog can you show your configuration of **huaweicloud** provider block?
As far as I know, Huawei Cloud does not have a region named "ru-moscow-1".

**Comment by abejaranog** [comment]
```
terraform {
  backend "s3" {
...
...
  }
  required_providers {
    huaweicloud = {
      source  = "huaweicloud/huaweicloud"
      version = "~> 1.26.0"
    }
  }
}

provider "huaweicloud" {
  region = var.region
}

...
region = "ru-moscow-1"
```

When I change "ru-moscow-1" by another region, terraform works well, but my company and I are interested to deploy terraform in Moscow region.

Maybe the tenant name is not ru-moscow-1, but Moscow region exists on Huawei cloud as I can show in the following screenshot.

<img width="468" alt="imagen" src="https://user-images.githubusercontent.com/61002781/149733817-e09220ec-279c-4fb5-b2ce-18d2369caf11.png">

The access URL is: https://ru-console-intl.huaweicloud.com/console/?region=ru-moscow-1 so I deduced that the tenant name is "ru-moscow-1"

Thanks for your help.

**Comment by ShiChangkuo** [comment]
please try to get the project or region name  from [Obtaining Account, IAM User, Group, Project, Region, and Agency Information](https://support.huaweicloud.com/intl/en-us/api-iam/iam_17_0002.html)

**Comment by abejaranog** [comment]
Received this error:

<img width="407" alt="imagen" src="https://user-images.githubusercontent.com/61002781/149763336-773245ef-35f5-4c16-a4d7-e68859fcfef9.png">

**Comment by abejaranog** [comment]
Attached the project name:
<img width="1172" alt="imagen" src="https://user-images.githubusercontent.com/61002781/149764595-a219dd9b-a98a-430c-bb68-b79b0b408308.png">

**Comment by ShiChangkuo** [comment]
please try the following methods:
1. open the debug with: `export TF_LOG=TRACE; export TF_LOG_PATH=./tf.log`, and then run terraform command;
2. get the project ID of ru-moscow-1 and add it to provider block: `project_id = xxxx`, then run terraform command; 

if it still does not works, please attach the **tf.log** file

**Comment by ShiChangkuo** [comment]
You can try to get token with postman, here is an example https://support.huaweicloud.com/intl/en-us/api-iam/iam_30_0001.html#section3

**Comment by abejaranog** [comment]
I have had a meet with some members of Huawei Cloud team. 

They told me that Russia is a new Region that nowadays is managed by a third-party provider in the region, but Huawei manages the services.

This means that all the log-in process pass for another IAM service different than the Global, so I try to find the correct endpoint and attach here the log.

Also, Huawei tolds me that there are other regions in the same situation. Do you know anything about that and how to solve this differences on the provider?

Thank you. Regards.

**Comment by ShiChangkuo** [comment]
maybe you should try to use [sbercloud provider](https://registry.terraform.io/providers/sbercloud-terraform/sbercloud/latest/docs) or use huaweicloud provider with cloud and autn_url parameters in provider block, please refer to #1341

**Comment by abejaranog** [comment]
Using sbercloud provider I can deploy my infrastructure on Huawei Cloud in Russia region.

Many thanks!!
