### ISSUE TITLE
[CBR] Adding long-term retention settings to the huaweicloud_cbr_policy

### ISSUE THREAD

**Issue by ev-grebenyuk** [huaweicloud/terraform-provider-huaweicloud#1971]
### Current Terraform Version

```
Terraform v1.0.0
on darwin_amd64
+ provider registry.terraform.io/huaweicloud/huaweicloud v1.33.0

Your version of Terraform is out of date! The latest version
is 1.1.6. You can update by downloading from https://www.terraform.io/downloads.html
```

### Use-cases

Need to manage CBR policy Long-term retention settings of the "Backup quantity" Retention rule via terraform.

### Attempted Solutions

There is no needed arguments to resolve the issue.

### Proposal

For example, adding a **long_term_retention** argument to a **huaweicloud_cbr_policy**
```
resource "huaweicloud_cbr_policy" "policy1" {
  name            = "policy1"
  type            = "backup"
  backup_quantity = 7
  long_term_retention {
    daily   = 5
    weekly  = 1
    monthly = 1
    yearly  = 0
  }
  backup_cycle {
    interval        = 1
    execution_times = ["01:00"]
  }
}
```

**Comment by Lance52259** [comment]
`time_period` is a backup duration parameter, in days.

**Comment by ev-grebenyuk** [comment]
I am talking about these parameters in web-console (take a look at the attached screenshot).
Now I cannot manage them via terraform because there are no such parameters in the huaweicloud_cbr_policy resource.
<img width="1236" alt="Screen 2022-02-21 at 15 19 36" src="https://user-images.githubusercontent.com/68594418/154954652-1eec5d8d-f601-4552-83ff-22548a08528c.png">

**Comment by Lance52259** [comment]
Thanks for your suggestion, we will develop this feature in the future and plan to release it with the version within 30 days.
