### ISSUE TITLE
Destroy a `huaweicloud_compute_instance` does not destroy its disk.

### ISSUE THREAD

**Issue by alissa-tung** [huaweicloud/terraform-provider-huaweicloud#1973]
```hcl
resource "huaweicloud_compute_instance" "server" {
  data_disks {
    type = var.data_disk_type
    size = var.data_disk_sizes["server"]
  }
```

will create a server and mount a newly created disk. the `terraform apply -destroy` action does not destroy the disk.

**Comment by ShiChangkuo** [comment]
@alissa-tung sorry for the delay. Actually, you can delete data disks with setting **delete_disks_on_termination** to true.
here is an example: [Instance With Multiple Data Disks](https://registry.terraform.io/providers/huaweicloud/huaweicloud/latest/docs/resources/compute_instance#instance-with-multiple-data-disks)

**Comment by alissa-tung** [comment]
thx
