### ISSUE TITLE
How to save terraform state in an obs service

### ISSUE THREAD

**Issue by dritux** [huaweicloud/terraform-provider-huaweicloud#2014]
Dear,

I'm creating my resources on Huawei Cloud and I haven't found a way to synchronize the grounded state in the obs service.

As backend in the link:
https://www.terraform.io/language/settings/backends#available-backends

I didn't find any for huawei.

Example of how I used it on GCP:

  backend "gcp" {
    bucket = "fs-dev-tools-terraform-state"
    prefix = "env/prod"
  }

**Comment by Lance52259** [comment]
try this:
```
terraform {
  required_providers {
    huaweicloud = {
      source  = "huaweicloud/huaweicloud"
      version = "version contral"
    }
  }

  backend "s3" {
    bucket = "your storage bucket name"
    key    = "terraform/terraform.tfstate" // The location where the state file wants to be stored in OBS.
    region = "your region"
    encrypt = true
    endpoint = "your OBS bucket endpoint"

    skip_region_validation      = true
    skip_metadata_api_check     = true
    skip_credentials_validation = true
  }
}

```

**Comment by Lance52259** [comment]
https://www.terraform.io/language/settings/backends/s3

**Comment by ShiChangkuo** [comment]
I'm going to close this issue because there are no updates for 30 days.
If you have found a problem that seems similar to this, please open a new issue and complete the issue template so we can capture all the details necessary to investigate further.
