### ISSUE TITLE
How to associate a project in the huaweicloud_vpc_eip resource

### ISSUE THREAD

**Issue by dritux** [huaweicloud/terraform-provider-huaweicloud#2021]
I didn't find in the documentation the parameter to associate the Enterprise Project in the huaweicloud_vpc_eip resource

Documentation example

```
resource "huaweicloud_vpc_eip" "cce" {
  publicip {
    type = "5_bgp"
  }
  bandwidth {
    name = "eip-sonarqube-prod-la-south-2"
    size = 20
    share_type = "PER"
    charge_mode = "traffic"
  }
}

**Comment by Lance52259** [comment]
https://registry.terraform.io/providers/huaweicloud/huaweicloud/latest/docs/resources/vpc_eip

**Comment by Lance52259** [comment]
```
resource "huaweicloud_vpc_eip" "cce" {
  enterprise_project_id = "your eps ID"

  publicip {
    type = "5_bgp"
  }

  bandwidth {
    name = "eip-sonarqube-prod-la-south-2"
    size = 20
    share_type = "PER"
    charge_mode = "traffic"
  }
}
```

**Comment by ShiChangkuo** [comment]
I'm going to close this issue because there are no updates for 30 days.
If you have found a problem that seems similar to this, please open a new issue and complete the issue template so we can capture all the details necessary to investigate further.
