### ISSUE TITLE
API Error creating Security Group - error_code":"APIGW.0101

### ISSUE THREAD

**Issue by benhur-araujo** [huaweicloud/terraform-provider-huaweicloud#2050]
### Terraform Version
```
Terraform v1.1.7
on linux_386
provider registry.terraform.io/huaweicloud/huaweicloud v1.34.1
```

### Terraform Configuration Files
```
resource "huaweicloud_networking_secgroup" "sg_test" {
  name        = "hw-test-sg"
  description = "Security Group test"
}
```

### Expected Behavior

Create a Security Group called "sg_test"

### Actual Behavior

Plan: 1 to add, 0 to change, 0 to destroy.
huaweicloud_networking_secgroup.sg_test: Creating...
╷
│ Error: Error creating Security Group: Resource not found: [POST https://vpc.sa-brazil-1.myhuaweicloud.com/v3/0df327ee7080f2d52f3ac0130e42af0f/vpc/security-groups], error message: {"error_msg":"The API does not exist or has not been published in the environment","error_code":"APIGW.0101","request_id":"220b2c0b5847e3e3f0437c2111b1b19f"}

### Steps to Reproduce

1. `terraform init`
2. `terraform apply`

**Comment by Lance52259** [comment]
Thank you for using HuaweiCloud provider.
We are working on a fix (#2048) for this, with a release at the end of the month.
