### ISSUE TITLE
can not create ecs with flavor `ir3.4xlarge.4`

### ISSUE THREAD

**Issue by YangKian** [huaweicloud/terraform-provider-huaweicloud#2110]
### Terraform Version

```
Terraform v1.1.8
```

### Terraform Configuration Files

```hcl
resource "huaweicloud_compute_instance" "server" {
  count        = 2
  name        = "hserver-${count.index}"
  image_name  = "Ubuntu 20.04 server 64bit"
  flavor_name = "ir3.4xlarge.4"
  key_pair    = var.key_pair_name
  security_group_ids = [var.security_group_ids]

  network {
    access_network = true
    uuid                    = var.network_uuid 
}

```
I get an error when I want to create `ir3.4xlarge.4` ecs instance with terraform
```
│ Error: Error creating HuaweiCloud server: Bad request with: [POST https://ecs.cn-southwest-2.myhuaweicloud.com/v1.1/0eb5b244ac8091662f89c00ee3a3c060/cloudservers], error message: {"error":{"message":"The flavor does not match the image.","code":"Ecs.0005"}}                                           
│                                                           
│   with huaweicloud_compute_instance.server[2],
│   on main.tf line 32, in resource "huaweicloud_compute_instance" "server":
│   32: resource "huaweicloud_compute_instance" "server" {
```
And I didn't see the instance created on the web console.

**Comment by YangKian** [comment]
I create success with flavor `s6.small.1` and `c6s.2xkarge.2`, but failed with `ir3.4xlarge.4` and `ir3.2xlarge.4`. Hope someone can help me with this problem, thanks a lot！

**Comment by realli07kkk** [comment]
ir3.4xlarge.4 not support Ubuntu 20.04 server 64bit,try centos

**Comment by YangKian** [comment]
>

**Comment by YangKian** [comment]
> ir3.4xlarge.4 not support Ubuntu 20.04 server 64bit,try centos

try with `CentOS 7.9 64bit` and `CentOS 8.2 64bit`, same error again

**Comment by realli07kkk** [comment]
> > ir3.4xlarge.4 not support Ubuntu 20.04 server 64bit,try centos
> 
> try with `CentOS 7.9 64bit` and `CentOS 8.2 64bit`, same error again

According to the console information, 7.9 and 8.2 are also not supported, I tried 8.0 is ok, I tested at cn-east-3

**Comment by YangKian** [comment]
Ok, I'll have a try. Thanks a lot.

Incidentally, I can create `ir` series on ubuntu 20 using the web console, is this configuration not yet supported by terraform?

**Comment by realli07kkk** [comment]
> Ok, I'll have a try. Thanks a lot.
> 
> Incidentally, I can create `ir` series on ubuntu 20 using the web console, is this configuration not yet supported by terraform?

You can create a case on the HUAWEI CLOUD official website. The Terraform only complies with the ECS API specifications. The ECS service determines whether the parameters are available.
