### ISSUE TITLE
compute_instance_v2 gave the wrong example of "Instance With Attached Volume"

### ISSUE THREAD

**Issue by freesky-edward** [huaweicloud/terraform-provider-huaweicloud#218]
the parameters of ```compute_volume_attach_v2``` are:
- instance_id
- volume_id
please refer to [compute_volume_attach_v2](https://www.terraform.io/docs/providers/huaweicloud/r/compute_volume_attach_v2.html)

however the examples in ```compute_instance_v2``` showing is 
- compute_id
- volume_id

please refer to [example](https://www.terraform.io/docs/providers/huaweicloud/r/compute_instance_v2.html#instance-with-attached-volume)

### Terraform Version
NA

### Affected Resource(s)
Please list the resources as a list, for example:
- compute_volume_attach_v2
- compute_instance_v2

### Debug Output
```
Error: Missing required argument

  on evs/vol_temp.tf line 9, in resource "huaweicloud_compute_volume_attach_v2" "this":
   9: resource "huaweicloud_compute_volume_attach_v2" "this" {

The argument "instance_id" is required, but no definition was found.


Error: Unsupported argument

  on evs/vol_temp.tf line 11, in resource "huaweicloud_compute_volume_attach_v2" "this":
  11:   compute_id = "${lookup(var.vol_attaches[count.index], "server_id")}"

An argument named "compute_id" is not expected here.
```

### Panic Output
NA

### Expected Behavior
anyone can use the example corrently

### Actual Behavior
it prints the error message

**Comment by niuzhenguo** [comment]
@freesky-edward Thanks for raising this, will fix soon!
