### ISSUE TITLE
[feature] Ask help to support CDN resource

### ISSUE THREAD

**Issue by freesky-edward** [huaweicloud/terraform-provider-huaweicloud#220]
currently, this provider doesn't support CDN service yet. this issue is to ask whether anyone can help to implement it. much appreciate your help.

### Terraform Version
NA

### Affected Resource(s)
Please list the resources as a list, for example:
- huaweicloud-cdn?

### Terraform Configuration Files
NA

### Debug Output
NA

### Panic Output
NA

### Expected Behavior
CDN service can be managed by terraform

### Actual Behavior
There is no CDN relevant resource.

### Steps to Reproduce
NA

### Important Factoids
NA

### References
https://www.huaweicloud.com/en-us/product/cdn.html

**Comment by niuzhenguo** [comment]
@ShiChangkuo please help to add this resource!

**Comment by ShiChangkuo** [comment]
ok, let me have a try, and it would be better if we named the resource huaweicloud_cdn_domain.
