### ISSUE TITLE
autoscaler addons setup

### ISSUE THREAD

**Issue by fabricio-josouza** [huaweicloud/terraform-provider-huaweicloud#2208]
### Terraform Version

Terraform v1.2.1
on linux_amd64
+ provider registry.terraform.io/huaweicloud/huaweicloud v1.37.0

Your version of Terraform is out of date! The latest version
is 1.2.2. You can update by downloading from https://www.terraform.io/downloads.html

### Terraform Configuration Files
 addons.tf

resource "huaweicloud_cce_addon" "metrics" {
  cluster_id    = huaweicloud_cce_cluster.cce_cluster.id
  template_name = "metrics-server"
  version       = "1.2.1"
}

resource "huaweicloud_cce_addon" "dashboard" {
  cluster_id    = huaweicloud_cce_cluster.cce_cluster.id
  template_name = "dashboard"
  version       = "2.1.1"
}

resource "huaweicloud_cce_addon" "cce-hpa-controller" {
  cluster_id    = huaweicloud_cce_cluster.cce_cluster.id
  template_name = "cce-hpa-controller"
  version       = "1.2.11"
}

resource "huaweicloud_cce_addon" "prometheus" {
  cluster_id    = huaweicloud_cce_cluster.cce_cluster.id
  template_name = "prometheus"
  version       = "2.21.14"
}

resource "huaweicloud_cce_addon" "autoscaler" {
  cluster_id    = huaweicloud_cce_cluster.cce_cluster.id
  template_name = "autoscaler"
  version       = "1.21.1"
}`

### Crash Output
 Not enable due to the sintaxe or some stupid config

### Actual Behavior
 the "Autoscaler" did not install

### Additional Context

![Capture](https://user-images.githubusercontent.com/43297942/173717768-5999c283-153d-44cb-83d7-b26151947a4e.PNG)

**Comment by ShiChangkuo** [comment]
@fjosouza Arguments which can be passed to the basic_json, custom_json and flavor_json add-on parameters depends on the add-on type and version. For more detailed description of add-ons see [add-ons description](https://github.com/huaweicloud/terraform-provider-huaweicloud/blob/master/examples/cce/basic/cce-addon-templates.md)

**Comment by jveraduran** [comment]
Hi @ShiChangkuo!

Thanks for the information

**Comment by aaovchinnikov** [comment]
Hi @fjosouza 

I use this code to deploy autoscaler

```
data "huaweicloud_cce_addon_template" "autoscaler" {
  cluster_id = huaweicloud_cce_cluster.cluster.id
  name       = "autoscaler"
  version    = var.autoscaler_plugin_version
}

resource "huaweicloud_cce_addon" "autoscaler" {
  # Autoscaler should be scheduled on some worker nodes, so they must be created beforehand
  depends_on = [
    resource.huaweicloud_cce_node_pool.pools
  ]
  cluster_id    = huaweicloud_cce_cluster.cluster.id
  template_name = data.huaweicloud_cce_addon_template.autoscaler.name
  version       = data.huaweicloud_cce_addon_template.autoscaler.version
  values {
    basic_json = jsonencode(jsondecode(data.huaweicloud_cce_addon_template.autoscaler.spec).basic)
    custom_json = jsonencode(
      merge(
        jsondecode(data.huaweicloud_cce_addon_template.autoscaler.spec).parameters.custom,
        {
          cluster_id       = huaweicloud_cce_cluster.cluster.id
          tenant_id        = var.iam_project_id
          scaleDownEnabled = true
        }
      )
    )
  }
}
```

As I can see, it's kind of this [sample](https://github.com/huaweicloud/terraform-provider-huaweicloud/blob/master/examples/cce/basic/cce-addon-templates.md#use-basic-and-custom)

**Comment by fabricio-josouza** [comment]
Okay...
Tks I will do that and get back
--
Sent from myMail for Android Tuesday, 13 September 2022, 03:07AM -03:00 from Alexander Ovchinnikov  ***@***.*** :

**Comment by ShiChangkuo** [comment]
@fjosouza I'm going to close this issue because there are no updates for 20 days.
If you have found a problem that seems similar to this, please open a new issue and complete the issue template so we can capture all the details necessary to investigate further.
