### ISSUE TITLE
Error on creating security group and rules

### ISSUE THREAD

**Issue by Kin6HA** [huaweicloud/terraform-provider-huaweicloud#2217]
hi, we are using the terraform module for huaweicloud_networking_secgroup and huaweicloud_networking_secgroup_rule, with following errors:

**Error**
│ Warning: Resource not found
│
│   with huaweicloud_networking_secgroup_rule.mysecgroup2_rule1,
│   on main.tf line 26, in resource "huaweicloud_networking_secgroup_rule" "mysecgroup2_rule1":
│   26: resource "huaweicloud_networking_secgroup_rule" "mysecgroup2_rule1" {
│
│ the resource XXXXXXXXXXXXX is gone and will be removed in Terraform state.
│
│ (and one more similar warning elsewhere)
╵
╷
│ Error: Provider produced inconsistent result after apply
│
│ When applying changes to huaweicloud_networking_secgroup_rule.mysecgroup2_rule2, provider "provider[\"registry.terraform.io/huaweicloud/huaweicloud\"]" produced an unexpected new value: Root resource was present, but now absent.
│
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.
╵
╷
│ Error: Provider produced inconsistent result after apply
│
│ When applying changes to huaweicloud_networking_secgroup_rule.mysecgroup2_rule1, provider "provider[\"registry.terraform.io/huaweicloud/huaweicloud\"]" produced an unexpected new value: Root resource was present, but now absent.
│
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.

**Below is the tf code:**
resource "huaweicloud_networking_secgroup" "mysecgroup2" {
  name        = "mysecgroup2"
  description = "My security group"
}

resource "huaweicloud_networking_secgroup_rule" "mysecgroup2_rule1" {
  security_group_id = huaweicloud_networking_secgroup.mysecgroup2.id
  direction         = "ingress"
  ethertype         = "IPv4"
  protocol          = "tcp"
  port_range_min    = 8080
  port_range_max    = 8080
  remote_ip_prefix  = "0.0.0.0/0"
}
resource "huaweicloud_networking_secgroup_rule" "mysecgroup2_rule2" {
  security_group_id = huaweicloud_networking_secgroup.mysecgroup2.id
  direction         = "ingress"
  ethertype         = "IPv4"
  protocol          = "tcp"
  port_range_min    = 443
  port_range_max    = 443
  remote_ip_prefix  = "0.0.0.0/0"
}

Shall anyone assist on it?

**Comment by ShiChangkuo** [comment]
@Kin6HA Sorry for the delay, are you still suffering from the same issue?

**Comment by ShiChangkuo** [comment]
I will close it temporarily, If you have found a problem that seems similar to this, please open a new issue and complete the issue template so we can capture all the details necessary to investigate further.
