### ISSUE TITLE
无法创建华为云instance

### ISSUE THREAD

**Issue by jami1024** [huaweicloud/terraform-provider-huaweicloud#229]
### Terraform Version
Terraform v0.12.6
terraform-provider-huaweicloud_v1.10.0_x4

### cvm.tf文件

provider "huaweicloud" {
  access_key  = "xxxx"
  secret_key  = "xxxxx"
  auth_url    = "https://iam.myhwclouds.com:443/v3"
  region = "cn-east-3"
  tenant_name = "cn-east-3"
  domain_name = "xxxxxx"
}

resource "huaweicloud_ecs_instance_v1" "basic" {
  name     = "test2"
  image_id = "f18e7940-9e31-4a53-bbae-e9f462e57499"
  flavor   = "s3.small.1"
  vpc_id   = "dd9f438e-559c-40d1-97fa-769349184236"
  charging_mode = "prePaid"
  period_unit  = "month"
  period = 1
  count = 2
  delete_disks_on_termination  = true

  nics {
    network_id = "05d6af6a-04f9-465b-8aea-0dd9ad05ae1a"
  }

  system_disk_type = "SAS"
  system_disk_size = 40

  data_disks {
    type = "SAS"
    size = "10"
  }

  availability_zone = "cn-east-3a"
  password  = "xxxxxxxx"
  security_groups   = [xxxxxxxx]
}

resource "huaweicloud_compute_floatingip_associate_v2" "my_ip" {
  region = "cn-east-3"
  count = 2
  floating_ip = "${huaweicloud_vpc_eip_v1.eip_1.publicip[0].ip_address}"
  instance_id = "${huaweicloud_ecs_instance_v1.basic[count.index].id}"
}
resource "huaweicloud_vpc_eip_v1" "eip_1" {
  region = "cn-east-3"
  publicip {
    type = "5_bgp"
  }
  bandwidth {
    name = "test"
    size        = 8
    share_type  = "PER"
    charge_mode = "traffic"
  }
}

### 失败提示

Plan: 5 to add, 0 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

huaweicloud_vpc_eip_v1.eip_1: Creating...
huaweicloud_ecs_instance_v1.basic[0]: Creating...
huaweicloud_ecs_instance_v1.basic[1]: Creating...
huaweicloud_vpc_eip_v1.eip_1: Creation complete after 8s [id=a2ea9a8c-8369-4c53-84cc-9946676e3256]

Error: Resource not found: [GET https://bss.myhuaweicloud.com/v1.0//common/order-mgr/orders-resource/CS1911141853WHYSW], error message: {"error_msg":"The API does not exist or has not been published in the environment","error_code":"APIGW.0101","request_id":"3d4e2240a2b23f464484a34c7437266c"}

  on cvm.tf line 10, in resource "huaweicloud_ecs_instance_v1" "basic":
  10: resource "huaweicloud_ecs_instance_v1" "basic" {

Error: Resource not found: [GET https://bss.myhuaweicloud.com/v1.0//common/order-mgr/orders-resource/CS1911141853TLMXV], error message: {"error_msg":"The API does not exist or has not been published in the environment","error_code":"APIGW.0101","request_id":"1e36438fa68ae951956a56a0b2eb87da"}

  on cvm.tf line 10, in resource "huaweicloud_ecs_instance_v1" "basic":
  10: resource "huaweicloud_ecs_instance_v1" "basic" {

**Comment by niuzhenguo** [comment]
closed by #231
