### ISSUE TITLE
[CCE] Creating CCE Node with Disk Encryption Failed

### ISSUE THREAD

**Issue by zhenzh** [huaweicloud/terraform-provider-huaweicloud#2357]
When I try to create a data disk with kms encryption id, error message below was reported:
│ Error: Error waiting for job (2b2e2b9d-2d32-11ed-abcc-0255ac1002c7) to become success: unexpected state 'Failed', wanted target 'Success'. last error: %!s(<nil>), reason: [[CreateNodeVM.DoError] Expected HTTP response code [200 201 202 203 204] when accessing [POST https://ecs-internal.cn-east-3.myhuaweicloud.com/v1/xxxxxxxxxxxxxxxxxxxxxxxxx/cloudservers], but got 400 instead
│ {"error":{"message":"Failed to check the role of kms.{\"error\":{\"code\":\"EVS.2044\",\"message\":\"Failed to check the role of kms.\"}}","code":"Ecs.0025"}}, [InstallNode.DoError] [Install.Dependency] creating node machine failed]

In the document for huaweicloud_cce_node, it mentioned EVSAccessKMS is required. I have already had such agency created in my terraform as below:
```
resource "huaweicloud_identity_agency" "agency" {
  name                      = "EVSAccessKMS"
  description               = "Agency Created by Terraform for EVS Accessing KMS"
  delegated_service_name    = "op_svc_evs"

  domain_roles              = ["KMS Administrator"]
}
```

**Comment by niuzhenguo** [comment]
Seems this is an error on Service side, you can create a ticket to them with the API error logs.

**Comment by ShiChangkuo** [comment]
@zhenzh I will close it temporarily, If you have any questions, please reopen it. Thanks.
