### ISSUE TITLE
[CCE] Need PEM formated credentials for kubernetes provider

### ISSUE THREAD

**Issue by zhenzh** [huaweicloud/terraform-provider-huaweicloud#2359]
As kubernetes provider requires PEM credentials(client_certificate,client_key,cluster_ca_certificate) for connection input, can you provide such cce reference attributes with PEM format, rather than the current raw data which can not been used by kubernetes provider directly?

**Comment by niuzhenguo** [comment]
You can json encode the raw data and split yourself.

**Comment by zhenzh** [comment]
you are right.
