### ISSUE TITLE
[OBS] multi_az parameter doesn't work

### ISSUE THREAD

**Issue by zhenzh** [huaweicloud/terraform-provider-huaweicloud#2369]
Though I have specified multi_az = true in my resource and it do show me the correct result in preview, the terraform created single az obs finally.
When I try applying again without any updating, terraform do detected the existing obs is a single az one and tell me it will be force replaced to multi az after apply. While the terraform destroy the older obs and recreated a new single az obs again.

I have proved the 1.39.0 and later version are impacted by the issue, but the 1.38.0 and earlier version has no such issue.

**Comment by ShiChangkuo** [comment]
@zhenzh  can you provide your tf script and debug log to help us analyse the issue？I tested it well with my account in cn-north-4.

**Comment by zhenzh** [comment]
Here's my test block:

```
terraform {
  required_version          = "~> 1.0.0, < 1.1.0"

  required_providers {
    huaweicloud = {
      source                = "huaweicloud/huaweicloud"
      version               = "1.40.1"
    }
  }
}

provider "huaweicloud" {
  region                    = "cn-east-3"
}

resource "huaweicloud_obs_bucket" "obs_bucket" {
  bucket                    = "sh1-devqa-vault-obs"
  acl                       = "private"
  multi_az                  = true
  versioning                = false
  force_destroy             = true
  storage_class             = "WARM"
}
```


I have some new founds this time. It may not be the multi_za parameter issue.
When the bucket is first time created, obs can be successfully created with the specified az policy.
If I try to remove the created obs and create a new one with the same bucket name, changing az policy may not work. Seems the huawei backend reused the config of the older bucket.

You can try run my test script again and again with az policy updating between false and true. It may hit the issue.
In my case, I have created an single az obs during my script development which has kept for several days and switch the az policy to multiple finally for production. The obs was destroied and recreated by terraform automatically.
While the result is that I can never create a multiaz obs with the same bucket name. I think that's the key step lead me hitting such issue.

Below are pictures show strange obs information during my debug. The obs changes its az policy constantly after my applying the terraform several times with az policy updating:
![single](https://user-images.githubusercontent.com/14171017/190191924-6d350fe6-b3b1-417d-91f3-dd4d1e2c4d79.jpg)
![multiaz](https://user-images.githubusercontent.com/14171017/190191953-2a1088e5-8085-4788-ba8f-77bc51472852.jpg)
![none](https://user-images.githubusercontent.com/14171017/190192885-178c0ac5-8c8e-4409-8a5b-68d5b653245b.jpg)

You can see the create time of the obs is the same, only the az policy changed. I guess such strange symptom may also related to the same issue.

**Comment by ShiChangkuo** [comment]
please refer to the notes of [multi_az](https://registry.terraform.io/providers/huaweicloud/huaweicloud/latest/docs/resources/obs_bucket#multi_az)

```
Once a bucket is created, you cannot enable or disable the multi-AZ mode. Changing this will create a new bucket,
but the name of a deleted bucket can be reused for another bucket at least 30 minutes after the deletion.
Exercise caution when changing this field.
```

**Comment by zhenzh** [comment]
Yes. That's the root cause.

**Comment by ShiChangkuo** [comment]
so, it is the behavior of OBS server and the provider can't help you.
