### ISSUE TITLE
ELB 缺少负载均衡器弹性扩缩容开关

### ISSUE THREAD

**Issue by wangheng0206** [huaweicloud/terraform-provider-huaweicloud#2373]
![image](https://user-images.githubusercontent.com/106153788/190043762-1ff2591b-2600-4172-9e83-d1b39b4c01d6.png)

![image](https://user-images.githubusercontent.com/106153788/190043813-fd688497-64ba-4208-9d68-e930b3946b03.png)

**Comment by niuzhenguo** [comment]
I tried the API, but seems not work...
