### ISSUE TITLE
Whether support huaweicloud private cloud platform?

### ISSUE THREAD

**Issue by scarecrow111** [huaweicloud/terraform-provider-huaweicloud#2396]
### Current Terraform Version

```
...
```

**Comment by niuzhenguo** [comment]
no, this is for huawei public cloud.

**Comment by scarecrow111** [comment]
> no, this is for huawei public cloud.

Thanks.

**Comment by int32bit** [comment]
Hi, @niuzhenguo.  We are using Huawei Private Cloud(HCS) 8.20, and will use Terraform to create cloud resources. I find an another project in huaweicloud repo list: https://github.com/huaweicloud/terraform-provider-huaweicloudstack, But it hasn't been updated for 3 years. Is this project still under maintenance? Or is there any other way or provider we can use instead to apply terraform? Thanks.
