### ISSUE TITLE
terraform sdk v2.10.0 会导致测试报错

### ISSUE THREAD

**Issue by xuxiaoahang2018** [huaweicloud/terraform-provider-huaweicloud#2401]
cannot run Terraform provider tests: unexpected Content-Type: "application/vnd+hashicorp.releases-api.v0+json"

换成 v2.16.0后解决:

https://discuss.hashicorp.com/t/cannot-run-terraform-provider-tests-unexpected-content-type-application-vnd-hashicorp-releases-api-v0-json/39643

**Comment by ShiChangkuo** [comment]
@xuxiaoahang2018 请问这个问题如何复现？
