### ISSUE TITLE
Can not create KMS in Beijing -4 Region

### ISSUE THREAD

**Issue by yzp623** [huaweicloud/terraform-provider-huaweicloud#242]
### Terraform Version
Run `terraform -v` to show the version. If you are not running the latest version of Terraform, please upgrade because your issue may have already been fixed.

### Affected Resource(s)
Terraform v0.11.14
+ provider.huaweicloud (unversioned) (Build from least source code)

### Debug Output
Error: Error applying plan:

1 error occurred:
	* huaweicloud_kms_key_v1.ecs-centos-64-key: 1 error occurred:
	* huaweicloud_kms_key_v1.ecs-centos-64-key: Error creating HuaweiCloud kms key client: No suitable endpoint could be found in the service catalog.

`provider "huaweicloud" {
  access_key  = "${var.hw_access_key}"
  secret_key  = "${var.hw_secret_key}"
  region      = "${var.hw_region}"
  tenant_name = "${var.tenant_name}"
  #domain_name = "RTM"
  auth_url    = "https://iam.myhwclouds.com:443/v3"
}

terraform {
  required_version = "= 0.11.14"
}`

`resource "huaweicloud_kms_key_v1" "ecs-centos-64-key" {
  key_alias       = "ecs-centos-64-key"
  #pending_days    = "7"
  #key_description = "ECS access key for CentOS 6.4"
  #realm           = "cn-north-1"
  #is_enabled      = true
}`

**Comment by niuzhenguo** [comment]
@yzp623 That's because the kms endpoint not registered on Cloud side, you can ask help from them instead.

**Comment by yzp623** [comment]
issue can be closed, Since Huawei IAM will register service.
