### ISSUE TITLE
New feature, add data source to ECS instance

### ISSUE THREAD

**Issue by yzp623** [huaweicloud/terraform-provider-huaweicloud#244]
Dear maintainer 

Cloud you add new data source for ECS, to allow get ECS info from terraform?

Best 
Ian

**Comment by niuzhenguo** [comment]
@ShiChangkuo can you help on this?

**Comment by ShiChangkuo** [comment]
@niuzhenguo with my pleasure.

**Comment by ShiChangkuo** [comment]
@yzp623 could you give me more details? like which arguments do you want to query the ECS, and which attributes do you want to get from the ECS.

**Comment by yzp623** [comment]
I would like using instance id to retrieve private ip of this instance

**Comment by ShiChangkuo** [comment]
ok, I got it.

**Comment by niuzhenguo** [comment]
@yzp623 do we still need this?

**Comment by yzp623** [comment]
Thank for support, we can close this
