### ISSUE TITLE
DMS plugin crashed

### ISSUE THREAD

**Issue by gustavocearasc** [huaweicloud/terraform-provider-huaweicloud#2445]
### Terraform Version

```
...
```

### Terraform Configuration Files

resource "huaweicloud_networking_secgroup" "secgroup" {
  name        = var.security_group_name
  description = "terraform security group rabbit"
}

data "huaweicloud_dms_product" "product_1" {
  engine        = "rabbitmq"
  instance_type = "single"
  version       = "3.7.17"
  node_num      = 1
  
}

resource "huaweicloud_dms_rabbitmq_instance" "test" {
  name              = "test-api"
  product_id        = data.huaweicloud_dms_product.product_1.id
  engine_version    = data.huaweicloud_dms_product.product_1.version
  storage_spec_code = data.huaweicloud_dms_product.product_1.storage_spec_code

  vpc_id             = "111111"
  network_id         = "22222"
  security_group_id  = huaweicloud_networking_secgroup.secgroup.id
  availability_zones = ["zone"]

  access_user = "user"
  password    = "pass"

```hcl
...
```

### Additional Context
when I try to create the object , It returned the msg error
Stack trace from the terraform-provider-huaweicloud_v1.41.1 plugin:

panic: runtime error: index out of range [0] with length 0

goroutine 31 [running]:
github.com/huaweicloud/terraform-provider-huaweicloud/huaweicloud/services/dms.resourceDmsRabbitmqInstanceCreate({0x1de4748, 0xc0002d2c60}, 0x180eb00?, {0x1af9940?, 0xc000d33400})
    github.com/huaweicloud/terraform-provider-huaweicloud/huaweicloud/services/dms/resource_huaweicloud_dms_rabbitmq_instance.go:259 +0x12ef
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).create(0xc0005f6ee0, {0x1de46d8, 0xc00024d4c0}, 0x2?, {0x1af9940, 0xc000d33400})
    github.com/hashicorp/terraform-plugin-sdk/v2@v2.10.0/helper/schema/resource.go:341 +0x12e
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc0005f6ee0, {0x1de46d8, 0xc00024d4c0}, 0xc000df4820, 0xc0000ce400, {0x1af9940, 0xc000d33400})
    github.com/hashicorp/terraform-plugin-sdk/v2@v2.10.0/helper/schema/resource.go:467 +0x705
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc000010288, {0x1de46d8, 0xc00024d4c0}, 0xc0010265f0)
    github.com/hashicorp/terraform-plugin-sdk/v2@v2.10.0/helper/schema/grpc_provider.go:977 +0xde5
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ApplyResourceChange(0xc00012ae00, {0x1de4780?, 0xc00101c360?}, 0xc00100c000)
    github.com/hashicorp/terraform-plugin-go@v0.5.0/tfprotov5/tf5server/server.go:603 +0x2ad
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0x1a70b60?, 0xc00012ae00}, {0x1de4780, 0xc00101c360}, 0xc0002d2060, 0x0)
    github.com/hashicorp/terraform-plugin-go@v0.5.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:380 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc00020ddc0, {0x1de87b8, 0xc00082ec00}, 0xc00026e100, 0xc000acdfb0, 0x2ae4fc0, 0x0)
    google.golang.org/grpc@v1.32.0/server.go:1194 +0xcab
google.golang.org/grpc.(*Server).handleStream(0xc00020ddc0, {0x1de87b8, 0xc00082ec00}, 0xc00026e100, 0x0)
    google.golang.org/grpc@v1.32.0/server.go:1517 +0xa2f
google.golang.org/grpc.(*Server).serveStreams.func1.2()
    google.golang.org/grpc@v1.32.0/server.go:859 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
    google.golang.org/grpc@v1.32.0/server.go:857 +0x28a

Error: The terraform-provider-huaweicloud_v1.41.1 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.

**Comment by chengxiangdong** [comment]
The product query API is offline. 
I will fix this issues by replacing another API.

**Comment by gustavocearasc** [comment]
Thank you for your answer.

I will wait for it.
