### ISSUE TITLE
request to new feature, add RDS V3 API support for terraform. 

### ISSUE THREAD

**Issue by yzp623** [huaweicloud/terraform-provider-huaweicloud#245]
Dear all

Since Huawei RDS v1 API will depreciated soon. Cloud you add support to RDS V3 support? 

https://support.huaweicloud.com/api-rds/zh-cn_topic_0032347782.html
https://support.huaweicloud.com/api-rds/rds_06_0002.html
 
Thanks in advance

**Comment by yzp623** [comment]
KMS encrypted database is needed

**Comment by niuzhenguo** [comment]
@ShiChangkuo please help on this.

**Comment by ShiChangkuo** [comment]
I'll handle it, and please review the referenced RP, thanks.

**Comment by niuzhenguo** [comment]
closed by #248
