### ISSUE TITLE
request to add new feature, associate eip to Enhanced load balancer

### ISSUE THREAD

**Issue by yzp623** [huaweicloud/terraform-provider-huaweicloud#246]
Hi all 

I do not find a way to associate EIP to Enhanced load balancer. 
is there any way to do that? 

Best

**Comment by niuzhenguo** [comment]
@yzp623 You can use networking_floatingip_associate resource to bind eip and elb vip_port_id.
https://www.terraform.io/docs/providers/huaweicloud/r/networking_floatingip_associate_v2.html

**Comment by yzp623** [comment]
working perfectly, Thanks
