### ISSUE TITLE
[IAM] Both encrypted_secret and secret references of huaweicloud_identity_access_key are empty

### ISSUE THREAD

**Issue by zhenzh** [huaweicloud/terraform-provider-huaweicloud#2461]
I can now only read the secret key by specifying secret_file to a temporary local file.

Is there a method to provide generated secret key without storing it to local file which may lead to additional security concern.

**Comment by ShiChangkuo** [comment]
@zhenzh sorry for the delay.

the `secret` is not empty only when writing to `secret_file` failed, so you can set **secret_file** in a nonexistent dir, e.g. /aaa/bbb/ccc.csv. --- you can find the `secret` in state file with plaint text.

the `encrypted_secret` is not empty only when you specified [pgp_key](https://registry.terraform.io/providers/huaweicloud/huaweicloud/latest/docs/resources/identity_access_key#pgp_key).

**Comment by zhenzh** [comment]
setting secret_file to a nonexistent dir will get the terraform exit with error
`Error: Error saving the access key to null/obs-aksk.csv: open null/obs-aksk.csv: no such file or directory`

**Comment by ShiChangkuo** [comment]
I will downgrade the level to warning, then terraform can continue running.
