### ISSUE TITLE
AS group Instance number can not update after changing as-group desire/min/max_instance_number

### ISSUE THREAD

**Issue by yzp623** [huaweicloud/terraform-provider-huaweicloud#247]
### Terraform Version
Terraform v0.11.14

### Affected Resource(s)
huaweicloud_as_group_v1

AS group created  with following config
  desire_instance_number   = 1
  min_instance_number      =  1
  max_instance_number      = 2

After AS group creation now modified AS group config as following

`resource "huaweicloud_as_group_v1" "api-gateway-as-group" {
  scaling_group_name       = "**************"
  scaling_configuration_id = "*****************"
  desire_instance_number   = "0"
  min_instance_number      = "0"
  max_instance_number      = "0"
  networks                 = [{ id = "***************"}]
  security_groups          = [{ id = "******************"}]
  vpc_id                   = "*****************}"
  delete_publicip          = true
  delete_instances         = "yes"
}`

Change
  desire_instance_number   = change from 1 to 0
  min_instance_number      =  change from 1 to 0
  max_instance_number      = change from 2 to 0

### Expected Behavior
AS group config in Huawei Web portal will change accordingly 

### Actual Behavior
nothing changed
no error message, terraform message show apply complete
terraform message : 

`huaweicloud_as_group_v1.web_portal_as_group: Modifying... (ID: *********************)
  desire_instance_number: "1" => "0"
  instances.#:            "1" => "0"
  instances.0:            "*********************" => ""
  min_instance_number:    "1" => "0"
huaweicloud_as_group_v1.web_portal_as_group: Modifications complete after 2s 
Apply complete! Resources: 0 added, 2 changed, 0 destroyed.
`

**Comment by ShiChangkuo** [comment]
@yzp623 thanks for reporting, it does seem like a program bug, and I'll fix it asap.
