### ISSUE TITLE
Secgroup deletion fails if has any ECSes

### ISSUE THREAD

**Issue by aaovchinnikov** [huaweicloud/terraform-provider-huaweicloud#2481]
Hi there,

All along the usage of this terraform provider deletion of secgroup resource stuck if secgroup was attached to ECS. First terraform tries to delete secgroup and then adjust ECS parameters, but fails. Thus secgroup deletion should be performed in two steps - remove ECSes from secgroup membership, and then remove secgroup itself

It would be nice to change the order of operations: adjust ECS parameters (remove secgroup membership) and then remove secgroup - to have single terraform apply instead of two as for now

**Comment by aaovchinnikov** [comment]
Maybe its reasonable to move membership of ECSes in secgroups declaration from ECS to SG declaration, as it's done via secgroup WebUI in cloud console

**Comment by ShiChangkuo** [comment]
@aaovchinnikov the provider can not control the order of steps, maybe you can open an issue in Terraform.

**Comment by ShiChangkuo** [comment]
@aaovchinnikov I will close it temporarily, If you have any questions, please reopen it. Thanks.
