### ISSUE TITLE
[CCE NodePool]节点池创建，缺少包年包月、安全组设置功能

### ISSUE THREAD

**Issue by wangheng0206** [huaweicloud/terraform-provider-huaweicloud#2505]
why not use billingmode value?

![image](https://user-images.githubusercontent.com/106153788/200736608-77d56300-1799-4fe2-9ab8-926861aba5c3.png)

![image](https://user-images.githubusercontent.com/106153788/200494078-f57ad4b3-dad0-4cfa-a380-a62c702ab263.png)

![image](https://user-images.githubusercontent.com/106153788/200494028-205f101e-b0d5-43de-a00b-6a766f7c1800.png)

![image](https://user-images.githubusercontent.com/106153788/200492094-0f3c6d9e-3c23-498a-ba2d-646cf1602d6e.png)

![image](https://user-images.githubusercontent.com/106153788/200492005-0883f8f3-a64d-4698-94d1-7afa62e377cb.png)

**Comment by ShiChangkuo** [comment]
fixed by #2526 #2534
