### ISSUE TITLE
[Node Pool] charging_mode is invalid 节点池支持包年包月并未成功修复，请悉知

### ISSUE THREAD

**Issue by wangheng0206** [huaweicloud/terraform-provider-huaweicloud#2568]
its my terraform config 

![image](https://user-images.githubusercontent.com/106153788/205608839-8cf4aa05-eb3e-4888-a3df-de99d0c7ac4b.png)

but its result

![image](https://user-images.githubusercontent.com/106153788/205608717-fa75f442-516f-43f7-957f-6e3d97f5081d.png)

![image](https://user-images.githubusercontent.com/106153788/205609154-5d0f392b-5a43-482f-9be8-04ddc5115ecc.png)

**Comment by niuzhenguo** [comment]
这个会在1.45版本修复，今天的版本。但是退订需要手动去退，因为API不支持。
