### ISSUE TITLE
使用terraform创建安全组deny规则失败

### ISSUE THREAD

**Issue by likuan222222** [huaweicloud/terraform-provider-huaweicloud#2581]
### Current Terraform Version
Terraform v1.3.6
provider  huaweicloud v1.43.0

默认创建安全组规则是allow,在定义deny的时候报错，terraform脚本如下：
![image](https://user-images.githubusercontent.com/32713694/207225150-b2504f7b-9307-4037-bf61-3ba5fcfb611f.png)
报错信息如下：
![image](https://user-images.githubusercontent.com/32713694/207225230-a7e706d9-682b-468d-8999-a399ff7d17fe.png)

**Comment by Lance52259** [comment]
please use `ports` instead of the `port_range_max` and `port_range_min`.

**Comment by ShiChangkuo** [comment]
@likuan222222 I will close it temporarily, If you have any questions, please reopen it. Thanks.
