### ISSUE TITLE
"description" argument in huaweicloud_identity_user_v3 rejected by the provider

### ISSUE THREAD

**Issue by thiagoeh** [huaweicloud/terraform-provider-huaweicloud#262]
I was able to sucessfully create an IAM user using the resource huaweicloud_identity_user_v3.
When I add the "description" argument it is rejected with this message:
```
Error: Unsupported argument

  on iam_users.tf line 5, in resource "huaweicloud_identity_user_v3" "user_1":
   5:   description = "A user created with TF"

An argument named "description" is not expected here.
```

Version:
```
$ terraform -v
Terraform v0.12.19
+ provider.huaweicloud v1.12.0
```

Resource definition:
```
resource "huaweicloud_identity_user_v3" "user_1" {
  name        = "user_1_tf"
  description = "A user created with TF"
  password    = "password123!"
}
```
### Expected Behavior
Set the IAM user description

### Actual Behavior
Error message informing that the "description" parameter is unsupported.

**Comment by ShiChangkuo** [comment]
@thiagoeh thanks for raising this. The `description` argument is missing, and I'll fix it soon.
