### ISSUE TITLE
No parameter to set metadata (tags) in resource huaweicloud_s3_bucket

### ISSUE THREAD

**Issue by thiagoeh** [huaweicloud/terraform-provider-huaweicloud#263]
### Terraform Version
```
$ terraform -v
Terraform v0.12.19
+ provider.huaweicloud v1.12.0
```

### Affected Resource
- huaweicloud_s3_bucket

### Expected Behavior
Be able to define tags for the S3 bucket.
In the example code it was used the same syntax from the OpenStack Terraform provider

### Actual Behavior
There is no parameter to set S3 bucket tags

### Terraform Configuration Files
```hcl
resource "huaweicloud_s3_bucket" "b" {
  bucket = "my-tf-test-bucket"
  acl    = "private"

  metadata {
      key1 = "value1"
  }
}
```

### References
https://www.terraform.io/docs/providers/openstack/r/objectstorage_container_v1.html#metadata

**Comment by ShiChangkuo** [comment]
@thiagoeh we add `tags` parameter in huaweicloud_s3_bucket, and the usage example as follows:
```
resource "huaweicloud_s3_bucket" "b" {
  bucket = "my-tf-test-bucket"
  acl    = "private"

  tags {
      key1 = "value1"
  }
}
```
