### ISSUE TITLE
Assigning role to UserGroup for All projects

### ISSUE THREAD

**Issue by mikhailzakhryapin** [huaweicloud/terraform-provider-huaweicloud#2654]
### Current Terraform Version
1.3.7

### Use-cases
I have deployed a Role and User Group using Terraform. I would like to assign a Role to User Group in all current and future Projects using Terraform. According to [documentation](https://registry.tfpla.net/providers/huaweicloud/huaweicloud/latest/docs/resources/identity_role_assignment) I can only specify a particular project. The Role is project level (ECS management).

resource "huaweicloud_identity_role_assignment" "role_assignment_1" {
  role_id    = data.huaweicloud_identity_role.role_1.id
  group_id   = huaweicloud_identity_group.group_1.id
  project_id = var.project_id
}

### Attempted Solutions
If I do not specify project_id and only specify domain_id the Role is assigned in Global region and does not work.

### Proposal
Add possibility to assign Role to all current and future Projects

**Comment by ShiChangkuo** [comment]
@mikhailzakhryapin have you try [Assign Role On Domain Level](https://registry.tfpla.net/providers/huaweicloud/huaweicloud/latest/docs/resources/identity_role_assignment#example-usage-assign-role-on-domain-level) ?

**Comment by mikhailzakhryapin** [comment]
Yes, we tried it but it did not work
