### ISSUE TITLE
Autoscaler addon installation problem with terraform

### ISSUE THREAD

**Issue by owenJiao** [huaweicloud/terraform-provider-huaweicloud#2655]
Hi, Team.

I got a problem when I installed the autoscaler addon with terraform,  the pod of autoscaler has been restarting and can't run normally. But if I installed this addon in huawei console, pod can run well.  I don't know if I missed some key parameters , Could you help to fix this problem?

1) ENV
   K8s cluster:  cce_turbo
   huawei-terraform-provider version: 1.42.0

2) Autoscaler addon configuration:
   data "huaweicloud_cce_addon_template" "autoscaler" {
          cluster_id = huaweicloud_cce_cluster.cce_turbo.id
          name       = local.autoscaler_name
          version    = var.autoscaler_version (1.23.10)
   }
   resource "huaweicloud_cce_addon" "autoscaler" {
       depends_on = [
           resource.huaweicloud_cce_node_pool.node_pool
       ]
      cluster_id    = huaweicloud_cce_cluster.cce_turbo.id
      template_name = data.huaweicloud_cce_addon_template.autoscaler.name
      version       = data.huaweicloud_cce_addon_template.autoscaler.version
      values {
            basic_json = jsonencode(jsondecode(data.huaweicloud_cce_addon_template.autoscaler.spec).basic)
            custom_json = jsonencode(
                merge(
                     jsondecode(data.huaweicloud_cce_addon_template.autoscaler.spec).parameters.custom,
                     {
                             cluster_id       = huaweicloud_cce_cluster.cce_turbo.id
                             tenant_id        = data.huaweicloud_identity_projects.project.id
                     }
               )
          )
          flavor_json = jsonencode(jsondecode(data.huaweicloud_cce_addon_template.autoscaler.spec).parameters.flavor1)
  }
}

3)  Error output of this pod.
    hws_manager.go:196] Failed to fresh cluster information: Unexpected Response error, StatusCode: 401, Error Message: {"error_msg":"Incorrect IAM authentication information: get token error,status:400","error_code":"APIGW.0301","request_id":"c82ac8fdaecb63228753b70863036cfe"}
E0115 14:38:55.433087       1 hws_manager.go:200] Failed to fresh node group cache: Unexpected Response error, StatusCode: 401, Error Message: {"error_msg":"Incorrect IAM authentication information: get token error,status:400","error_code":"APIGW.0301","request_id":"9e80e214ab9527f860336ac4558364b8"}
F0115 14:38:55.433102       1 hws_cloud_provider.go:154] Failed to create HWS Manager: Unexpected Response error, StatusCode: 401, Error Message: {"error_msg":"Incorrect IAM authentication information: get token error,status:400","error_code":"APIGW.0301","request_id":"9e80e214ab9527f860336ac4558364b8"}

4) Expect
  Hope the defect can be fixed, thanks.

**Comment by ShiChangkuo** [comment]
same as #3276
