### ISSUE TITLE
The data source of VPC and Subnet can't support tags filter with terraform

### ISSUE THREAD

**Issue by owenJiao** [huaweicloud/terraform-provider-huaweicloud#2658]
As the title says, When I wanted to use data source of VPC and Subnet with tag filter to query an existing VPC and Subnet. Terraform threw some errors like below image.
![image](https://user-images.githubusercontent.com/35132388/212637188-e13cbce3-dc6c-4f1b-81e9-5e701ea91957.png)

**Comment by ShiChangkuo** [comment]
@owenJiao sorry for the delay, the type of `tags` is  Map, we should use is like this

```hcl
data "huaweicloud_vpc_subnets" "by_tag" {
  status = "ACTIVE"
  tags = {
    key = "value"
  }
}
```

I will update the examples in docs.
