### ISSUE TITLE
[EVS] volume should be replaced by new resource when shrinking operation is requested 

### ISSUE THREAD

**Issue by zhenzh** [huaweicloud/terraform-provider-huaweicloud#2746]
When shrinking evs, below error message is reported.

{"error":{"message":"new volume Size must be greater than old Size!","code":"EVS.1015"}}

Since evs doesn't support shrinking operation, the provider should do resource replacing operation, rather than trying sending incorrect command and return error message.

**Comment by niuzhenguo** [comment]
it's not possible as we can only set the size parameter ForceNew or not under Terraform framework. You can't make shrinking forcenew and expanding not :(

**Comment by zhenzh** [comment]
But such feature used to work befor v1.41

**Comment by niuzhenguo** [comment]
> But such feature used to work befor v1.41

I just checked the code before v1.41, the size parameter is not with ForceNew, can you show your `terraform plan` for shrinking?

**Comment by zhenzh** [comment]
Neither can I reproduce the replacing operation with lower version. Maybe got confused with other cloud provider.

Back to the technicality, is it possible to overwrite some parameter at the beginning of terraform apply, so that size parameter can be update based on the result of resource state refershing?

**Comment by niuzhenguo** [comment]
> 

not possible, do you remember which cloud provider has the ability, I can check how they make this.

**Comment by zhenzh** [comment]
I forget where I hit such case. Will let you know once I find it.

**Comment by ShiChangkuo** [comment]
I will close it temporarily, If you have found a problem that seems similar to this, please open a new issue and complete the issue template so we can capture all the details necessary to investigate further.
