### ISSUE TITLE
[OBS] Add support to configure event notifications for bucket objects

### ISSUE THREAD

**Issue by bolzon** [huaweicloud/terraform-provider-huaweicloud#2763]
### Terraform Version

This is the Terraform version I'm currently using:

```
Terraform v1.3.9
on linux_amd64
```

### Use cases

- Provider should provide a way to configure event notifications  for objects that are created or removed from a OBS bucket.
- Notification method should support at least SMN topics.
- Support to DMS queues is also much appreciated, if possible.

So far I couldn't found any option to achieve that via Huawei Cloud provider, but if there's any, I appreciate any help.

### Attempted solutions

- Faster and simpler solution is to configure those triggers manually in the console.
- It's also possible to use the Huawei Cloud APIs to achieve that, although it requires more effort.

### Proposal

- It could use a layout similar to [huaweicloud_fgs_trigger](https://registry.terraform.io/providers/huaweicloud/huaweicloud/latest/docs/resources/fgs_trigger).

### References

- #1215

**Comment by ShiChangkuo** [comment]
@bolzon [Event notifications](https://support.huaweicloud.com/intl/en-us/ugobs-obs/obs_41_0045.html) have been taken **offline**. If you have any questions, please submit a service ticket.

BTW, you can use an OBS trigger to send a SMN message.

**Comment by bolzon** [comment]
@ShiChangkuo thanks for the quick response.

Could you please point me out which Terraform resource I could use to configure an OBS trigger to send a SMN message?

Appreciate any help.

**Comment by ShiChangkuo** [comment]
First you can use `huaweicloud_smn_topic` and `huaweicloud_smn_subscription` to create a SMN, then you can use `huaweicloud_fgs_function` to send the SMN message. Finally, you can use `huaweicloud_fgs_trigger` to trigger the OBS event.

you can try it by console

**Comment by bolzon** [comment]
@ShiChangkuo yea, I'm aware of those.

Any option to configure this OBS > SMN trigger without the need of a Function Graph?

Asking because the region I'm working on doesn't have this service available.

Thanks.

**Comment by bolzon** [comment]
FGS trigger now is available in the region I'm using, so closing this ticket.
