### ISSUE TITLE
[CCE Node Pool] 缺少关联安全组

### ISSUE THREAD

**Issue by wangheng0206** [huaweicloud/terraform-provider-huaweicloud#2779]
### Terraform Version

```
terraform {
  required_providers {
    huaweicloud = {
      source = "huaweicloud/huaweicloud"
      version = "1.45.0"
    }
  }
}
```

### Terraform Configuration Files

![image](https://user-images.githubusercontent.com/106153788/224210273-b1952940-b461-4407-9963-dde1655a96b1.png)

### Debug Output

![image](https://user-images.githubusercontent.com/106153788/224210359-3de7974c-f850-4a5b-96d8-52214e8f622f.png)

缺少关联安全组
![image](https://user-images.githubusercontent.com/106153788/224210403-7c4e3e47-887a-4e85-9e48-d0221d444db4.png)

**Comment by niuzhenguo** [comment]
是说TF缺少关联安全组这个属性吗？

**Comment by ShiChangkuo** [comment]
@wangheng0206 该特性已经在1.46.0版本中支持 https://registry.terraform.io/providers/huaweicloud/huaweicloud/latest/docs/resources/cce_node_pool#security_groups
