### ISSUE TITLE
[ELB]  The output of ELB doesn't have id attribute

### ISSUE THREAD

**Issue by owenJiao** [huaweicloud/terraform-provider-huaweicloud#2837]
Hi, Team.
    As the title, When I use terraform to provision the ingress controller in CCE ,  I need to bind an ELB to the ingress service with loadbalance  type to make it can be accessed by internet . If I do that,  the id of ELB is required (please reference this link for details : https://support.huaweicloud.com/usermanual-cce/cce_10_0014.html), but I didn't get the id of ELB,  is this a bug or by design? Could you help me fix it? Thanks a lot.

**Comment by niuzhenguo** [comment]
What do you mean the id of ELB? We do have resource id attribute.

**Comment by owenJiao** [comment]
I upload the screenshot which is the error I encountered. I can't get resource id from ELB output.
<img width="858" alt="截屏2023-03-22 上午10 06 35" src="https://user-images.githubusercontent.com/35132388/226789514-74fdce67-4303-4cb9-8e25-0cb7fd862681.png">

**Comment by niuzhenguo** [comment]
you need to paste the screenshot of your elb output for id within the module.

**Comment by owenJiao** [comment]
Awkwardly, it's my fault，so close.
