### ISSUE TITLE
[CCE nginx-ingress addon] can't work in terraform

### ISSUE THREAD

**Issue by owenJiao** [huaweicloud/terraform-provider-huaweicloud#2862]
Hi, Team.
I encountered a problem when I used terraform to create one addon of CCE whose name is nginx-ingress. but it didn't work as expected. The error message please see the screenshot below.  which says "It can't get addon templates  of CCE from data resource"... But I could get the addon templates of CCE by rest api that provide by huawei .  So could you help me fix it, Thanks. 
<img width="1440" alt="截屏2023-03-27 下午3 30 40" src="https://user-images.githubusercontent.com/35132388/227877589-23cba23a-72c3-48ef-954a-86e4663861e0.png">

**Comment by niuzhenguo** [comment]
This is not related to terraform but the certificate of CCE service is not valid.
You can try to add insecure=true in you provider configuration like https://registry.terraform.io/providers/huaweicloud/huaweicloud/latest/docs#insecure

**Comment by owenJiao** [comment]
I ran the same terraform script but on different region, which got the different result. On region cn-north-4, where I got the error as above said, but on region cn-east-3, it worked well as expected. I don't know why, so strange...
Moreover, I couldn't  set insecure=true in my provider config.

**Comment by niuzhenguo** [comment]
That's certificate issue, you can create a ticket to CCE service for this.

**Comment by owenJiao** [comment]
OK. Thanks a lot for your reply, so close this issue.
