### ISSUE TITLE
[LB] 共享LB开启公网的情况下，监听器开启健康检查成功，但主机显示健康检查未开启。

### ISSUE THREAD

**Issue by wangheng0206** [huaweicloud/terraform-provider-huaweicloud#2863]
### Terraform Version

```
terraform {
  required_providers {
    huaweicloud = {
      source  = "huaweicloud/huaweicloud"
      version = "1.45.0"
    }
  }
}


```

### Terraform Configuration Files

```hcl
 + resource "huaweicloud_lb_monitor" "monitor_tcp" {
      + admin_state_up = true
      + delay          = 5
      + expected_codes = (known after apply)
      + http_method    = (known after apply)
      + id             = (known after apply)
      + max_retries    = 3
      + pool_id        = (known after apply)
      + port           = 80
      + region         = (known after apply)
      + tenant_id      = (known after apply)
      + timeout        = 3
      + type           = "TCP"
      + url_path       = (known after apply)
    }
```

### Debug Output

![image](https://user-images.githubusercontent.com/106153788/227892935-fd05e70c-f169-47d9-a9cb-5ebffc67072f.png)
![image](https://user-images.githubusercontent.com/106153788/227893138-f82947a0-7b4d-4939-a518-dc0ae2a4edd2.png)

**Comment by wangheng0206** [comment]
内网情况下正常，仅LB绑定EIP有问题

# module.huaweicloud_elb_loadbalancer.huaweicloud_lb_loadbalancer.elb will be created
  + resource "huaweicloud_lb_loadbalancer" "elb" {
      + admin_state_up        = true
      + enterprise_project_id = "0"
      + id                    = (known after apply)
      + loadbalancer_provider = (known after apply)
      + name                  = "lb-hw-terraform-test"
      + region                = (known after apply)
      + security_group_ids    = (known after apply)
      + tenant_id             = (known after apply)
      + vip_address           = (known after apply)
      + vip_port_id           = (known after apply)
      + vip_subnet_id         = "xxx"
    }

  # module.huaweicloud_vpc_eip.huaweicloud_vpc_eip.eip will be created
  + resource "huaweicloud_vpc_eip" "eip" {
      + address               = (known after apply)
      + charging_mode         = (known after apply)
      + enterprise_project_id = "0"
      + id                    = (known after apply)
      + ipv6_address          = (known after apply)
      + name                  = "lb-hw-terraform-test-eip"
      + port_id               = (known after apply)
      + private_ip            = (known after apply)
      + region                = (known after apply)
      + status                = (known after apply)

      + bandwidth {
          + charge_mode = "traffic"
          + id          = (known after apply)
          + name        = "lb-hw-terraform-test-eip-bandwidth"
          + share_type  = "PER"
          + size        = 200
        }

      + publicip {
          + ip_address = (known after apply)
          + ip_version = (known after apply)
          + port_id    = (known after apply)
          + type       = "5_bgp"
        }
    }

+ resource "huaweicloud_vpc_eip_associate" "associated" {
      + fixed_ip    = (known after apply)
      + id          = (known after apply)
      + mac_address = (known after apply)
      + network_id  = (known after apply)
      + port_id     = (known after apply)
      + public_ip   = (known after apply)
      + region      = (known after apply)
      + status      = (known after apply)
    }

**Comment by niuzhenguo** [comment]
功能正常吗？这个可能是服务的问题，接口调用成功但是和console没有同步

**Comment by wangheng0206** [comment]
> 功能正常吗？这个可能是服务的问题，接口调用成功但是和console没有同步

其他功能正常，但是进到官网主机显示健康检查未开启。能否修复下。

**Comment by niuzhenguo** [comment]
这个要找云服务看一下，不是Terraform的问题哈

**Comment by ShiChangkuo** [comment]
I will close it temporarily, If you have any questions, please reopen it. Thanks.
