### ISSUE TITLE
huaweicloud_obs_bucket creation fails with internal plugin error

### ISSUE THREAD

**Issue by thiagoeh** [huaweicloud/terraform-provider-huaweicloud#288]
### Terraform Version
```
$ terraform -v
Terraform v0.12.24
+ provider.huaweicloud v1.13.0
```

### Affected Resource(s)
- huaweicloud_obs_bucket

### Terraform Configuration Files
Authentication information set through OS_* variables. It works with other resources types.

Region is ap-southeast-1.

```hcl
provider "huaweicloud" {
}

resource "huaweicloud_obs_bucket" "bucket" {
  bucket        = "my-super-duper-bucket"
}
```

### Debug Output
https://gist.github.com/thiagoeh/f2dd887fcf8238ec81e00ad0a456e82c

### Expected Behavior
Create the OBS bucket.

### Actual Behavior
Fails with error

`[DEBUG] plugin: plugin exited
 Reason: We encountered an internal error. Please try again.`

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

**Comment by ShiChangkuo** [comment]
@thiagoeh, I tested well in `cn-north-1` region and encounter the same error in `ap-southeast-1` region.
The issue  maybe raise from the api side, you can create a service ticket on huaweicloud.

**Comment by ShiChangkuo** [comment]
@thiagoeh After discussing with my colleagues, this issue is caused by missing a parameter when creating an obs bucket. I'll fix it soon.
