### ISSUE TITLE
rpc error: code = Unavailable desc = transport is closing

### ISSUE THREAD

**Issue by bigmule** [huaweicloud/terraform-provider-huaweicloud#298]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### Terraform Version
Terraform version: 0.12.24
Go runtime version: go1.13.8
provider.huaweicloud: version = "~> 1.13"

### Affected Resource(s)
Please list the resources :
- huaweicloud_vpc_v1

Same error when running terraform plan and terraform apply

### Terraform Configuration Files
```
provider "huaweicloud" {
  token = ""
  tenant_name = ""
  region = ""
  auth_url = ""
}

data "huaweicloud_vpc_v1" "vpc" {
  id = "eb30e056-c39c-466a-9e2f-a75abbc1a23c"
}
```

### Panic Output
If Terraform produced a panic, please provide a link to a GitHub Gist containing the output of the `crash.log`.

### Expected Behavior
Should execute without errors

### Actual Behavior
panic: runtime error: invalid memory address or nil pointer dereference

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

[crash.log](https://github.com/terraform-providers/terraform-provider-huaweicloud/files/4434382/crash.log)

**Comment by ShiChangkuo** [comment]
@bigmule Thanks for raising, the crash is caused by nil vpc client. Checking the configuration of provider will be better.

BTW, we will add some judgement to avoid crashing.
