### ISSUE TITLE
huaweicloud_elb_loadbalancer using obsolete API version

### ISSUE THREAD

**Issue by thiagoeh** [huaweicloud/terraform-provider-huaweicloud#302]
I was able to sucessfully provision huaweicloud_elb_loadbalancer in sa-brazil-1 region, but the same template fail in ap-southeast-1 region.

It appears that the provider is using an obsolete API, that is still available in sa-brazil-1, but not in ap-southeast-1.

### Terraform Version
```
$ terraform -v
Terraform v0.12.24
+ provider.huaweicloud v1.13.0
```
### Affected Resource(s)
- huaweicloud_elb_loadbalancer

### Terraform Configuration Files
```hcl
resource "huaweicloud_elb_loadbalancer" "elb-asg-app-example" {
  name           = "elb-asg-app-example"
  type           = "External"
  description    = "ELB for ASG APP Example"
  vpc_id         = var.vpc_id
  admin_state_up = 1
  bandwidth      = 5
}
```
Full template available at https://github.com/thiagoeh/hwc-as-stress/tree/b009d90c181b7cb5086b85b22e1d496d920c5d3e

### Actual Behavior
```
$ terraform apply -auto-approve
REDACTED

huaweicloud_elb_loadbalancer.elb-asg-app-example: Creating...

Error: Error creating ELB-LoadBalancer: Resource not found: [POST https://elb.ap-southeast-1.myhuaweicloud.com/v1.0/077e5215b980251b2fecc014ddcaf63a/elbaas/loadbalancers], error message: {"error_msg":"The API does not exist or has not been published in the environment","error_code":"APIGW.0101","request_id":"2353a1958c5b2345d7da99cc129b9e9f"}
```

### References
https://support.huaweicloud.com/intl/en-us/api-elb/en-us_topic_0096561535.html

**Comment by ShiChangkuo** [comment]
@thiagoeh the huaweicloud_elb_loadbalancer resource is not recommended now, you can try `huaweicloud_lb_loadbalancer_v2` which will  provision an enhanced ELB within HuaweiCloud.
