### ISSUE TITLE
 No suitable endpoint could be found 

### ISSUE THREAD

**Issue by Aram1X** [huaweicloud/terraform-provider-huaweicloud#312]
Hello
Found an issue with terraform:
Here is code:
(base) Peters-MacBook-Pro:IAM peterp$ cat main.tf

# Configure the SberCloud Provider

provider "huaweicloud" {

  user_id     = var.user_id

  tenant_id   = var.tenant_id

  password    = var.password

 

  region      = "ru-moscow-1"

  auth_url    = "https://iam.ru-moscow-1.hc.sbercloud.ru/v3"

}

 

# Define user resource

resource "huaweicloud_identity_user_v3" "user_terra_01" {

  name        = "Terra"

  description = "User to test Terraform"

}

(base) Peters-MacBook-Pro:IAM peterp$

 
Here what I receive when apply it:

(base) Peters-MacBook-Pro:IAM peterp$ ./terraform import huaweicloud_identity_user_v3.user_terra_01 087c6640ab00240b1fc4c007799fec69

huaweicloud_identity_user_v3.user_terra_01: Importing from ID "087c6640ab00240b1fc4c007799fec69"...

huaweicloud_identity_user_v3.user_terra_01: Import prepared!

  Prepared huaweicloud_identity_user_v3 for import

huaweicloud_identity_user_v3.user_terra_01: Refreshing state... [id=087c6640ab00240b1fc4c007799fec69]

 

Error: Error creating HuaweiCloud identity client: No suitable endpoint could be found in the service catalog.

 

(base) Peters-MacBook-Pro:IAM peterp$

**Comment by niuzhenguo** [comment]
@Aram1X "No suitable endpoint" is a server side issue instead of terraform, that's because they didn't register the corresponding endpoint to the service catalog.

**Comment by ShiChangkuo** [comment]
@Aram1X there are some differences between huaweicloud and sbercloud on the service catalog. 
For example, some services (**dns**, **iam**) were registered as global in huaweicloud, while they were  registered as regional in sbercloud.

**Comment by Aram1X** [comment]
could you please explain more detailed? where failure is located? suggestion how to fix? How can i find this service catalog?

**Comment by niuzhenguo** [comment]
@Aram1X You should create a request to the SberCloud side instead of here. We don't have such issue for Huawei Cloud.

**Comment by ghost** [comment]
Guys, I've just tried the simplest possible terraform script in my global Huawei cloud account and got the same error. Here is the script:

```
provider "huaweicloud" {
  user_id       = "<my ID>"
  password      = "<my password>"
  tenant_id     = "<my region project ID here>"
  region        = "ap-southeast-1"
  auth_url      = "https://iam.ap-southeast-1.myhwclouds.com:443/v3"
}


resource "huaweicloud_identity_user_v3" "user01" {
  name        = "user01"
  description = "User to test Terraform"
}
```
You could see the region from the settings.
`terraform plan` shows that 1 user will be created while `terraform apply` fails with error.
What may be wrong in my settings? Maybe some endpoint informatoin missed?

**Comment by niuzhenguo** [comment]
@pavel-kutakov-at-huawei you also got "No suitable endpoint"? we need a domain_name/domain_id as well if using iam resouces. But seems there's someting wrong when using user_id with domain_id, please use the name of them instead.

**Comment by ghost** [comment]
Yes, I also go "No sutable endpoint". As you can see from the script, there is no "domain_name" or "domain_id" at all. But to be honest, I still do not understand what is "domain" in terms of Huaweicloud provider. I don't have any "domains" in my cloud console, neither in "My credentials" page where I can find my "User ID" nor in "IAM" page.
Let's make this very simple example working...

**Comment by niuzhenguo** [comment]
@pavel-kutakov-at-huawei Please check out this https://github.com/terraform-providers/terraform-provider-huaweicloud/blob/master/website/docs/index.html.markdown

**Comment by ghost** [comment]
@niuzhenguo Thank you very much, so "domain_name" equals to account name. After changing "user_id" to "user_name" and adding "domain_name" my script finally working with ap-southeast-1 region. Unfortunately it still not working with SbC cloud, but it seems to be a different story. 
Thank you very much again!

**Comment by niuzhenguo** [comment]
@pavel-kutakov-at-huawei We will also make auth_url default to Huawei Cloud IAM url to make the provider configuration easier, which may be also not friendly to SbC :( . I would suggest creating a separate provider for SbC.

**Comment by messimovich** [comment]
Hi Guys,
The error that you are facing with "No suitable endpoint found" is most probably related to the fact that your IAM related APIs have region and region_id values set to region name instead of "*".

Please check the configuration of endpoints with following attributes and set the region and region_id to "*" for them so that your terraform huaweicloud_identity_user_v3 will be able to find endpoints.
               "name": "iam",
               "type": "iam"
and 

                "name": "keystone",
                "type": "identity"

**Comment by niuzhenguo** [comment]
Closing this, please open an issue on sbercloud provider if there are still problems.
