### ISSUE TITLE
how to get or create nics.network_id when create ecs by huaweicloud_ecs_instance_v1 ?

### ISSUE THREAD

**Issue by lyc0221** [huaweicloud/terraform-provider-huaweicloud#313]
### Terraform Version
Terraform v0.12.24

### Affected Resource(s)
Please list the resources as a list, for example:
- ecs_instance

### Expected Behavior
output `network_id`

### Steps to Reproduce
`terraform plan`

### More
I find the following resource will output the `network_id`, but I don't know which one I should use when I create ecs instance by `huaweicloud_ecs_instance_v1`
- huaweicloud_networking_network_v2
- huaweicloud_networking_port_v2
- huaweicloud_networking_subnet_v2

Can you create a detailed example for creating an esc-instance ?

I think this [example](https://www.terraform.io/docs/providers/huaweicloud/r/ecs_instance_v1.html) is not clear enough.

Thank you !

**Comment by niuzhenguo** [comment]
@lyc0221 Thanks for raising this, it should be huaweicloud_networking_network_v2.xx.id or huaweicloud_vpc_subnet_v1.xx.id, will update the example you linked above.
