### ISSUE TITLE
get images failed by data.huaweicloud_images_image_v2.ubuntu

### ISSUE THREAD

**Issue by lyc0221** [huaweicloud/terraform-provider-huaweicloud#316]
### Terraform Version
Terraform v0.12.24

### Affected Resource(s)
- ecs_instance

### Panic Output
[crash.log](https://github.com/lyc0221/terraform-modules/blob/master/example/huaweicloud/crash.log)

### Expected Behavior
return images

### Actual Behavior
Error: rpc error: code = Unavailable desc = transport is closing
panic: interface conversion: pagination.Page is nil, not vpcs.VpcPage

### Steps to Reproduce
`terraform plan`

data.tf

```
data "huaweicloud_vpc_v1" "default" {
  name = "vpc-default"
}

data "huaweicloud_vpc_subnet_ids_v1" "all" {
  vpc_id = data.huaweicloud_vpc_v1.default.id
}

data "huaweicloud_images_image_v2" "ubuntu" {
  name        = "Ubuntu 18.04" # 2020.5.19, Ubuntu 20.04 is not existed.
  visibility  = "public"
  most_recent = true
}
```

main.tf
```
module "ecs" {
  source = "../../modules/huaweicloud-ecs-instance"
  
  namenumber                  = var.namenumber

  service                     = var.service
  environment                 = var.environment
  region                      = var.region

  flavor                      = "s6.small.1"
  availability_zone           = var.availability_zone
  image_id                    = data.huaweicloud_images_image_v2.ubuntu.id
  nics                        = element(tolist(data.huaweicloud_vpc_subnet_ids_v1.all.ids), 0)

  security_group_ids          = [module.security_group.this_security_group_id]
}

```

### More
I try change the value(`data.huaweicloud_images_image_v2.ubuntu.name`), but still failed

**Comment by niuzhenguo** [comment]
@lyc0221 It seems the vpc data source issue instead of image, can you please provide the detailed log with OS_DEBUG=1 and TF_LOG=DEBUG, thanks!

**Comment by lyc0221** [comment]
[terraform_huaweicloud_debug.log](https://github.com/terraform-providers/terraform-provider-huaweicloud/files/4654218/terraform_huaweicloud_debug.log)

[crash.log](https://github.com/terraform-providers/terraform-provider-huaweicloud/files/4654221/crash.log)

Thank you!

**Comment by lyc0221** [comment]
also can't create vpc

```
module.vpc.huaweicloud_vpc_v1.this[0]: Creating...

Error: Error creating Huaweicloud VPC: Resource not found: [POST https://vpc.cn-south-1.myhuaweicloud.com/v1//vpcs], error message: {"error_msg":"The API does not exist or has not been published in the environment","error_code":"APIGW.0101","request_id":"0bc1f19e2d932646dab1b941a05658e9"}
```

**Comment by ShiChangkuo** [comment]
it seems you use AKSK authentication and without `tenant_name` or `tenant_id` arguments?

**Comment by lyc0221** [comment]
The `tenant_name` or `tenant_id` is not optional ?

**Comment by niuzhenguo** [comment]
@lyc0221 Can you provide your provider config as well? I assume that you don't configure tenant_id or tenant_name with the AK/SK information.

**Comment by niuzhenguo** [comment]
one of them must be configured.

**Comment by lyc0221** [comment]
Yeah, I don't configure.

providers.tf
```
provider "huaweicloud" {
  access_key  = var.huaweicloud_access_key
  secret_key  = var.huaweicloud_secret_key
  domain_name = "xxxxx"
  region      = var.region
  auth_url    = "https://iam.myhwclouds.com:443/v3"
}
```

**Comment by lyc0221** [comment]
I learned from [the official documentation](https://www.terraform.io/docs/providers/huaweicloud/index.html) that the parameter was optional, so I didn't add it. That is  a problem!

**Comment by lyc0221** [comment]
```

Error: Your query returned no results. Please change your search criteria and try again.

  on data.tf line 10, in data "huaweicloud_images_image_v2" "ubuntu":
  10: data "huaweicloud_images_image_v2" "ubuntu" {


make: *** [plan] Error 1
```

data.tf
```
data "huaweicloud_vpc_v1" "default" {
  name = "vpc-default"
}

data "huaweicloud_vpc_subnet_ids_v1" "all" {
  vpc_id = data.huaweicloud_vpc_v1.default.id
}

data "huaweicloud_images_image_v2" "ubuntu" {
  name        = "Ubuntu 18.04" # 2020.5.19, Ubuntu 20.04 is not existed.
  visibility  = "public"
  most_recent = true
}
```

@niuzhenguo The [example](https://www.terraform.io/docs/providers/huaweicloud/d/images_image_v2.html) may be wrong.

**Comment by niuzhenguo** [comment]
@lyc0221 it should be "Ubuntu 18.04 server 64bit", I will be updating this, thanks!

**Comment by niuzhenguo** [comment]
@lyc0221 also, maybe we can get rid of the requirements for tenant_id/tenant_name, it can be default to the region value.

**Comment by lyc0221** [comment]
That's very good. And I found that the default project name is the region name, so you can do that.

**Comment by niuzhenguo** [comment]
Closing this, website will be updated in the comming release.
