### ISSUE TITLE
Authentication Failed

### ISSUE THREAD

**Issue by ovaliburak** [huaweicloud/terraform-provider-huaweicloud#3209]
### Terraform Version
```
terraform {
  required_providers {
    huaweicloud = {
      source = "huaweicloud/huaweicloud"
      version = "1.52.1"
    }
  }
}
```

### Terraform Configuration Files
```
provider "huaweicloud" {
  region     = "tr-west-1"
  access_key = "${var.access_key}"
  secret_key = "${var.secret_key}"
}
```

│ Error: Authentication failed
│ 
│   with provider["registry.terraform.io/huaweicloud/huaweicloud"],
│   on main.tf line 10, in provider "huaweicloud":
│   10: provider "huaweicloud" {

I am have authentication problem with the new version. Same configs were working before. 
```
provider "registry.terraform.io/huaweicloud/huaweicloud" {
  version     = "1.51.0"
  constraints = "1.51.0"
```

**Comment by ShiChangkuo** [comment]
@ovaliburak Is the execution environment exactly the same except for the version?

**Comment by ShiChangkuo** [comment]
I will close it temporarily, If you have found a problem that seems similar to this, please open a new issue and complete the issue template so we can capture all the details necessary to investigate further.
