### ISSUE TITLE
data "huaweicloud_vpc_route_ids_v2" doesn't work

### ISSUE THREAD

**Issue by barucoh** [huaweicloud/terraform-provider-huaweicloud#323]
### Terraform Version
```
Terraform v0.12.23
+ provider.huaweicloud v1.14.0
```

### Affected Resource(s)
Please list the resources as a list, for example:
- `data "huaweicloud_vpc_route_ids_v2"`

### Terraform Configuration Files
```hcl
data "huaweicloud_vpc_route_ids_v2" "vpc_routes" {
  vpc_id = "<redacted - VPC UUID HERE>"
}
```

### Description
`data "huaweicloud_vpc_route_ids_v2"` expects a `vpc_id` yet it always returns a `Error: no matching route found for vpc with id <uuid>` even though the VPC contains a route table with routes, both custom and system ones.

**Comment by niuzhenguo** [comment]
@barucoh I can't reproduce your issue. Can you please provide more details.

**Comment by barucoh** [comment]
@niuzhenguo When I opened this issue I was trying to get the `router_id` for the `nat_gateway` resource, I thought I needed an actual "Router ID" but it appeared to be the VPC ID itself.

I guess this can be closed, but the documentation isn't so clear about that.
