### ISSUE TITLE
Add field to specify external ID in IAM

### ISSUE THREAD

**Issue by rucciva** [huaweicloud/terraform-provider-huaweicloud#3256]
### Current Terraform Version

```
Terraform v1.5.4
```

### Use-cases

Hi, i would like to give access to users in my IdP to huawei cloud using terraform so that i could easily create user access matrix. I have already configured my huawei cloud account to use a SAML IdP and map user to IAM [using external ID field](https://support.huaweicloud.com/intl/en-us/usermanual-iam/iam_08_0003.html#:~:text=An%20account%20can%20have%20only%20one%20identity%20provider%20of%20the%20IAM%20user%20type.%20If%20you%20select%20this%20type%2C%20ensure%20that%20you%20have%20created%20an%20IAM%20user%20and%20set%20the%20external%20identity%20ID). When i tried to do the same via terraform, i noticed that there is no field to specify exteranl id in the [doc](https://registry.terraform.io/providers/huaweicloud/huaweicloud/latest/docs/resources/identity_user#argument-reference)

### Proposal

add `external_id` argument to [identity user](https://registry.terraform.io/providers/huaweicloud/huaweicloud/latest/docs/resources/identity_user) resource

**Comment by ShiChangkuo** [comment]
@rucciva Thanks for your feedback. Currently, the API is ready and I can implement this feature soon.

**Comment by rucciva** [comment]
thanks for the fast respond @ShiChangkuo . looking forward to it. cheers!
