### ISSUE TITLE
"huaweicloud_cce_cluster_v3" resources and data always return "Action Forbidden" even with Full Privilges

### ISSUE THREAD

**Issue by barucoh** [huaweicloud/terraform-provider-huaweicloud#326]
### Description
I'm trying to create a CCE cluster in region `cn-south-1`.
I am an admin on the entire account, I have full privileges and am able to create a CCE cluster from the UI.
However when trying to create a CCE cluster through Terraform or even retrieve an existing CCE cluster, I get the following error:
**data** `Error: Unable to retrieve clusters: Action Forbidden`
**resource** `Error: Error creating HuaweiCloud Cluster: Action Forbidden`

When trying to do the same action in a different region - `ap-southeast-1` everything works.

### Debug info
```
2020/05/27 17:40:04 [WARN] Provider "registry.terraform.io/-/huaweicloud" produced an invalid plan for huaweicloud_cce_cluster_v3.cce-cluster, but we are tolerating it because it is using the legacy plugin SDK.
    The following problems may be the cause of any confusing errors from downstream operations:
      - .authentication_mode: planned value cty.StringVal("x509") does not match config value cty.NullVal(cty.String)
huaweicloud_cce_cluster_v3.cce-cluster: Creating...
2020/05/27 17:40:04 [DEBUG] huaweicloud_cce_cluster_v3.cce-cluster: applying the planned Create change
2020-05-27T17:40:04.268+0300 [DEBUG] plugin.terraform-provider-huaweicloud_v1.14.0_x4: 2020/05/27 17:40:04 [DEBUG] setting computed for "certificate_clusters" from ComputedKeys
2020-05-27T17:40:04.268+0300 [DEBUG] plugin.terraform-provider-huaweicloud_v1.14.0_x4: 2020/05/27 17:40:04 [DEBUG] setting computed for "certificate_users" from ComputedKeys
2020-05-27T17:40:04.268+0300 [DEBUG] plugin.terraform-provider-huaweicloud_v1.14.0_x4: 2020/05/27 17:40:04 [DEBUG] HuaweiCloud Region is: cn-south-1
2020/05/27 17:40:07 [DEBUG] huaweicloud_cce_cluster_v3.cce-cluster: apply errored, but we're indicating that via the Error pointer rather than returning it: Error creating HuaweiCloud Cluster: Action Forbidden
2020/05/27 17:40:07 [ERROR] <root>: eval: *terraform.EvalApplyPost, err: Error creating HuaweiCloud Cluster: Action Forbidden
2020/05/27 17:40:07 [ERROR] <root>: eval: *terraform.EvalSequence, err: Error creating HuaweiCloud Cluster: Action Forbidden

Error: Error creating HuaweiCloud Cluster: Action Forbidden

  on main.tf line 55, in resource "huaweicloud_cce_cluster_v3" "cce-cluster":
  55: resource "huaweicloud_cce_cluster_v3" "cce-cluster" {
```

**Comment by niuzhenguo** [comment]
@barucoh Please ask for help from Cloud side as the API just return this error with your account. We can't do any help here.

**Comment by barucoh** [comment]
@niuzhenguo I just got this answer from support:

> Dear customer, please be noted that, as an open source tool which enables the customer to safely and predictably create, change, and improve infrastructure, recently, it is not supportive for the Terraform to be used in China Mainland region. As far as we are concerned, the software violates Chinese laws and is illegal to sell in China. This explains why you are forbidden to create resources in Huawei Cloud China Mainland region through Terraform. We deeply apologize for those inconvenience that caused for you. Thank you so much for your support and understanding!

Is this true?
Can we use the provider only for non-China Mainland regions?

**Comment by niuzhenguo** [comment]
@barucoh Could you please provide the ticket number? As my understanding it's not related.

**Comment by niuzhenguo** [comment]
@barucoh I have talked with the support team, sorry for the misleading answer. You can continue your ticket or create a new one for the "Action Forbidden" API issue with your account.

**Comment by barucoh** [comment]
@niuzhenguo Thanks, it eventually appeared to be something related to account credit.
So creating other resources works, but creating CCE still fails with "Action Forbidden", it feels like this error message could use some more description returned from the backend API.

**Comment by niuzhenguo** [comment]
@barucoh Yes, we can just print the real error message from the API.

**Comment by barucoh** [comment]
@niuzhenguo Great! It would be good to see what actually happened in the backend, make troubleshooting easier.

**Comment by niuzhenguo** [comment]
@barucoh Actually, you can run `terrafrom apply` with OS_DEBUG=1 TF_LOG=DEBUG TF_LOG_PATH=/logfile to fetch the detailed description, and provide the API request details may help the support team easily understand you.

**Comment by barucoh** [comment]
@niuzhenguo I wasn't aware of the `OS_DEBUG=1`, this one helped a lot thanks!
It shows this in the error message:
```
2020-06-03T11:52:04.101+0300 [DEBUG] plugin.terraform-provider-huaweicloud_v1.14.0_x4:   "error_code": "APIGW.0801",
2020-06-03T11:52:04.101+0300 [DEBUG] plugin.terraform-provider-huaweicloud_v1.14.0_x4:   "error_msg": "The service is unavailable in the currently selected region: service name:CCE",
```

Is CCE not supported in `cn-south-1`?
I managed to create CCE through the UI in `cn-south-1` so this doesn't make sense...

**Comment by niuzhenguo** [comment]
@barucoh Could you provide the request url?

**Comment by barucoh** [comment]
@niuzhenguo Sure

```
2020-06-03T11:52:02.486+0300 [DEBUG] plugin.terraform-provider-huaweicloud_v1.14.0_x4: 2020/06/03 11:52:02 [DEBUG] setting computed for "certificate_clusters" from ComputedKeys
2020-06-03T11:52:02.486+0300 [DEBUG] plugin.terraform-provider-huaweicloud_v1.14.0_x4: 2020/06/03 11:52:02 [DEBUG] setting computed for "certificate_users" from ComputedKeys
2020-06-03T11:52:02.486+0300 [DEBUG] plugin.terraform-provider-huaweicloud_v1.14.0_x4: 2020/06/03 11:52:02 [DEBUG] HuaweiCloud Region is: cn-south-1
2020-06-03T11:52:02.487+0300 [DEBUG] plugin.terraform-provider-huaweicloud_v1.14.0_x4: 2020/06/03 11:52:02 [DEBUG] HuaweiCloud Request URL: POST https://cce.cn-south-1.myhuaweicloud.com/api/v3/projects/<redacted>/clusters
```

Shouldn't the request URL be the same for everyone?

**Comment by niuzhenguo** [comment]
@barucoh just want to check if we use a wrong URL on terraform side :D

**Comment by barucoh** [comment]
@niuzhenguo Just finished a troubleshooting session with support.
According to the HWC support team, the API used by Terraform when trying to create a CCE resource in "china mainland" regions is incorrect.
The API to get the auth tokens as it seems is:
```
HuaweiCloud Request Body: {
   "auth": {
     "identity": {
       "methods": [
         "password"
       ],
       "password": {
         "user": {
           "domain": {
             "name": "<redacted domain name>"
           },
           "name": "<redacted user name>",
           "password": "***"
         }
       }
     },
     "scope": {
       "domain": {
         "name": "<redacted domain name>"
       }
     }
   }
 }
```

According to support it should be (in case deploying to **cn-south-1**:
```
HuaweiCloud Request Body: {
   "auth": {
     "identity": {
       "methods": [
         "password"
       ],
       "password": {
         "user": {
           "domain": {
             "name": "<redacted domain name>"
           },
           "name": "<redacted user name>",
           "password": "***"
         }
       }
     },
     "scope": {
       "project": {
         "name": "cn-south-1"
       }
     }
   }
 }
```
Basically the difference is having the "project" instead of "domain" in the "scope" section.
So it appears there's a bug with the API call to CCE when it comes to china mainland regions?

As for my provider configuration:
```
provider "huaweicloud" {
  user_name = var.huawei_username
  password = var.huawei_password
  domain_name = "<redacted domain name>"
  tenant_name = "cn-south-1"
  region = "cn-south-1"
  auth_url = "https://iam.myhwclouds.com:443/v3"
}
```

Does this make sense?

**Comment by niuzhenguo** [comment]
@barucoh I don't understand why they can't use domain scoped token, that's a must for managing IAM resources with terraform. However, you can use ak/sk instead which is the recommended method, and I will update the webiste in the comming release https://github.com/terraform-providers/terraform-provider-huaweicloud/blob/master/website/docs/index.html.markdown#example-usage.
BTW, `tenant_name` and `auth_url` are still required in the current version.

**Comment by barucoh** [comment]
@niuzhenguo I just tried using `ak/sk` instead of user password and it still fails on "Action Forbidden"

**Comment by niuzhenguo** [comment]
@barucoh I would suggest you provide the logs to the support.

**Comment by barucoh** [comment]
@niuzhenguo I already tried support they said it was a problem with the API calls within china-mainland regions.
Can you please assist?

These are the latest logs I encountered:
```
2020-06-04T14:21:19.655+0300 [DEBUG] plugin.terraform-provider-huaweicloud_v1.14.0_x4: 2020/06/04 14:21:19 [DEBUG] Openstack Response Headers:
2020-06-04T14:21:19.655+0300 [DEBUG] plugin.terraform-provider-huaweicloud_v1.14.0_x4: Content-Type: application/json
2020-06-04T14:21:19.655+0300 [DEBUG] plugin.terraform-provider-huaweicloud_v1.14.0_x4: Date: Thu, 04 Jun 2020 11:21:19 GMT
2020-06-04T14:21:19.655+0300 [DEBUG] plugin.terraform-provider-huaweicloud_v1.14.0_x4: Server: api-gateway
2020-06-04T14:21:19.655+0300 [DEBUG] plugin.terraform-provider-huaweicloud_v1.14.0_x4: X-Request-Id: f7b9aac00c5fd993b80e7c25ab6860fa
2020-06-04T14:21:19.656+0300 [DEBUG] plugin.terraform-provider-huaweicloud_v1.14.0_x4: 2020/06/04 14:21:19 [DEBUG] HuaweiCloud Response Body: {
2020-06-04T14:21:19.656+0300 [DEBUG] plugin.terraform-provider-huaweicloud_v1.14.0_x4:   "error_code": "APIGW.0801",
2020-06-04T14:21:19.656+0300 [DEBUG] plugin.terraform-provider-huaweicloud_v1.14.0_x4:   "error_msg": "The service is unavailable in the currently selected region: service name:CCE",
2020-06-04T14:21:19.656+0300 [DEBUG] plugin.terraform-provider-huaweicloud_v1.14.0_x4:   "request_id": "f7b9aac00c5fd993b80e7c25ab6860fa"
2020-06-04T14:21:19.656+0300 [DEBUG] plugin.terraform-provider-huaweicloud_v1.14.0_x4: }
2020/06/04 14:21:19 [DEBUG] huaweicloud_cce_cluster_v3.cce-cluster: apply errored, but we're indicating that via the Error pointer rather than returning it: Error creating HuaweiCloud Cluster: Action Forbidden
2020/06/04 14:21:19 [ERROR] <root>: eval: *terraform.EvalApplyPost, err: Error creating HuaweiCloud Cluster: Action Forbidden
2020/06/04 14:21:19 [ERROR] <root>: eval: *terraform.EvalSequence, err: Error creating HuaweiCloud Cluster: Action Forbidden
```

**Comment by niuzhenguo** [comment]
@barucoh I don't know what's the difference between your account and mine, I don't see such issue and other customers seems also OK. That's why I recommend you ask help from the support.

**Comment by niuzhenguo** [comment]
@barucoh I got feedbacks from support team that it's already resolved. Do you still have problems with this?

**Comment by barucoh** [comment]
Yes I got the same feedback, I will check it later and update accordingly.
Thank you @niuzhenguo !

**Comment by ShiChangkuo** [comment]
Hello @barucoh any new progress？

**Comment by ShiChangkuo** [comment]
@barucoh I'm going to close this issue because it has been blocked for a long time.
If you have found a problem that seems similar to this, please open a new issue and complete the issue template so we can capture all the details necessary to investigate further.

**Comment by iabdulrahman91** [comment]
I encountered similar issue. 
simply, make sure the region inside provider "huaweicloud" { region = "some_region" } match the region you are importing.
 https://developer.huaweicloud.com/intl/en-us/endpoint
