### ISSUE TITLE
Add huaweicloud_mrs capacity 

### ISSUE THREAD

**Issue by Maoxingyun** [huaweicloud/terraform-provider-huaweicloud#3273]
### Current Terraform Version

```
Terraform v1.5.4
on darwin_arm64
```

### Proposal

I am looking forward to the resource API for mapreduce service, as AWS EMR.

**Comment by ShiChangkuo** [comment]
@Maoxingyun I can't get your point. Does [huaweicloud_mapreduce_cluster](https://registry.terraform.io/providers/huaweicloud/huaweicloud/latest/docs/resources/mapreduce_cluster) meet your requirement?

**Comment by ShiChangkuo** [comment]
I will close it temporarily, If you have found a problem that seems similar to this, please open a new issue and complete the issue template so we can capture all the details necessary to investigate further.
