### ISSUE TITLE
Unable to bind EIP to ELB

### ISSUE THREAD

**Issue by barucoh** [huaweicloud/terraform-provider-huaweicloud#337]
Perhaps I'm unaware of the method, but the documentation doesn't really dictate on a way to bind an Elastic IP to a Terraform created V2 Elastic Load Balancer.

Is there a way to do so?
And if not, can this please be added in the next release?

**Comment by niuzhenguo** [comment]
@barucoh You can bind the vip_port_id with eip address via networking_floatingip_associate_v2
https://www.terraform.io/docs/providers/huaweicloud/r/lb_loadbalancer_v2.html#vip_port_id
https://www.terraform.io/docs/providers/huaweicloud/r/networking_floatingip_associate_v2.html

**Comment by barucoh** [comment]
@niuzhenguo Thanks it's working!
Perhaps it's worth updating the documentation about that

**Comment by niuzhenguo** [comment]
@barucoh I will be working on that.

**Comment by barucoh** [comment]
@niuzhenguo Thanks!
