### ISSUE TITLE
How can I get a recordset_id for importing 

### ISSUE THREAD

**Issue by ik8svip** [huaweicloud/terraform-provider-huaweicloud#3397]
### Current Terraform Version

```bash
$ terraform version
Terraform v1.5.7
on linux_amd64
+ provider registry.terraform.io/hashicorp/http v3.4.0
+ provider registry.terraform.io/hashicorp/local v2.4.0
+ provider registry.terraform.io/huaweicloud/huaweicloud v1.55.0
```

### Use-cases

I want to create a DNS record and then import it cause I got unexpected errors when I try to create it. see #3396 

The [documentation](https://registry.terraform.io/providers/huaweicloud/huaweicloud/latest/docs/resources/dns_recordset) just said it can be imported via the command below

```bash
$ terraform import huaweicloud_dns_recordset.test <zone_id>/<recordset_id>
```

But there's no docs or example for how can I got the `recordset_id` for an existing records.

**Comment by ShiChangkuo** [comment]
@ik8svip actually, we can not find the ID of recordset from console. 
Fortunately, we can use [huaweicloud_dns_recordsets](https://registry.terraform.io/providers/huaweicloud/huaweicloud/latest/docs/data-sources/dns_recordsets) data source to get the list of DNS recordsets.

**Comment by ShiChangkuo** [comment]
I will close it temporarily, If you have found a problem that seems similar to this, please open a new issue and complete the issue template so we can capture all the details necessary to investigate further.
