### ISSUE TITLE
Terraform 报错

### ISSUE THREAD

**Issue by wo494945137** [huaweicloud/terraform-provider-huaweicloud#346]
![企业微信截图_15923796807481](https://user-images.githubusercontent.com/24561267/84975407-df02df80-b157-11ea-9c51-1f55dc0fb648.png)
您好，使用terraform报这个错，请问是什么原因，跟账户余额有关系吗

**Comment by wo494945137** [comment]
Hello, use terraform to report this error. What's the reason? Is it related to the account balance

**Comment by liorhasson** [comment]
Check that you have enough budget (money) in your cloud account!

**Comment by wo494945137** [comment]
Hello, I would like to ask whether Terraform supports coupon to create ECS

**Comment by niuzhenguo** [comment]
@wo494945137 Coupon is not supported, and I don't even know how to support it on Terraform side.
