### ISSUE TITLE
huaweicloud_vpc_subnet_ids return not subnet IDs but "Network ID" instead.

### ISSUE THREAD

**Issue by xianlin** [huaweicloud/terraform-provider-huaweicloud#3547]
### Terraform Version

```
1.6.1
```

### Expected Behavior
the "ids" field should return "Subnet IDs" 

### Actual Behavior
it return Network IDs

**Comment by xianlin** [comment]
![image](https://github.com/huaweicloud/terraform-provider-huaweicloud/assets/1726373/9485259a-b2e7-4788-a5d9-c9fb974da501)

**Comment by ShiChangkuo** [comment]
please use [huaweicloud_vpc_subnets](https://registry.terraform.io/providers/huaweicloud/huaweicloud/latest/docs/data-sources/vpc_subnets) data source to get the subnet_id. For example, `data.huaweicloud_vpc_subnets.test.subnets[*].ipv4_subnet_id`

**Comment by ShiChangkuo** [comment]
I will close it temporarily, If you have found a problem that seems similar to this, please open a new issue and complete the issue template so we can capture all the details necessary to investigate further.
