### ISSUE TITLE
cdn resource doesn't support websocket parameter

### ISSUE THREAD

**Issue by riverfell** [huaweicloud/terraform-provider-huaweicloud#3581]
cdn resource doesn't support websocket parameter

**Comment by ShiChangkuo** [comment]
@riverfell can you show more details about this feature? I can not find the `websocket` in console and API docs.

**Comment by riverfell** [comment]
![image](https://github.com/huaweicloud/terraform-provider-huaweicloud/assets/59993421/df432cfa-d726-4b83-93bc-940840214c48)
you can find the switch in advanced settings

and in [api doc](https://support.huaweicloud.com/api-cdn/UpdateDomainFullConfig.html) you can see configs named websocket

**Comment by ShiChangkuo** [comment]
I got it. we will try to develop a new resource to impl this feature.
