### ISSUE TITLE
No resources related to ServiceStage

### ISSUE THREAD

**Issue by thiagoeh** [huaweicloud/terraform-provider-huaweicloud#383]
None of the ServiceStage related resources are available.

### Terraform Version
```
terraform version
Terraform v0.12.28
+ provider.huaweicloud v1.16.0
```

### References

* [ServiceStage elements in AOS (Application Orchestration Service)](https://support.huaweicloud.com/en-us/tr-aos/aos_01_4013.html)
  * ServiceStage.Agent
  * ServiceStage.AppGroup
  * ServiceStage.ContainerComponent
  * ServiceStage.Job
  * ServiceStage.StatefulApplication
  * ServiceStage.StatelessApplication
* [Application Management V2 APIs](https://support.huaweicloud.com/intl/en-us/api-servicestage/servicestage_api_0091.html)

**Comment by niuzhenguo** [comment]
@thiagoeh We need ServiceStage to provide a Golang sdk first.

**Comment by niuzhenguo** [comment]
@thiagoeh You can create a request to ServiceStage team ^

**Comment by tianxiaoliang** [comment]
https://github.com/huaweicloud/huaweicloud-sdk-go-v3/tree/master/services/servicestage/v2

here is the go sdk

**Comment by tianxiaoliang** [comment]
service stage has changed the model， plz only use v2 API.
