### ISSUE TITLE
huaweicloud_rds_instance description field has no sense

### ISSUE THREAD

**Issue by aaovchinnikov** [huaweicloud/terraform-provider-huaweicloud#4101]
Hi there,

In provider version 1.60.1 `huaweicloud_rds_instance` resource has field:
```
description - (Optional, String) Specifies the description of the instance. The value consists of 0 to 64 characters, including letters, digits, periods (.), underscores (_), and hyphens (-).
```

Good practice is to place descriptions at any place you can, but adding `description` field easily leads to too generic error:
```
{"errCode":"DBS.200001","externalMessage":"Parameter error"}
```
The cause is space symbols are forbidden in `description` field, what is ridiculous I believe. No other resource object has such limitation on `description`.

In addition [Huaweicloud API docs](https://support.huaweicloud.com/intl/en-us/api-rds/rds_01_0002.html#rds_01_0002__table64243102) and web-UI don't mention anything similar to `description`, making `description` field in `huaweicloud_rds_instance` useless, misleading and error prone. 

Is there any chance Huaweicloud would change/add `description` support for RDS?

Or maybe it's better to remove `description` field from `huaweicloud_rds_instance` resource at all

**Comment by ShiChangkuo** [comment]
@aaovchinnikov It's better to open a service ticket in Huawei Cloud because the valid values are defined by RDS service.

**Comment by ShiChangkuo** [comment]
I will close it temporarily, If you have found a problem that seems similar to this, please open a new issue and complete the issue template so we can capture all the details necessary to investigate further.
