### ISSUE TITLE
Any plan to support SWR (Software Repository for Container) ?

### ISSUE THREAD

**Issue by namoshizun** [huaweicloud/terraform-provider-huaweicloud#428]
On the Terraform doc, I couldn't find a resource provider for provisioning SWR resource... Unless I missed it on the doc, is there any plan to support SWR ;D? 
Thanks heaps.

**Comment by niuzhenguo** [comment]
@namoshizun Currently not, we need SWR provide a golang sdk first before we can add it to terraform.

**Comment by namoshizun** [comment]
> @namoshizun Currently not, we need SWR provide a golang sdk first before we can add it to terraform.

Thanks for replying. Is SWR team going to provide a golang sdk, or is there a timeline for doing so? Currently, we are migrating our cloud infrastructure from Azure to HuaweiCloud and the lack of SWR Terraform support is becoming a road-blocker. We might have to leave part of infrastructure, at least the container registry, in Azure, if we do have to leave SWR out of our Terraform plan...

**Comment by niuzhenguo** [comment]
> > @namoshizun Currently not, we need SWR provide a golang sdk first before we can add it to terraform.
> 
> Thanks for replying. Is SWR team going to provide a golang sdk, or is there a timeline for doing so? Currently, we are migrating our cloud infrastructure from Azure to HuaweiCloud and the lack of SWR Terraform support is becoming a road-blocker. We might have to leave part of infrastructure, at least the container registry, in Azure, if we do have to leave SWR out of our Terraform plan...

You can create a request to SWR team to prioritize this.

**Comment by namoshizun** [comment]
> > > @namoshizun Currently not, we need SWR provide a golang sdk first before we can add it to terraform.
> > 
> > 
> > Thanks for replying. Is SWR team going to provide a golang sdk, or is there a timeline for doing so? Currently, we are migrating our cloud infrastructure from Azure to HuaweiCloud and the lack of SWR Terraform support is becoming a road-blocker. We might have to leave part of infrastructure, at least the container registry, in Azure, if we do have to leave SWR out of our Terraform plan...
> 
> You can create a request to SWR team to prioritize this.

Right....could you point me out how to send such request to them?

**Comment by niuzhenguo** [comment]
@namoshizun You can create servcie ticket on Console.

**Comment by niuzhenguo** [comment]
@namoshizun To my understanding, you can use `docker` cli to manage the images with SWR, which terraform resources do you need on Terraform?

**Comment by namoshizun** [comment]
@niuzhenguo yeah but that's the resource management after terraform provision --- use docker CLI to push / pull from an already existing container registry. However, currently Huaweicloud provider lacks support for provisioning the SWR registry, which means we would have to manually create & configure it and keep track of its status, which is kinda "anti-terraform". For consideration, Azure has a provider resource for its container registry: https://www.terraform.io/docs/providers/azurerm/r/container_registry.html

**Comment by aspekt112** [comment]
Any progress here?

**Comment by tarasmandryk** [comment]
We're interested in deploying SWR service with Terraform too.
I'd be really grateful if you could share your roadmap regarding Terraform support of various HuaweiCloud services.

**Comment by niuzhenguo** [comment]
Sorry for the late response, will prioritize this. @tarasmandryk you can go to kanban project to see the roadmap.

**Comment by niuzhenguo** [comment]
hi all, we just need a SWR organization/namespace resource here?
