### ISSUE TITLE
[MRS] Request to add charging mode argument. 

### ISSUE THREAD

**Issue by thanapatkit** [huaweicloud/terraform-provider-huaweicloud#4288]
Hi, 

I would like to create a MapReduce(MRS) cluster using Terraform, and I can't configure it for pay-per-use mode. It seems that no configuration for the charging mode

However, this issue doesn't arise when creating the cluster via the HWC console.

Please add argument for configuring the charging mode in this service as well.

Reference: [MRS Cluster](https://registry.terraform.io/providers/huaweicloud/huaweicloud/1.61.1/docs/resources/mapreduce_cluster)
Current Version: v1.61.1

**Comment by niuzhenguo** [comment]
will try to test the API to see if we can support this on Terraform

**Comment by niuzhenguo** [comment]
The default mode is pay-per-use, no need to do any configuration.

**Comment by thanapatkit** [comment]
@niuzhenguo  Thanks for your confirmation. I think this issue is clear and I will close now.
