### ISSUE TITLE
1.16 -> 1.17 regression, EIP's always created for resource_huaweicloud_cce_node_v3

### ISSUE THREAD

**Issue by rgershkovich** [huaweicloud/terraform-provider-huaweicloud#434]
### Terraform Version
Terraform v0.12.29

### Affected Resource(s)
- resource_huaweicloud_cce_node_v3

### Terraform Configuration Files
```hcl
resource "huaweicloud_cce_node_v3" "this" {
  cluster_id = huaweicloud_cce_cluster_v3.this.id
  billing_mode = 0
  subnet_id = var.network_id
  max_pods = lookup(each.value, "max_pods", 0)
  name = "${terraform.workspace}-${each.key}"
  flavor_id = lookup(each.value, "flavor_id", "s3.large.2")

  // (Optional) Elastic IP type. Default is 5_bgp. Changing this parameter will create a new resource.
  iptype = lookup(each.value, "iptype", "5_bgp")

  // (Required) specify the name of the available partition (AZ). Changing this parameter will create a new resource.
  availability_zone = lookup(each.value, "availability_zone", var.region_az[0])

  // (Optional) Number of elastic IPs to be dynamically created. Changing this parameter will create a new resource.
  eip_count = lookup(each.value, "eip_count", 0)

  // (Optional) List of existing elastic IP IDs. Changing this parameter will create a new resource.
  eip_id = lookup(each.value, "eip_id", null)
  }

  root_volume {
    size       = lookup(each.value, "root_volume_size", 40)
    volumetype = lookup(each.value, "root_volume_type", "SSD")
  }

  sharetype      = lookup(each.value, "sharetype", "PER")
  bandwidth_size = lookup(each.value, "bandwidth_size", 100)
}
```

### Expected Behavior
Be able to create resource_huaweicloud_cce_node_v3 without EIP's attached.

### Actual Behavior
Looks like we are always getting EIP's now due to this condition:
https://github.com/terraform-providers/terraform-provider-huaweicloud/blob/ed0188b2495d59cc702d47f17c67f2fdc64dc642/huaweicloud/resource_huaweicloud_cce_node_v3.go#L366

**bandwidthSize** can't be set to 0:
> "error_msg":"Request body invalid","message":"Bandwith of EIP flavor is out of range: 1-100 Mbit/s"

So even if we set `eipCount == 0`, it's still turned to 1 and EIP is created. Is there a way to not create EIP's for resource_huaweicloud_cce_node_v3 now?

Thank you!

**Comment by niuzhenguo** [comment]
@rgershkovich The condition is assuming the `bandwidth_size` not configured.

**Comment by niuzhenguo** [comment]
@ShiChangkuo Please have a look at this, thanks!

**Comment by rgershkovich** [comment]
It doesn't look like that it's possible to leave `bandwidth_size` not configured.
Getting same
```
Error: Error creating HuaweiCloud Node: Bad request with: [POST https://cce.ap-southeast-1.myhuaweicloud.com/api/v3/projects/x/clusters/y/nodes], error message: {"error_code":"CCE_CM.0201","error_msg":"Request body invalid","message":"Bandwith of EIP flavor is out of range: 1-100 Mbit/s","errorCode":"E.CFE.4000201","reason":"Request body invalid"}
```

**Comment by niuzhenguo** [comment]
@rgershkovich will try on my local env.

**Comment by niuzhenguo** [comment]
@rgershkovich https://github.com/huaweicloud/terraform-provider-huaweicloud/blob/master/huaweicloud/resource_huaweicloud_cce_node_v3_test.go#L153-L167 please try this.

**Comment by rgershkovich** [comment]
Thank you for your help!

Removed several elements fully like `iptype` / `sharetype` / `bandwidth_size` and indeed it created nodes with 0 EIPs as needed.

Maybe the ticket can be closed.

**Comment by niuzhenguo** [comment]
@rgershkovich let's keep this open, we can do some check to avoid such issue.
