### ISSUE TITLE
Feature request: support enterprise_project_id 

### ISSUE THREAD

**Issue by XuLi0330** [huaweicloud/terraform-provider-huaweicloud#435]
Currently,  it seems that only a few resources  such as ecs、cdn  support enterprise_project_id.   
Could terraform team add the feature that all  resources （vpc,  subnet, cce,rds  ...） provisioned by terraform support enterprise_project_id  attribute？

- [x] huaweicloud_vpc_subnet_v1
- [x] huaweicloud_networking_secgroup_v2
- [x] huaweicloud_obs_bucket
- [x] huaweicloud_sfs_file_system_v2
- [x] huaweicloud_rds_instance_v3
- [x] huaweicloud_dcs_instance_v1
- [x] huaweicloud_vpc_bandwidth_v2
- [x] huaweicloud_vpc_eip_v1
- [x] huaweicloud_cce_cluster_v3
- [x] huaweicloud_nat_snat_rule_v2
- [x] huaweicloud_networking_secgroup_rule_v2

**Comment by niuzhenguo** [comment]
Yes, new added resources will all include `enterprise_project_id`, and regarding old ones, we are working on adding EPS support for all of them now.

**Comment by namoshizun** [comment]
+1 this feature request, would be quite a necessary feature to better organize resources~~

**Comment by niuzhenguo** [comment]
@XuLi0330 @namoshizun Do you have a priority list of resources for this request?

**Comment by namoshizun** [comment]
@niuzhenguo 
Thanks! Currently our system uses the following stack, and it'd be lovely to have all of them support "enterprise_project_id" :D.

* huaweicloud_vpc_subnet_v1
* huaweicloud_networking_secgroup_v2
* huaweicloud_obs_bucket
* huaweicloud_sfs_file_system_v2
* huaweicloud_rds_instance_v3
* huaweicloud_dcs_instance_v1
* huaweicloud_vpc_bandwidth_v2
* huaweicloud_vpc_eip_v1
* huaweicloud_cce_cluster_v3
* huaweicloud_nat_snat_rule_v2
* huaweicloud_networking_secgroup_rule_v2

**Comment by niuzhenguo** [comment]
@namoshizun OK, will prioritize according to  the provided list.

**Comment by namoshizun** [comment]
@niuzhenguo looking forward to it lol!

**Comment by niuzhenguo** [comment]
@namoshizun we don't have an enterprise_project_id parameter on API side for huaweicloud_vpc_subnet, it depends on the enterprise project id of the VPC which it belongs to.
