### ISSUE TITLE
创建vpc报错但是成功创建，用最新的插件和1.59.0都不行

### ISSUE THREAD

**Issue by op-family** [huaweicloud/terraform-provider-huaweicloud#4378]
[root@amj terraform-ws]# terraform apply

Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # huaweicloud_vpc.example will be created
  + resource "huaweicloud_vpc" "example" {
      + cidr                  = "192.168.0.0/16"
      + enterprise_project_id = (known after apply)
      + id                    = (known after apply)
      + name                  = "terraform_vpc"
      + region                = (known after apply)
      + routes                = (known after apply)
      + status                = (known after apply)
    }

Plan: 1 to add, 0 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

huaweicloud_vpc.example: Creating...
huaweicloud_vpc.example: Still creating... [10s elapsed]
huaweicloud_vpc.example: Still creating... [20s elapsed]
huaweicloud_vpc.example: Still creating... [30s elapsed]
╷
│ Error: Plugin did not respond
│ 
│   with huaweicloud_vpc.example,
│   on main.tf line 2, in resource "huaweicloud_vpc" "example":
│    2: resource "huaweicloud_vpc" "example" {
│ 
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may contain more details.
╵

Stack trace from the terraform-provider-huaweicloud_v1.59.0 plugin:

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0xe68554]

goroutine 30 [running]:
github.com/huaweicloud/terraform-provider-huaweicloud/huaweicloud/services/vpc.resourceVirtualPrivateCloudRead({0x40002536c0?, 0x1e530d3?}, 0x400118cb80, {0x1e35dc0?, 0x400121d200})
        github.com/huaweicloud/terraform-provider-huaweicloud/huaweicloud/services/vpc/resource_huaweicloud_vpc.go:228 +0x9b4
github.com/huaweicloud/terraform-provider-huaweicloud/huaweicloud/services/vpc.resourceVirtualPrivateCloudCreate({0x22307b0, 0x4000266000}, 0x400118cb80, {0x1e35dc0?, 0x400121d200?})
        github.com/huaweicloud/terraform-provider-huaweicloud/huaweicloud/services/vpc/resource_huaweicloud_vpc.go:165 +0xc30
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).create(0x40008e8700, {0x2230708, 0x4000d23a40}, 0xd?, {0x1e35dc0, 0x400121d200})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.0/helper/schema/resource.go:707 +0xe8
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0x40008e8700, {0x2230708, 0x4000d23a40}, 0x4000b7c820, 0x400118ca00, {0x1e35dc0, 0x400121d200})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.0/helper/schema/resource.go:837 +0x850
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0x400000c180, {0x2230708?, 0x4000d23950?}, 0x4000d4eb40)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.0/helper/schema/grpc_provider.go:1021 +0xb08
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ApplyResourceChange(0x40004bdae0, {0x2230708?, 0x4000d23140?}, 0x4000a357a0)
        github.com/hashicorp/terraform-plugin-go@v0.14.0/tfprotov5/tf5server/server.go:818 +0x3c0
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0x1d8bb20?, 0x40004bdae0}, {0x2230708, 0x4000d23140}, 0x4000a35730, 0x0)
        github.com/hashicorp/terraform-plugin-go@v0.14.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:385 +0x164
google.golang.org/grpc.(*Server).processUnaryRPC(0x40002b01e0, {0x2235658, 0x4000b72d00}, 0x4000efe5a0, 0x4000b76390, 0x343d8a0, 0x0)
        google.golang.org/grpc@v1.56.3/server.go:1335 +0xbe0
google.golang.org/grpc.(*Server).handleStream(0x40002b01e0, {0x2235658, 0x4000b72d00}, 0x4000efe5a0, 0x0)
        google.golang.org/grpc@v1.56.3/server.go:1712 +0x7cc
google.golang.org/grpc.(*Server).serveStreams.func1.1()
        google.golang.org/grpc@v1.56.3/server.go:947 +0xb4
created by google.golang.org/grpc.(*Server).serveStreams.func1 in goroutine 10
        google.golang.org/grpc@v1.56.3/server.go:958 +0x160

Error: The terraform-provider-huaweicloud_v1.59.0 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.

[root@amj terraform-ws]# terraform destory
Terraform has no command named "destory". Did you mean "destroy"?

To see all of Terraform's top-level commands, run:
  terraform -help

**Comment by ShiChangkuo** [comment]
@qybf 请问这是在哪个region下报的错？

**Comment by op-family** [comment]
> @qybf 请问这是在哪个region下报的错？

贵阳一

**Comment by ShiChangkuo** [comment]
你好，我在贵阳一没有复现出来，能否提供一下日志？
参考方法：https://support.huaweicloud.com/terraform_faq/index.html#section1

**Comment by op-family** [comment]
> 你好，我在贵阳一没有复现出来，能否提供一下日志？ 参考方法：https://support.huaweicloud.com/terraform_faq/index.html#section1

你好，透过日志找到原因了。因为我在华为云上部署了一个vpn服务用来访问华为云内网。我的这台机器就是，连接了vpn，然后通过vpn配置了网络代理，而网络代理的ip则是华为云内网的ip，不是公网ip。在日志中有这样一个报错：

2024-03-25T10:32:56.237+0800 [WARN]  provider.terraform-provider-huaweicloud_v1.62.1: parsing https proxy failed: parse "10.0.1.167:10171": first path segment in URL cannot contain colon: timestamp="2024-03-25T10:32:56.237+0800"

这里的10.0.1.167:10171就是我的代理。当我把代理一断开并且同时需要断开vpn，则任何版本插件都没问题。但是我实测，v1.56.0版本及以下的很多版本，我都不需要断开vpn以及代理，都可正常运行，但是会有一些警告。

**Comment by ShiChangkuo** [comment]
请问是否设置了`HTTPS_PROXY`环境变量呢？

**Comment by op-family** [comment]
> 请问是否设置了`HTTPS_PROXY`环境变量呢？

设置了的，就是通过这个环境变量设置的代理，以及http_proxy

**Comment by ShiChangkuo** [comment]
能否给proxy加上 http:// 的前缀试一下？

**Comment by op-family** [comment]
> 能否给proxy加上 http:// 的前缀试一下？

export HTTPS_PROXY=http://10.0.1.117:10171
这样配置确实可行，已解决，多谢答疑。
