### ISSUE TITLE
Some problems checked by tfproviderlint

### ISSUE THREAD

**Issue by smilemusic** [huaweicloud/terraform-provider-huaweicloud#448]
Here are some questions about lint checking,

/home/devops01/src/terraform-provider-huaweicloud/huaweicloud/resource_huaweicloud_mrs_cluster_v1.go:566:21: R004: ResourceData.Set() incompatible value type: struct{wall uint64; ext int64; loc *time.Location}
/home/devops01/src/terraform-provider-huaweicloud/huaweicloud/resource_huaweicloud_mrs_cluster_v1.go:567:21: R004: ResourceData.Set() incompatible value type: struct{wall uint64; ext int64; loc *time.Location}
/home/devops01/src/terraform-provider-huaweicloud/huaweicloud/resource_huaweicloud_mrs_cluster_v1.go:568:31: R004: ResourceData.Set() incompatible value type: struct{wall uint64; ext int64; loc *time.Location}
/home/devops01/src/terraform-provider-huaweicloud/huaweicloud/resource_huaweicloud_networking_subnet_v2.go:234:23: R004: ResourceData.Set() incompatible value type: []github.com/huaweicloud/golangsdk/openstack/networking/v2/subnets.HostRoute
/home/devops01/src/terraform-provider-huaweicloud/huaweicloud/resource_huaweicloud_as_group_v1.go:602:5: R005: multiple ResourceData.HasChange() calls can be combined with single HasChanges() call
/home/devops01/src/terraform-provider-huaweicloud/huaweicloud/resource_huaweicloud_compute_instance_v2.go:756:5: R005: multiple ResourceData.HasChange() calls can be combined with single HasChanges() call
/home/devops01/src/terraform-provider-huaweicloud/huaweicloud/resource_huaweicloud_iam_agency_v3.go:449:5: R005: multiple ResourceData.HasChange() calls can be combined with single HasChanges() call
/home/devops01/src/terraform-provider-huaweicloud/huaweicloud/resource_huaweicloud_iam_agency_v3.go:470:5: R005: multiple ResourceData.HasChange() calls can be combined with single HasChanges() call
/home/devops01/src/terraform-provider-huaweicloud/huaweicloud/resource_huaweicloud_vbs_backup_policy_v2.go:264:5: R005: multiple ResourceData.HasChange() calls can be combined with single HasChanges() call
/home/devops01/src/terraform-provider-huaweicloud/huaweicloud/resource_huaweicloud_ces_alarmrule.go:343:32: R006: RetryFunc should include RetryableError() handling or be removed
/home/devops01/src/terraform-provider-huaweicloud/huaweicloud/resource_huaweicloud_ces_alarmrule.go:368:32: R006: RetryFunc should include RetryableError() handling or be removed

**Comment by ShiChangkuo** [comment]
@smilemusic thanks for you efforts!

closed by #467 #471 #473
