### ISSUE TITLE
Feature request: CCE resource exports raw kube config content 

### ISSUE THREAD

**Issue by namoshizun** [huaweicloud/terraform-provider-huaweicloud#469]
Hiiii,
For the CCE resource, besides exporting individual kube config variables like certificate_clusters/server etc (the current behaviour), it'd be nice if it can also export the whole kube config in some encoded format.

**Use case**:
In a continuous deployment pipeline, we setup the cluster access by creating the local ~/.kube/config file within our CD container. While it is possible to do so by executing the `kubectl config`  command multiple times with needed kubeconfig credentials, one can simply `cat` the raw config content if he has access to it.

For consideration,  Azure Kubernetes Service resource exports `kube_config_raw`: https://www.terraform.io/docs/providers/azurerm/r/kubernetes_cluster.html#kube_config_raw

**Comment by niuzhenguo** [comment]
@namoshizun Thanks for raising this, will try to add it in next release.

**Comment by namoshizun** [comment]
@niuzhenguo 
Thanks! Another minor request about the CCE exports.... I can create this request in another issue if you would like.
So is it also possible to export the CCE's node security group ID? The reason is that we want to configure security group ingress rule within Terraform as well, which requires the CCE security group ID to be known.

**Comment by niuzhenguo** [comment]
@namoshizun Seems yes, the security group ID can be exported according to the API docs.

**Comment by kittitucht** [comment]
how can we configure terraform kubernetes provide with CCE. We did use terraform data for CCE and then would like to configure kubernetes provider using that data.

data "huaweicloud_cce_cluster" "mycluster1" {
  name                   = "mycluster1"
  status                 = "Available"
}

provider "kubernetes" {
  load_config_file = false

  host  = data.huaweicloud_cce_cluster.mycluster1.certificate_clusters.server
}

**Comment by namoshizun** [comment]
@kittitucht According to the kubernetes provider's [official doc](https://registry.terraform.io/providers/hashicorp/kubernetes/latest/docs#statically-defined-credentials), it allows defining K8S credentials statically, in which case you can just provide the K8S credentials exported from the "huaweicloud_cce_cluster". However, I am not sure whether you can reference a data source variable inside the provider definition, like what you showed. In our use case, since the K8S provision happens after the cloud infrastructure provision, we simply create the local ~/.kube/config file and the K8S provider will know to load it.

**Comment by niuzhenguo** [comment]
@kittitucht We can add TLS certificates attributes to cce_cluster data source. Currently only cce cluster resource have this
https://registry.terraform.io/providers/huaweicloud/huaweicloud/latest/docs/resources/cce_cluster#certificate_clusters/server

**Comment by kittitucht** [comment]
> @kittitucht We can add TLS certificates attributes to cce_cluster data source. Currently only cce cluster resource have this
> https://registry.terraform.io/providers/huaweicloud/huaweicloud/latest/docs/resources/cce_cluster#certificate_clusters/server

sounds good
