### ISSUE TITLE
Feature request: NAT data source and more friendly elastic load balance resource definition

### ISSUE THREAD

**Issue by namoshizun** [huaweicloud/terraform-provider-huaweicloud#475]
Hiii,
Unless the Terraform documentation is missing a part, it seems that there isn't a data source for NAT gateway? This data source will be vital for our use case where we already purchased a shared NAT beforehand and would like use it to provide internet access to multiple clusters. Currently, for the lack of NAT data source, we have to hardcode the gateway ID in the SAT rule definition like: 

```
resource "huaweicloud_nat_snat_rule_v2" "snat" {
  # TODO: read it from data source!
  nat_gateway_id = "xxx-xxx-xxx-xxx"
  network_id     = huaweicloud_vpc_subnet_v1.subnet.id
  floating_ip_id = huaweicloud_vpc_eip_v1.nat_ip.id
}
```

Another petition is in regards with the [Elastic Load Balancer resource API](https://www.terraform.io/docs/providers/huaweicloud/r/lb_loadbalancer_v2.html), which looks quite confusing to us, and perhaps a bit outdated already? The example gives a "floating_ip" which it is undocumented. In a nutshell, we hope to create a ELB similar to how the portal guided us --- select a flavour (dedicated or shared), elastic IP (use an existing one or create a new one) and VPC & subnet. 

```
resource "huaweicloud_lb_loadbalancer_v2" "lb_1" {
  vip_subnet_id = "d9415786-5f1a-428b-b35f-2f1523e146d2"
}

resource "huaweicloud_networking_eip_associate" "eip_1" {
  floating_ip = "1.2.3.4"
  port_id     = "${huaweicloud_lb_loadbalancer_v2.lb_1.vip_port_id}"
}
```

Thanks heaps!

**Comment by niuzhenguo** [comment]
Yes, we don't have such data source for nat gateway, will add ASAP!
The `floating_ip` is deprecated and should use `public_ip` instead, will update the example. 
Regarding to the LB API, I'm not sure if the API's capability is same as the portal.

**Comment by namoshizun** [comment]
> Yes, we don't have such data source for nat gateway, will add ASAP!
> The `floating_ip` is deprecated and should use `public_ip` instead, will update the example.
> Regarding to the LB API, I'm not sure if the API's capability is same as the portal.

Thanks! Appreciate the effort. By the way, the ELB resource accepts a "flavor" parameter of UUID type. Could you also add more detailed description of what this "flavor" is and what are the selectable flavors, together with their UUID?

**Comment by niuzhenguo** [comment]
@namoshizun Seems we don't support the `flavor` parameter at all, please just ignore that, will update the docs soon.
