### ISSUE TITLE
DCS Redis 5.0 resource provision still requires security group ID

### ISSUE THREAD

**Issue by namoshizun** [huaweicloud/terraform-provider-huaweicloud#505]
Hiiii,
I encountered some quite weird terraform behavior while trying to create an DCS Redis 5.0 resource. According to the [official documentation](https://support.huaweicloud.com/dcs_faq/dcs-faq-0427022.html), Redis 4.0 and 5.0 do not support security group, `huaweicloud_dcs_instance` still asks me to give a security group ID.... And even if I gave it the requested sec group ID, it doesn't seem to be recognized by HWC at all because the second terraform apply will ask me whether I am trying to set its security group ID... like below
```

  # huaweicloud_dcs_instance_v1.redis_cache will be updated in-place
  ~ resource "huaweicloud_dcs_instance_v1" "redis_cache" {
        available_zones    = [
            "xxxxx",
        ]
        backup_at          = [
            7,
        ]
        backup_type        = "manual"
        begin_at           = "00:00-01:00"
        capacity           = 2
        description        = "KV Redis cache"
        engine             = "Redis"
        engine_version     = "5.0"
        id                 = "xxxxx"
        maintain_begin     = "02:00:00"
        maintain_end       = "06:00:00"
        name               = "aiclp-staging-redis_cache"
        password           = (sensitive value)
        period_type        = "weekly"
        product_id         = "redis.ha.au1.large.r2.2-h"
        resource_spec_code = "redis.ha.au1.large.r2.2"
        save_days          = 1
      + security_group_id  = "xxxxx"
        subnet_id          = "xxxxx"
        subnet_name        = "aiclp-staging-subnet"
        used_memory        = 2
        user_id            = "xxxxx"
        vpc_id             = "xxxxx"
        vpc_name           = "aiclp-vpc"
    }
```

### Affected Resource(s)
- huaweicloud_dcs_instance

### Terraform Configuration
Similar to the Redis provision example given in the [offical doc](https://registry.terraform.io/providers/huaweicloud/huaweicloud/latest/docs/resources/dcs_instance)

### Expected Behavior
Create Redis 5.0 DCS without security group

### Actual Behavior
Security group is mandatory regardless of Redis version

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. Create an Redis 5.0 DCS resource similar to the official doc's example but setting "engine_version" to "5.0"
2. The first terraform apply works fine.
3. Immediately run `terraform apply` again, but this time terraform will somehow think that you are trying to set the DCS' security group.

**Comment by namoshizun** [comment]
One more thing.... for some reason, I was unable to export Redis IP and port either. My terraform script is:

```hcl
output "REDIS_HOST" {
  value = huaweicloud_dcs_instance_v1.redis_cache.ip
}
output "REDIS_PORT" {
  value = huaweicloud_dcs_instance_v1.redis_cache.port
}
```

but none of them appears in my `terraform output`

**Comment by ShiChangkuo** [comment]
@namoshizun thanks for your reporting.
we will set `security_group_id` to be optional for Redis 4.0 and 5.0, and add `whitelists` for them ASAP.
the missing `ip` and `port` will be fixed together.

**Comment by namoshizun** [comment]
@ShiChangkuo Thanks! much appreciated.

**Comment by namoshizun** [comment]
@ShiChangkuo looks like the DCS resource for redis 5.0 still has some problem... #576
