### ISSUE TITLE
Invalid node pool type, only support vm and ElasticBMS

### ISSUE THREAD

**Issue by kittitucht** [huaweicloud/terraform-provider-huaweicloud#548]
resource "huaweicloud_cce_node_pool" "node_pool" {
  cluster_id               = huaweicloud_cce_cluster.mycluster1.id
  name                     = "testpool"
  os                       = "EulerOS"
  initial_node_count       = 2
  flavor_id                = "s3.large.2"
  password = "JDYkS1oydTcxQ0Q0SmpRbmVBeSRXRjVkc29PalRnYzlSRDQ2aTQ2Y0NMM0g5MkxNRW83OHMwckhkZlNMREU4UFc3eWxFMklDY3hVR0Y3LzhSQmJueFcwY3JnQTNaR05GQTBMTGdGYVlEMA=="
  scall_enable             = true
  min_node_count           = 1
  max_node_count           = 10
  scale_down_cooldown_time = 100
  priority                 = 1

  root_volume {
    size       = 40
    volumetype = "SAS"
  }
  data_volumes {
    size       = 100
    volumetype = "SAS"
  }
}

failed with error message of 
Invalid node pool type, only support vm and ElasticBMS

**Comment by kittitucht** [comment]
It is my bad that I missed specifying the cluster type when creating the cluster

**Comment by niuzhenguo** [comment]
@Jason-Zhang9309 please have a look at this!

**Comment by Jason-Zhang9309** [comment]
This problem has been fixed with pr #554 . A new required parameter "type" was added. Possible values are: "vm" and "ElasticBMS".
You can update your local repo, make build, and try again.

**Comment by Jason-Zhang9309** [comment]
@kittitucht

**Comment by kittitucht** [comment]
> This problem has been fixed with pr #554 . A new required parameter "type" was added. Possible values are: "vm" and "ElasticBMS".
> You can update your local repo, make build, and try again.


Error: Unsupported argument

  on main.tf line 57, in resource "huaweicloud_cce_node_pool" "node_pool":
  57:   type                     = "vm"

An argument named "type" is not expected here.
Well, I'll wait for a new release then ^^

**Comment by Jason-Zhang9309** [comment]
@kittitucht We found out that it was an API problem. They have fixed it. So your tf script could be useful. Don't add "type", and try again.

**Comment by kittitucht** [comment]
@Jason-Zhang9309 still got the error
Error: Error creating HuaweiCloud Node Pool: Bad request with: [POST https://cce.ap-southeast-2.myhuaweicloud.com/api/v3/projects/09a74fecf6800f022f9cc0091dfa99a4/clusters/3a1419a6-ff41-11ea-bf7f-0255ac1019db/nodepools], error message: {"error_code":"CCE_CM.0201","error_msg":"Request body invalid","message":"invalid node pool type, only support vm and ElasticBMS","errorCode":"E.CFE.4000201","reason":"Request body invalid"}

**Comment by niuzhenguo** [comment]
@kittitucht which region are you using?

**Comment by kittitucht** [comment]
@niuzhenguo I'm using region ap-southeast-2

**Comment by niuzhenguo** [comment]
@kittitucht That's an API side issue, please create a ticket on Cloud side if it still exists.

**Comment by kittitucht** [comment]
@niuzhenguo  I have raised it on Cloud side, but they said that the API can create a node pool
https://support.huaweicloud.com/api-cce/cce_ 02_ 0354.html
![image](https://user-images.githubusercontent.com/55327193/95600593-9790be00-0a7c-11eb-9914-30b665fdeb2a.png)

**Comment by niuzhenguo** [comment]
@kittitucht Do you still face the same problem? If it's not fixed on the Cloud side till now, you can try our new release v1.19.1 which added a new `type` parameter for cce node pool.

**Comment by kittitucht** [comment]
> @kittitucht Do you still face the same problem? If it's not fixed on the Cloud side till now, you can try our new release v1.19.1 which added a new `type` parameter for cce node pool.

I have tried a new release of v1.19.1 and it fixes the problem.

Thank you very much.
