### ISSUE TITLE
DLI ERROR?

### ISSUE THREAD

**Issue by tadeuif** [huaweicloud/terraform-provider-huaweicloud#560]
resource "huaweicloud_dli_queue" "queue" {
  name     = var.name
  cu_count = var.cu_count
}

Apparently, I can't run this simple resource to create the DLI queue, and I really don't know if it's a bug or anything else. 
Error:
```
Error: Error creating sdk client, err=No suitable endpoint could be found in the service catalog.
```
Anyone have experienced this? 
Provider version = 1.19.0
Terraform version = 0.13.2
Thanks!

**Comment by niuzhenguo** [comment]
@tadeuif Which environment are you using? This usually happens when there's no such endpoint in the IAM service catalog.

**Comment by tadeuif** [comment]
> @tadeuif Which environment are you using? This usually happens when there's no such endpoint in the IAM service catalog.

Thx for the answer!
Talking to our Huawei client, it seems to be a problem on the selected region to use. When we use the Hong Kong region the DLI resource works very well and using the LA-Santiago, don't.

**Comment by fabiobo2005** [comment]
@tadeuif and @niuzhenguo I have exactly same behavior to create a DLI-CU using terraform

**Comment by niuzhenguo** [comment]
@tadeuif @fabiobo2005 You can create a ticket on Cloud side to register the endpoint for DLI in that region to fix this. And also we are refactoring this part on Terraform side to not relay on the IAM catalog, which should be done in the next version.

**Comment by ShiChangkuo** [comment]
Hi @tadeuif @fabiobo2005 we do many efforts on the service endpoints since #538, and also support the customizing service endpoints by #741, so the endpoint error will no longer occur and be easy to fix.

I will close it temporarily, If you have any questions, please reopen it. Thanks.
