### ISSUE TITLE
Feature request: bandwidth data source

### ISSUE THREAD

**Issue by namoshizun** [huaweicloud/terraform-provider-huaweicloud#575]
Hiiiii,
Could you please add a data source for "huaweicloud_vpc_bandwidth"? There is "resource" for it but I was unable to find a corresponding data source object. We purchased a shared bandwidth and currently have to hardcode its ID in EIP resources using it....

**Comment by niuzhenguo** [comment]
@namoshizun Thanks for raising this, will try to include it in the next release.
