### ISSUE TITLE
Travis doesn't report status

### ISSUE THREAD

**Issue by galuszkak** [huaweicloud/terraform-provider-huaweicloud#586]
Hi @niuzhenguo @ShiChangkuo ,

Travis doesn't report status in Github from October. See master commits:
<img width="896" alt="Screenshot 2020-10-12 at 11 40 54 AM" src="https://user-images.githubusercontent.com/759579/95731448-d478d280-0c7f-11eb-98aa-e4c40cd8d749.png">

**Comment by niuzhenguo** [comment]
@galuszkak not sure why it happens, seems something wrong with Travis?

**Comment by galuszkak** [comment]
@niuzhenguo I found this:
https://travis-ci.community/t/github-status-not-posted-on-commits-on-repositories-using-legacy-service-integration/7798/9

```We have a few more details to share on this subject.

In the last couple of weeks, we have observed an increased number of failures to post statuses on GitHub. The sources of the increase itself remains unclear, but the repeated problems prompted us to clean up some wasteful requests. This helped a little, but not entirely; at the height of the user activities, we still saw some errors.

We reached out to GitHub, and was granted some additional (but temporary) capacity so that our services can continue. This was yesterday (April 2nd).

We are continuing to reduce waste, so that the issue is resolved for good.

**It is worth repeating that the issue applies only to Legacy integration. GitHub Apps should not exhibit this issue; if you have evidence to show otherwise, please open a separate issue.**
```

I'm not sure how this is integrated now, maybe if it's not the case this should start using Github Apps TravisCI?

**Comment by niuzhenguo** [comment]
@galuszkak It's back now! I login the travis again with my github account and it gets back...
