### ISSUE TITLE
Feature request: VPC Endpoint resource

### ISSUE THREAD

**Issue by ghost** [huaweicloud/terraform-provider-huaweicloud#646]
**Feature**
We are using the VPC endpoint resource on our company, but currently there is no support through Terraform for this, could you include as a new resource?

**Comment by niuzhenguo** [comment]
@julio-cesar-development Thanks for raising this, we will try to include this in the next month release.

**Comment by niuzhenguo** [comment]
@julio-cesar-development Seems we don't have such API on the Service side.

**Comment by ghost** [comment]
Yes, I was trying to circumvent somehow using directly the API, I was following this documentation to create the VPC endpoint https://support.huaweicloud.com/intl/en-us/api-vpcep/vpcep_06_0303.html, but it doesn't seem to be working, and I couldn't find another documentation about.

**Comment by ShiChangkuo** [comment]
@julio-cesar-development the VPC endpoint resources has released in v1.20.2 or later, you can have a try.
Please feel free to open an issue if you hava any problems.
