### ISSUE TITLE
Can't import or apply snat rules

### ISSUE THREAD

**Issue by Juanito87** [huaweicloud/terraform-provider-huaweicloud#830]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### Terraform Version
Run `terraform -v` to show the version. If you are not running the latest version of Terraform, please upgrade because your issue may have already been fixed.

### Affected Resource(s)
Please list the resources as a list, for example:
- opc_instance
- opc_storage_volume

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files
```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

### Debug Output
Please provider a link to a GitHub Gist containing the complete debug output: https://www.terraform.io/docs/internals/debugging.html. Please do NOT paste the debug output in the issue; just paste a link to the Gist.

### Panic Output
If Terraform produced a panic, please provide a link to a GitHub Gist containing the output of the `crash.log`.

### Expected Behavior
What should have happened?
terraform apply or terraform import should work

### Actual Behavior
What actually happened?
Error: Error creatting Snat Rule: json: cannot unmarshal string into go struct field  SnatRule.source_type of type int

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply` to a plan with a snat rule
The rule is created, the applied fails.

Or `terraform import snat id`
With or without the option -allow-missing-config
With or withouth the resource being created in the tf file.

### Important Factoids
Are there anything atypical about your accounts that we should know? For example: Running in EC2 Classic? Custom version of OpenStack? Tight ACLs?

### References
Are there any other GitHub issues (open or closed) or Pull Requests that should be linked here? For example:
- GH-297
- GH-291

**Comment by ShiChangkuo** [comment]
@Juanito87 Thanks for raising this, but I can not find the error message, can you supply the log file? thanks

**Comment by Juanito87** [comment]
Sorry @ShiChangkuo , forgot about the log.
The link to the gist is the following:
https://gist.github.com/Juanito87/e247b54b3e0e59edea9c6dbb09f5963b

**Comment by ShiChangkuo** [comment]
Hi @Juanito87,

I can't catch the error in the log.
Also, a snat rule can be imported with `terraform import -allow-missing-config huaweicloud_nat_snat_rule.snat_1 xxx` in my environment.
can you show me the cli output?

**Comment by Juanito87** [comment]
Yes, this is the cli output @ShiChangkuo 
![WindowsTerminal_8qt1rZKDf7](https://user-images.githubusercontent.com/11276687/105162491-7286ff00-5af1-11eb-9ef3-9dd6114f2edb.png)
According to the documentation [here](https://registry.terraform.io/providers/huaweicloud/huaweicloud/latest/docs/resources/nat_snat_rule) "source_type": "0" (as shown in log) is a valid value for a vpc scenario. That's why I ended up opening the ticket. Maybe I'm doing something wrong, I just starting with terraform. Thanks a lot for the help.

**Comment by ShiChangkuo** [comment]
@Juanito87 the snat rule resides in "la-south-2", right?

I have encountered the issue in some regions as the API response is inconsistent with the [support documentation](https://support.huaweicloud.com/intl/en-us/api-natgateway/nat_apiv2_0013.html).

According to the support documentation, the `source_type` should be an integer rather than string. You can opening a ticket on cloud side to update the API.

If you have any updates, please let us know in time.

**Comment by Juanito87** [comment]
Thanks a lot for the help @ShiChangkuo , I'll get a ticket open with the cloud team. As soon as I get an answer from them, I'll post right back.

**Comment by Juanito87** [comment]
Currently working, thanks for the help.
