### ISSUE TITLE
Error: EIP was not attached to instance

### ISSUE THREAD

**Issue by Jason-Zhang9309** [huaweicloud/terraform-provider-huaweicloud#878]
Hi there,

Sometimes when running acctest, there will be an err like "EIP was not attached to instance".
It seems because the api returns stat code `202`, which means "The task is submitted successfully, the current system is busy, and the issued task will be delayed". But we don't have a stat check func in the code to wait for right stat before finishing the creation.
This problem may affect following operations. Need someone to fix it.

BTW, the api that resource_huaweicloud_compute_eip_associate is using has been deprecated. It's better to use new api(openstack neutron v2.0) for long-term support.

**Comment by ShiChangkuo** [comment]
Hi, @Jason-Zhang9309 @niuzhenguo ,

can we merge `huaweicloud_compute_eip_associate` and `huaweicloud_networking_eip_associate` into one resource?
