### ISSUE TITLE
how to add description field on huaweicloud_networking_secgroup_rule?

### ISSUE THREAD

**Issue by wardenlym** [huaweicloud/terraform-provider-huaweicloud#905]
### Terraform Version
```
Terraform v0.14.6
+ provider registry.terraform.io/huaweicloud/huaweicloud v1.21.0
```

hi, i want to add some custom description on huaweicloud_networking_secgroup_rule just like do that via the cloud console, but i did not see about in documents, how could i do this in v0.14.6? many thx!

**Comment by ShiChangkuo** [comment]
@wardenlym thanks for raising this, will try to implement the feature before the last day of February.

**Comment by ShiChangkuo** [comment]
@Lance52259 can you please help with this when you are free, thanks!
