### ISSUE TITLE
Huawei cloud provider not work specific iam endpoint

### ISSUE THREAD

**Issue by DaulGitHub** [huaweicloud/terraform-provider-huaweicloud#907]
Simple the code example

    terraform {
      required_providers {
        huaweicloud = {
          source = "huaweicloud/huaweicloud"
          version = "1.21.0"
       }
    }
    }

    provider "huaweicloud" {
      region      = "cn-north-3"
      access_key  = "*****"
      secret_key  = "*****"

      endpoints = {
        iam = "https://iam.cn-north-3.huawei.com"
        vpc = "https://vpc.cn-north-3.huawei.com"
      }
    }

    # Create a VPC
    resource "huaweicloud_vpc" "example" {
      name = "my_terraform_vpc"
      cidr = "192.168.0.0/16"
    }

on start up I get an error:
Error: Authentication failed

  on main.tf line 11, in provider "huaweicloud":
  11: provider "huaweicloud" {

In the log I see: 
huaweiCloud Request URL: GET https://iam.myhuaweicloud.com:443/v3/projects?name=cn-north-3

why the request doesn't go to "https://iam.cn-north-3.huawei.com" ?

**Comment by ShiChangkuo** [comment]
@DaulGitHub could you try to add `auth_url = "https://iam.cn-north-3.huawei.com"` in your provider configuration?

**Comment by DaulGitHub** [comment]
@ShiChangkuo thank you!)
it helped, but now I have this error

Error: Get "https://iam.cn-north-3.huawei.com/": HuaweiCloud connection error, retries exhausted. Aborting. Last error was: x509: certificate is valid for *.cn-north-3.myhuaweicloud.com, cn-north-3.myhuaweicloud.com, not iam.cn-north-3.huawei.com

How can I fix this problem?

**Comment by DaulGitHub** [comment]
I resolve my problem 
set variable
insecure = true

Thanks!)

**Comment by ShiChangkuo** [comment]
maybe `insecure = true` will help you
