### ISSUE TITLE
Auto Capacity Expansion for SFS

### ISSUE THREAD

**Issue by alexandrovas** [huaweicloud/terraform-provider-huaweicloud#911]
Hello!

I want to create file share with unlimited capacity.
There is resource `huaweicloud_sfs_file_system`, but parameter `size` is Required.
How I can use Auto Capacity Expansion feature in terraform configuration?

In my Huawei cloud Web-UI this option is available:
![image](https://user-images.githubusercontent.com/49055338/107242902-87461b00-6a3d-11eb-9e34-30ea37a0547a.png)

**Comment by ShiChangkuo** [comment]
@alexandrovas sorry, we can not implement this feature due to the [API limitation](https://support.huaweicloud.com/intl/en-us/api-sfs/sfs_02_0021.html#section2).

**Comment by ShiChangkuo** [comment]
@alexandrovas After checking with the sfs R&D team, you can enable auto capacity expansion with #sfs_quota_type metadata.
The configuration as follows:

```
resource "huaweicloud_sfs_file_system" "share-file" {
  ...
  size     = 100
  metadata = {
    "#sfs_quota_type" = "soft"
  }
}
```

if it works, I will make **size** be optional and default to 100GB.
