### ISSUE TITLE
Server group managing

### ISSUE THREAD

**Issue by alexandrovas** [huaweicloud/terraform-provider-huaweicloud#913]
Hello!

How I can create server group and add servers to it?
I see there is resourse `huaweicloud_compute_servergroup`, but no resources for group membership managing.

**Comment by ShiChangkuo** [comment]
Hi, @alexandrovas

you can add a server to group in `huaweicloud_compute_instance.scheduler_hints` block:
```
resource "huaweicloud_compute_instance" "instance_1" {
  ...
  scheduler_hints {
    group = huaweicloud_compute_servergroup.sg_1.id
  }
}
```

**Comment by alexandrovas** [comment]
This code will re-create the instance. How I can add ECS to group without recreating?

**Comment by ShiChangkuo** [comment]
That's an excellent suggestion, will implement it in the next release.
