### ISSUE TITLE
what is the available options for  "flavor_id" and "container_network_type"

### ISSUE THREAD

**Issue by tianxiaoliang** [huaweicloud/terraform-provider-huaweicloud#92]
resource "huaweicloud_cce_cluster_v3" "cluster_1" {
  name = "cluster"
  cluster_type= "VirtualMachine"
  flavor_id= "${var.flavor_id}"
  vpc_id= "${var.vpc_id}"
  subnet_id= "${var.subnet_id}"
  container_network_type= "overlay_l2"
  description= "Create cluster"
}

**Comment by niuzhenguo** [comment]
@tianxiaoliang Please refer to https://github.com/terraform-providers/terraform-provider-huaweicloud/blob/master/website/docs/r/cce_cluster_v3.html.md
The terraform docs will update once v1.4.0 released.

**Comment by niuzhenguo** [comment]
Please checkout the updated docs https://www.terraform.io/docs/providers/huaweicloud/r/cce_cluster_v3.html

**Comment by tianxiaoliang** [comment]
thanks
