### ISSUE TITLE
Support of additional route types

### ISSUE THREAD

**Issue by alexandrovas** [huaweicloud/terraform-provider-huaweicloud#926]
Hello!

Can you implement supporting another types of routes in `huaweicloud_vpc_route` resource?
Currently only `peering` type is supported.

**Comment by ShiChangkuo** [comment]
@alexandrovas Thanks for raising this.

Now the route type canonly be peering due to the [API limitation](https://support.huaweicloud.com/intl/en-us/api-vpc/vpc_route_0003.html). We will support more types once the API updated.
