### ISSUE TITLE
where can I see the auth url in huawei cloud console

### ISSUE THREAD

**Issue by tianxiaoliang** [huaweicloud/terraform-provider-huaweicloud#93]
provider "huaweicloud" {
  access_key = "xxx"
  secret_key = "xxx"
  region     = "cn-north-1"
  **auth_url**    = "https://iam.cn-north-1.myhwclouds.com/v3"
}

**Comment by niuzhenguo** [comment]
@tianxiaoliang You can find that on API docs. https://support.huaweicloud.com/en-us/api-ecs/en-us_topic_0124306062.html

**Comment by Thomas999999** [comment]
Hi niuzhenguo,
I cannot find any hint in your reference how to obtain the value for auth_url.
How can a user easily see his Identity authentication URL.

Thanks!
Thomas

**Comment by niuzhenguo** [comment]
@Thomas999999 here is the region and endpoints link https://developer.huaweicloud.com/en-us/endpoint , combined with the link above you should be able to get the auth_url. Seems we don't expose  that info on console for users as only API developers need it :(

**Comment by niuzhenguo** [comment]
@tianxiaoliang @Thomas999999 Can we close this now?

**Comment by Thomas999999** [comment]
Yes from my point of view: but maybe giving the hint to https://developer.huaweicloud.com/en-us/endpoint in the providers doc would maybe help the customer

**Comment by niuzhenguo** [comment]
@Thomas999999 OK, will update the provider doc soon!
