### ISSUE TITLE
huaweicloud_vpc_v1.vpc_v1: Error creating Huaweicloud vpc client: No suitable endpoint could be found in the service catalog.

### ISSUE THREAD

**Issue by Thomas999999** [huaweicloud/terraform-provider-huaweicloud#96]
Hi there,

### Terraform Version
Terraform v0.11.11
+ provider.huaweicloud v1.3.0

### Affected Resource(s)
huaweicloud_vpc_v1

### Terraform Configuration Files
##VPC creation
resource "huaweicloud_vpc_v1" "vpc_v1" {
  name = "${var.cce_cluster_name}-vpc"
  cidr = "192.168.0.0/16"
  region = "${var.region}"
}

#subnet creation
resource "huaweicloud_vpc_subnet_v1" "subnet_1" {
  name = "${var.cce_cluster_name}-subnet1"
  cidr = "192.168.0.0/24"
  gateway_ip = "192.168.0.1"
  vpc_id = "${huaweicloud_vpc_v1.vpc_v1.id}"
}

#subnet creation
resource "huaweicloud_vpc_subnet_v1" "subnet_2" {
  name = "${var.cce_cluster_name}-subnet2"
  cidr = "192.168.48.0/20"
  gateway_ip = "192.168.48.1"
  vpc_id = "${huaweicloud_vpc_v1.vpc_v1.id}"
}

#subnet creation
resource "huaweicloud_vpc_subnet_v1" "subnet_3" {
  name = "${var.cce_cluster_name}-subnet3"
  cidr = "192.168.255.0/24"
  gateway_ip = "192.168.255.1"
  vpc_id = "${huaweicloud_vpc_v1.vpc_v1.id}"
}

### Expected Behavior
VPC should be created

### Actual Behavior
Getting error:
*** huaweicloud_vpc_v1.vpc_v1: Error creating Huaweicloud vpc client: No suitable endpoint could be found in the service catalog.**

Comlete output:
terraform apply

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  + huaweicloud_vpc_subnet_v1.subnet_1
      id:                <computed>
      availability_zone: <computed>
      cidr:              "192.168.0.0/24"
      dhcp_enable:       "true"
      dns_list.#:        <computed>
      gateway_ip:        "192.168.0.1"
      name:              "d021970_cce-subnet1"
      primary_dns:       <computed>
      region:            <computed>
      secondary_dns:     <computed>
      subnet_id:         <computed>
      vpc_id:            "${huaweicloud_vpc_v1.vpc_v1.id}"

  + huaweicloud_vpc_subnet_v1.subnet_2
      id:                <computed>
     availability_zone: <computed>
      cidr:              "192.168.48.0/20"
      dhcp_enable:       "true"
      dns_list.#:        <computed>
      gateway_ip:        "192.168.48.1"
      name:              "d021970_cce-subnet2"
      primary_dns:       <computed>
      region:            <computed>
      secondary_dns:     <computed>
      subnet_id:         <computed>
      vpc_id:            "${huaweicloud_vpc_v1.vpc_v1.id}"

  + huaweicloud_vpc_subnet_v1.subnet_3
      id:                <computed>
      availability_zone: <computed>
      cidr:              "192.168.255.0/24"
      dhcp_enable:       "true"
      dns_list.#:        <computed>
      gateway_ip:        "192.168.255.1"
      name:              "d021970_cce-subnet3"
      primary_dns:       <computed>
      region:            <computed>
      secondary_dns:     <computed>
      subnet_id:         <computed>
      vpc_id:            "${huaweicloud_vpc_v1.vpc_v1.id}"

  + huaweicloud_vpc_v1.vpc_v1
      id:                <computed>
      cidr:              "192.168.0.0/16"
      name:              "d021970_cce-vpc"
      region:            "cn-east-2b"
      shared:            <computed>
      status:            <computed>

Plan: 4 to add, 0 to change, 0 to destroy.

Do you want to perform these actions in workspace "provider"?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

huaweicloud_vpc_v1.vpc_v1: Creating...
  cidr:   "" => "192.168.0.0/16"
  name:   "" => "d021970_cce-vpc"
  region: "" => "cn-east-2b"
  shared: "" => "<computed>"

  status: "" => "<computed>"
Error: Error applying plan:

1 error(s) occurred:

* huaweicloud_vpc_v1.vpc_v1: 1 error(s) occurred:

*** huaweicloud_vpc_v1.vpc_v1: Error creating Huaweicloud vpc client: No suitable endpoint could be found in the service catalog.**

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

**Note** 
I used 3 different auth_url in the provider.tf, but for all the same error above:
variable "auth_url" {
  description = "Enter... "
  #default = "https://iam.cn-east-2.myhwclouds.com:443/v3"
  #default = "https://iam.myhwclouds.com:443/v3"
  default = "https://iam.cn-east-2.myhuaweicloud.com:443/v3"
} 

What could be the issue for that Error?

Thanks,
Thomas

**Comment by niuzhenguo** [comment]
@Thomas999999 The problem here is the `region: "" => "cn-east-2b"`, region should be `cn-east-2`. 
`cn-east-2a` and `cn-east-2b` are availability_zones instead of region.

**Comment by Thomas999999** [comment]
Thanks, that worked now
