### ISSUE TITLE
Missing description in huaweicloud_identity_user resource

### ISSUE THREAD

**Issue by alexandrovas** [huaweicloud/terraform-provider-huaweicloud#962]
Hello!

I have code for creating IAM users:
```hcl
resource "huaweicloud_identity_user" "bucket-user" {
  name        = "stage1_s3"
  description = "Service account for stage 1 S3 buckets"
}
```

terraform state:
```json
{
      "mode": "managed",
      "type": "huaweicloud_identity_user",
      "name": "bucket-user",
      "provider": "provider[\"registry.terraform.io/huaweicloud/huaweicloud\"]",
      "instances": [
        {
          "schema_version": 0,
          "attributes": {
            "access_type": "",
            "country_code": "",
            "create_time": "",
            "description": "",
            "email": "",
            "enabled": true,
            "id": "xxxxxxxxxx",
            "last_login": "",
            "name": "stage1_s3",
            "password": null,
            "password_stength": "",
            "phone": ""
          },
          "private": "xxxxxxx"
        }
      ]
    }
```

Terraform plan shows:
```
# huaweicloud_identity_user.bucket-user will be updated in-place
  ~ resource "huaweicloud_identity_user" "bucket-user" {
      + description = "Service account for stage1 S3 buckets"
        enabled     = true
        id          = "xxxxxxx"
        name        = "stage1_s3"
    }
```

But after apply this field is still empty.

Same for other fields: `create_time`, `last_login`.

Provider version: 1.22.0

**Comment by ShiChangkuo** [comment]
@alexandrovas I tested well in huaweicloud. Have you try the [sbercloud provider](https://registry.terraform.io/providers/sbercloud-terraform/sbercloud/latest/docs)?

**Comment by alexandrovas** [comment]
@ShiChangkuo I saw that this provider exists. At the moment, it simply duplicates the functionality of provider huaweicloud and contains fewer features. Therefore, we are not using it at the moment.

**Comment by alexandrovas** [comment]
@ShiChangkuo You may not have correctly understood the problem described. After applying this field is still empty in terraform state but not in cloud. This leads to the fact that the next time the applying, terraform wants to update these resources again.
In the cloud, this fields is filled in correctly.
In state this fields remain empty.

**Comment by ShiChangkuo** [comment]
some attributes may be miss when fetching from the cloud, could you get the debug logs?

**Comment by alexandrovas** [comment]
I found source of this issue. Sbercloud have the old version of IAM service, and API is defferent.
Huaweicloud API: https://support.huaweicloud.com/intl/en-us/api-iam/iam_08_0003.html
Sbercloud API: https://support.hc.sbercloud.ru/api/iam/en-us_topic_0207901489.html

I contacted the technical support of Sberсloud, they promised to update the version of IAM service in the near future.

**Comment by ShiChangkuo** [comment]
@alexandrovas
I just saw the API was updated in Sbercloud: https://support.hc.sbercloud.ru/api/iam/iam_08_0004.html 
Please have a try.

**Comment by alexandrovas** [comment]
Yes, you are right.
It,s working. Thank you.
