### ISSUE TITLE
resource huaweicloud_vpc_eip There is no monthly package option

### ISSUE THREAD

**Issue by HS-Gong** [huaweicloud/terraform-provider-huaweicloud#963]
When using Huaweicloud_ vpc_eip When EIP creates EIP of elastic public network, it is found that there is no annual and monthly package parameter, only on-demand charging. When can I use update the monthly package parameters？

**Comment by ShiChangkuo** [comment]
@HS-Gong Thanks for raising this issue. For now, only compute_instance and gaussdb support prePaid mode.

We will do some research on the possiblity to support more resources as the ablity depends on API.

**Comment by HS-Gong** [comment]
hi Is this function available now

**Comment by ShiChangkuo** [comment]
@HS-Gong we will release the feature before the end of June.
