### ISSUE TITLE
huaweicloud_cce_node_v3: missing key for OS configration

### ISSUE THREAD

**Issue by Thomas999999** [huaweicloud/terraform-provider-huaweicloud#97]
Hi there,

### Affected Resource(s)
**huaweicloud_cce_node_v3**

### Expected Behavior
I would expect to have key for **huaweicloud_cce_node_v3** to define the 2 different OS versions available for the worker nodes environment:
- Euler OS 2.2
- CentOS 7.4

Both OS can be configured if manually creating cluster node in console.

### Actual Behavior
I cannot find any key for that at: https://www.terraform.io/docs/providers/huaweicloud/r/cce_nodes_v3.html 

If a key is not yet available, should I open again an service support ticket on Huawei console to request to update API in order to get this in terraform resource?

Thanks in advance,
Thomas

**Comment by niuzhenguo** [comment]
@Thomas999999 You don't need to open a service ticket again, I already got the way to specify OS versions, will work on this later, thanks for raising this!

**Comment by niuzhenguo** [comment]
@Thomas999999 on my tests, it's CentOS 7.1 instead of CentOS 7.4

**Comment by Thomas999999** [comment]
Hi,

I just saw your new adaption:
"`os` - (Optional) Operating System of the node, possible values are EulerOS 2.2 and CentOS 7.1. Defaults to EulerOS 2.2.
    Changing this parameter will create a new resource."

Thanks for that, but some questions/remark to that:
- I see in Huawei console only the release 7.4 available for CentOS 
  ![image](https://user-images.githubusercontent.com/44159345/55466686-f6f84d00-55ff-11e9-8f69- 
  e58c74199a17.png)
- Nevertheless, as over time this may change to higher releases, wouldn't it be better just to have "EulerOS" and "CentOS" as parameter and for key os and then pick automatically the latest available release defiined by HUAWEI?

Thanks for your patient.
Thomas

**Comment by niuzhenguo** [comment]
@Thomas999999 That sounds good, but there not an API for us to fetch the latest available OS release :(
Regarding the CentOS version, which region do you use? not sure why we aren't on the same page.

**Comment by Thomas999999** [comment]
Hi,
I'm in region CN-east-Shanghai2.

Maybe you can trigger to get such an API?

Thanks,
Thomas

**Comment by niuzhenguo** [comment]
@Thomas999999 I just want to check why we don't have the same CentOS version.

**Comment by niuzhenguo** [comment]
@Thomas999999 Seems when you create the node with cluster creating process, it shows 7.4， but if you try to add a node afterwards it's 7.1.

**Comment by Thomas999999** [comment]
Hi,

I tried today with
os                 = "${var.cce_node_os}"

but C:\Testinfo\AWS_Dathub_Vora\Huawei-Cluster\cluster-dev>terraform plan
Error: huaweicloud_cce_node_v3.cce_node[0]: : invalid or unknown key: os

**Comment by Thomas999999** [comment]
Dear Niuzhenguo,

when do you think this "os" key may be available in terraform?
Thanks
