### ISSUE TITLE
Feature request: import of huaweicloud_networking_vip_associate

### ISSUE THREAD

**Issue by alexandrovas** [huaweicloud/terraform-provider-huaweicloud#987]
Hello!

Can you add the ability to import huaweicloud_networking_vip_associate resource?

**Comment by alexandrovas** [comment]
@ShiChangkuo

I think this is trivial for implementation, because creation of huaweicloud_networking_vip_associate resource is already implemented.
Can this be added in the next version of provider?

**Comment by ShiChangkuo** [comment]
Hi, @alexandrovas 

sorry for late response.
can you give more details about why you need to import the `huaweicloud_networking_vip_associate` ?

**Comment by alexandrovas** [comment]
In our project we have legacy VIPs which was created manually. I wanted to import this resources to terraform configuration but discovered that it is unsupported. Howewer import of huaweicloud_networking_vip resourse is implemented. It turns out that i can import VIP but cannot import of huaweicloud_networking_vip_associate resourse.
I think that import of huaweicloud_networking_vip_associate resourse should be implemented also.

**Comment by ShiChangkuo** [comment]
Actually, all the relational resources (end with _associate or _attach) can not be imported. 
For huaweicloud_networking_vip_associate, you can create a new resource with associated port IDs to manage your existing VIPs.

**Comment by alexandrovas** [comment]
@ShiChangkuo 

huaweicloud_compute_volume_attach can be imported:
![image](https://user-images.githubusercontent.com/49055338/117987569-4531bb80-b343-11eb-96d8-79562812c8bc.png)

huaweicloud_compute_interface_attach can be imported:
![image](https://user-images.githubusercontent.com/49055338/117987659-5d093f80-b343-11eb-82fc-dec0fe1c68e6.png)

huaweicloud_compute_eip_associate can be imported:
![image](https://user-images.githubusercontent.com/49055338/117987742-727e6980-b343-11eb-9acc-ae9e7f2b1fe7.png)

huaweicloud_networking_eip_associate can be imported:
![image](https://user-images.githubusercontent.com/49055338/117987856-89bd5700-b343-11eb-9d08-4540c16ef202.png)

Why resource huaweicloud_networking_vip_associate can not be imported? 😃

**Comment by ShiChangkuo** [comment]
@alexandrovas You are right, other relational resources can be imported expect `huaweicloud_networking_vip_associate`.

The reasom maybe the resource includes a list of port not a single, and we should use many  arguments when importing it.

You can create a new  `huaweicloud_networking_vip_associate` resource and execute `terraform apply`. Fortunately, there is no harm to bind ports to the vip tiwce.

**Comment by ShiChangkuo** [comment]
I'm going to close this issue because there are no updates for 20 days.
If you have found a problem that seems similar to this, please open a new issue and complete the issue template so we can capture all the details necessary to investigate further.
