### ISSUE TITLE
Assign EIP to RDS?

### ISSUE THREAD

**Issue by ippeter** [huaweicloud/terraform-provider-huaweicloud#988]
Hello!

It seems that it's not possible to assign EIP to RDS.

huaweicloud_rds_instance doesn't seem to support it explicitly.
huaweicloud_networking_eip_associate requires a port, and I can't figure out how to get the RDS network port.

Any plans to add it? Or did I miss anything?

Best regards,
Peter.

**Comment by ShiChangkuo** [comment]
@ippeter you can get the usage from the [examples](https://github.com/huaweicloud/terraform-provider-huaweicloud/tree/master/examples/rds/mysql-with-eip).

**Comment by ippeter** [comment]
@ShiChangkuo Dear Changkuo, thank you very much!
