### ISSUE TITLE
支持服务列表询问

### ISSUE THREAD

**Issue by si7eka** [huaweicloud/terraform-provider-huaweicloud#992]
![image](https://user-images.githubusercontent.com/15117469/111592003-2c090480-8803-11eb-9304-ed3b70487eed.png)
请问目前是只支持这些服务吗？

**Comment by Jason-Zhang9309** [comment]
感谢关注，目前官网文档尚未包含全部已支持服务，实际已支持的服务还有很多
请看这里 https://registry.terraform.io/providers/huaweicloud/huaweicloud/latest/docs

**Comment by si7eka** [comment]
希望可以在官网看到更多的中文资料

**Comment by Lance52259** [comment]
感谢支持华为云，后续我们会逐步添加其他资源的中文资料至Terraform用户指南中

**Comment by ShiChangkuo** [comment]
I'm going to close this issue because there are no updates for 20 days.
If you have found a problem that seems similar to this, please open a new issue and complete the issue template so we can capture all the details necessary to investigate further.
